### ISSUE TITLE
bug: If we add 'graphql-dgs-extended-validation', then in 'TracingInstrumentation.instrumentDataFetcher' method, 'parameters.isTrivialDataFetcher()' always returns false

### ISSUE THREAD

**Issue by springmonster** [Netflix/dgs-framework#1004]
## Expected behavior
Add 'graphql-dgs-extended-validation' and 'TracingInstrumentation', expect only method execution time and total execution time will display

## Actual behavior
Add 'graphql-dgs-extended-validation'and 'TracingInstrumentation'. DataFetcher type will be transformed into 'FieldValidatorDataFetcher', not 'TrivialDataFetcher', so 'parameters.isTrivialDataFetcher()' always returns false. Each field will display 

## Steps to reproduce
1. Add 'graphql-dgs-extended-validation'
2. Add 'TracingInstrumentation' from official document
3. Check logs

**Comment by berngp** [comment]
Thanks for reporting.

**Comment by kilink** [comment]
I think this is actually an issue within [graphql-java-extended-validation](https://github.com/graphql-java/graphql-java-extended-validation/blob/master/src/main/java/graphql/validation/schemawiring/ValidationSchemaWiring.java#L54), so shoud likely be fixed there. I am curious what issue it is causing?

**Comment by springmonster** [comment]
> I think this is actually an issue within [graphql-java-extended-validation](https://github.com/graphql-java/graphql-java-extended-validation/blob/master/src/main/java/graphql/validation/schemawiring/ValidationSchemaWiring.java#L54), so shoud likely be fixed there. I am curious what issue it is causing?

Hi @kilink , current now all fields record into file system and we only want to log method information. Is there a way to achieve this? Thanks very much!

**Comment by springmonster** [comment]
Close this issue. Create it in  graphql-java-extended-validation.

https://github.com/graphql-java/graphql-java-extended-validation/issues/69
