### ISSUE TITLE
feature: Add RSocket support as transport 

### ISSUE THREAD

**Issue by hzariv** [Netflix/dgs-framework#1010]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue. Also consider discussing your idea on
the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) first.

## Describe the Feature Request
Add GraphQL over RSocket instead of HTTP as transport.

## Describe Preferred Solution
Spring Boot GraphQL supports this: https://docs.spring.io/spring-graphql/docs/current-SNAPSHOT/reference/html/#server-rsocket

## Describe Alternatives
WebSocket is the alternative.

**Comment by paulbakker** [comment]
Now supported through the DGS / Spring GraphQL integration.
