### ISSUE TITLE
regression: Latest version 4.10.x seems to cause an error with implementing DgsCustomContextBuilderWithRequest<T> in Kotlin

### ISSUE THREAD

**Issue by resonantfreq** [Netflix/dgs-framework#1029]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior 
Normal compiling with no issues with class implementation of interface

## Actual behavior
Seeing this error now during compile, tests, builds: 

`Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option`

## Steps to reproduce
Use gradle and add the latest dgs versions as outlined in documentation. Implement a Spring Boot component
```

@Component
class CustomContextBuilder: DgsCustomContextBuilderWithRequest<CustomContext> {
    override fun build(extensions: Map<String, Any>?, headers: HttpHeaders?, webRequest: WebRequest?): CustomContext {
        
        return CustomContext(
            foo = "bar"
        )
    }

}

class CustomContext {
    val foo: String?
}
```

Try compiling and it should throw an error on the CustomContextBuilder class stating the error above. 

_Note: A test case would be highly appreciated, but we understand that's not always possible_ 

After downgrading to version 4.9.25 did the error stop.

**Comment by berngp** [comment]
Thanks for reporting this issue @resonantfreq.

**Comment by NfNitLoop** [comment]
👋 I'm affected by this one too.  (Though, full disclosure, @resonantfreq and I work together.) 

We were a bit stumped by this one. AFAICT [DgsCustomContextBuilderWithRequest] doesn't have any `default` methods and hasn't been modified recently, so not sure what could be causing the issue. I look forward to learning about it once y'all figure it out. 😊 

[DgsCustomContextBuilderWithRequest]: https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/context/DgsCustomContextBuilderWithRequest.kt

**Comment by berngp** [comment]
I upgraded the Kotlin Version int he latest minor release, I thought that setting the `-Xjvm-default` to `all-compatibility` will prevent this. [Ref](https://github.com/Netflix/dgs-framework/blob/master/build.gradle.kts#L140-L141).
Will address this asap and get a new release out.

**Comment by kilink** [comment]
@resonantfreq what version of Kotlin are you on? It appears to me this issue was [fixed in 1.6.20](https://youtrack.jetbrains.com/issue/KT-47000/Allow-graceful-migration-to-Xjvm-default-all-compatibility-by-al).

**Comment by NfNitLoop** [comment]
Aha, yep! I had a `build.gradle.kts` that was still using v1.6.10.  Upgrading to 1.6.20 (and .21) fixed it for me.

I'd recommend updating the BOM to require Kotlin 1.6.20+ if things are expected to break without it.

**Comment by resonantfreq** [comment]
@kilink confirmed that it is also working for me after upgrading all the dependancies including Kotlin to the latest `1.6.21`

Thanks so much for the prompt reply. 

Hope this helps others.

**Comment by berngp** [comment]
Having a stricter recommendation on the Kotlin version is a great idea. Tbh this caught me by surprise.


Thanks @kilink for helping in the thread.
