### ISSUE TITLE
Keep hash comments out of the runtime schema by default, or as an option

### ISSUE THREAD

**Issue by seanf** [Netflix/dgs-framework#1031]
### Discussed in https://github.com/Netflix/dgs-framework/discussions/995

<div type='discussions-op-text'>

<sup>Originally posted by **seanf** April 20, 2022</sup>
If my GraphQL schema file contains "private" hash comments (as opposed to docstring descriptions), is there an easy way to have DGS expose the schema _without_ the hash comments? 
<br>
Unfortunately, `graphql.schema.idl.SchemaGenerator` treats comments as descriptions by default (for historical reasons), which means that they appear in the schema introspection (along with real docstring descriptions). The `SchemaGenerator` option `useCommentsAsDescriptions(false)` gives the desired behaviour, but I can't find a way to configure the `SchemaGenerator` which DGS uses.
<br>
Related: https://github.com/graphql-java/graphql-java/discussions/2765#discussioncomment-2410907 and https://github.com/apollographql/federation-jvm/blob/7d05eb2ef896f812ad284dc1df0c494c9567e64c/graphql-java-support/src/main/java/com/apollographql/federation/graphqljava/Federation.java#L26-L27
<br>
EDIT: See also https://github.com/apollographql/federation-jvm/issues/163</div>

I have requested https://github.com/apollographql/federation-jvm/issues/163, but unless Federation changes the default behaviour, DGS would require code changes too.

**Comment by srinivasankavitha** [comment]
We could potentially expose a config property to do the same and apply that
on the SchemaGenerator. I am a bit reluctant to add more properties though,
since this is the only request we've had so far for doing this.

**Comment by seanf** [comment]
Thanks for the reply @srinivasankavitha.

> We could potentially expose a config property to do the same and apply that
on the SchemaGenerator. I am a bit reluctant to add more properties though,
since this is the only request we've had so far for doing this.

I understand, but I suspect this affects more people than might realise it. I had no idea that schema comments were visible as descriptions in GraphiQL/introspection until I found it by accident. I think it's a pretty surprising default, even if it has historical precedent for GraphQL Java. 

Right now I have to use an unpleasant reflection-based hack to work around it. As far as I can see, it's either that or maintain my own fork of either Federation or DGS. Is there some middle ground change that would allow me to avoid that?

Incidentally, do you have any thoughts on my suggestion in https://github.com/apollographql/federation-jvm/issues/163? It hasn't had any attention from the Federation team yet.

**Comment by srinivasankavitha** [comment]
Apologies for the delayed responses. We've been a bit caught up with other priorities internally. I think it does make sense to just have a config property to expose this. We will look into adding that.
Regarding making this the default behavior in federation-jvm, that's probably not the right place to do it. Perhaps `graphql-java` might be a better place. That said, I'm not sure there are many folks who would want this to be the default setting.

**Comment by aabdelhafez** [comment]
> That said, I'm not sure there are many folks who would want this to be the default setting.

After migrating some of our subgraphs from Apollo Server (Node.js) to DGS (Kotlin), we discovered by accident (just like @seanf) that comments were suddenly exposed to the ouside world and are made available via introspection. We checked the GraphQL spec, and it states that [comments ought to be ignored](https://spec.graphql.org/October2021/#sec-Comments).

> Comments are [Ignored](https://spec.graphql.org/October2021/#Ignored) like white space and may appear after any token, or before a [LineTerminator](https://spec.graphql.org/October2021/#LineTerminator), and have no significance to the semantic meaning of a GraphQL Document.

That is to say that we also assumed that the default setting in DGS (or `graphql-java`) is ignoring comments 😃

**Comment by srinivasankavitha** [comment]
We will update such that the default option is to hide the comments. As an enhancement, we can also offer a configuration option to change this behavior.
```
ParserOptions.newParserOptions().captureLineComments(false)
```

**Comment by srinivasankavitha** [comment]
@codeWithUtkarsh

**Comment by codeWithUtkarsh** [comment]
As discussed, I will be picking this up.

**Comment by kevinh-autoserve1** [comment]
Any time frame for when this might land? 
We have the same need for comments not being treated as descriptions.

**Comment by srinivasankavitha** [comment]
We will fix this for the next release, likely in a week.

**Comment by pjungels-paraport** [comment]
Any updates on this?

**Comment by srinivasankavitha** [comment]
Not yet, we had to deprioritize this at the time. I'll add it back to our backlog for this quarter.

**Comment by hpuac** [comment]
Hey @srinivasankavitha as the quarter has passed by, is there any update? 🙂 
Just asking because it's preventing us from having internal in-schema comments as the current implementation is going against the GraphQL spec.

**Comment by srinivasankavitha** [comment]
Hi @hpuac - apologies, we've been working on other priorities and this got side tracked. @kailyak will be looking into this ticket this week.

**Comment by kailyak** [comment]
Hi @hpuac, an update, I looked into this and it's not possible right now due to the way federation-jvm transforms the schema using default options. I have opened an [issue in federation-jvm](https://github.com/apollographql/federation-jvm/issues/389) which has more details and am following up on it.

**Comment by hpuac** [comment]
Thx a lot for the update and taking care! 🙂

**Comment by dariuszkuc** [comment]
👋 I've added another overloaded `transform` method to `federation-jvm` that allows folks to specify custom generator options. This is available starting with v`5.0.0` which was just released (bumps `graphql-java` dependency to v`22`)

```java
  public static SchemaTransformer transform(
      final TypeDefinitionRegistry typeRegistry,
      final RuntimeWiring runtimeWiring,
      final SchemaGenerator.Options generatorOptions)
```

**Comment by kailyak** [comment]
Thank you @dariuszkuc! 
@hpuac, the change needs to be integrated into the dgs-framework and is blocked by updating to graphql-java v22. We will update to graphql-java22 then add the change to disable SDL comments.

**Comment by kailyak** [comment]
Hello, closing this as the change has been merged. This will be available in the next release.
