### ISSUE TITLE
bug: DGS Webflux subscriptions' responses different to DGS MVC WebSocket

### ISSUE THREAD

**Issue by jvalde** [Netflix/dgs-framework#1036]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
Consistent behaviour between DGS Webflux (Reactive) and DGS MVC subscriptions

### Given the following Graphql subscription:

```
type Subscription {
    stocks: Stock
}

type Stock {
    name: String
    price: Float
}
```

### Given the following query
```
subscription StockWatch { stocks { name price } }
```

### Then, DGS Webflux subscription response:
```json
{
    "errors": [],
    "data": {
        "stocks": {
            "name": "NFLX",
            "price": 500.0
        }
    },
    "extensions": null,
    "dataPresent": true
}
```

### Then, DGS MVC subscription response:
```json
{
    "data": {
        "stocks": {
            "name": "NFLX",
            "price": 500.0
        }
    },
    "errors": []
}
```

The DGS Webflux subscription adds two extra fields, **extensions** and **dataPresent**, to its response.

This issue is twofold, firstly dataPresent is not part of the Graphql Spec. Secondly, WebSocketGraphQLClient does not support responses that contain extensions or dataPresent.

Using  WebSocketGraphQLClient to subscribe to a DGS Webflux subscription throws the following exception:

`reactor.core.Exceptions$ErrorCallbackNotImplemented: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "extensions" (class com.netflix.graphql.types.subscription.DataPayload), not marked as ignorable (2 known properties: "data", "errors"])`

## Steps to reproduce
Run the following test - DGS Webflux subscription. **It will fail**.
[Tes DGS Webflux Websocket Subscription](https://github.com/jvalde/dgs-framework/blob/bug/dgs-webflux-subscription-response/graphql-dgs-example-java-webflux/src/test/java/subsciption/integrationtest/SubscriptionIntegrationTest.java)

There is an existing test for DGS MVC subscription. **It will pass**.
[Tes DGS MVC Websocket Subscription](https://github.com/jvalde/dgs-framework/blob/bug/dgs-webflux-subscription-response/graphql-dgs-example-java/src/test/java/subsciption/integrationtest/SubscriptionIntegrationTest.java)

_Note: A test case would be highly appreciated, but we understand that's not always possible 

## Useful pointers

[DGS Webflux subscription response](https://github.com/jvalde/dgs-framework/blob/0bd898e241f73a9d024be94105286aef2013d7e4/graphql-dgs-spring-webflux-autoconfigure/src/main/kotlin/com/netflix/graphql/dgs/webflux/handlers/DgsReactiveWebsocketHandler.kt#L76)

[DGS MVC subscription response](https://github.com/jvalde/dgs-framework/blob/0bd898e241f73a9d024be94105286aef2013d7e4/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L121)

[Payload used by WebSocketGraphQLClient](https://github.com/jvalde/dgs-framework/blob/0bd898e241f73a9d024be94105286aef2013d7e4/graphql-dgs-subscription-types/src/main/kotlin/com/netflix/graphql/types/subscription/OperationMessage.kt#L66)

**Comment by berngp** [comment]
Fixed by #1050
