### ISSUE TITLE
bug: Getting tracing data for all the requests

### ISSUE THREAD

**Issue by AyushChaubey** [Netflix/dgs-framework#1037]
This issue is an extension of the [original](https://github.com/Netflix/dgs-framework/issues/930) issue which I had raised. The documentation was updated to suggest what needs to be done to enable tracing in a federated setup.

The issue now is that we are getting the tracing information for all the requests. Even though the tracing information is not requested from Apollo Gateway. Even if you run the GraphQL server standalone, it will reply back with the `ftv1` header in the response with the tracing information. The issue is happening because one of the type check is failing in the federated JVM library. Please refer the code [here](https://github.com/apollographql/federation-jvm/blob/b52bfd79bd4b20a5407f6f0fc22f3df2168576f8/graphql-java-support/src/main/java/com/apollographql/federation/graphqljava/tracing/FederatedTracingInstrumentation.java#L506) .
Here, the `context` is of type `DGSContext` and not of type `HTTPRequestHeaders`. This type check fails and the `shouldTrace` function returns `true` by default. This results in getting the trace for all the requests. In general, we request tracing only for a fraction of the requests to avoid the computation load.

## Expected behavior
We should be only getting the tracing information for the requests in which tracing header is passed from the Gateway.

## Actual behavior
We are getting tracing information for all the requests.

## Steps to reproduce
This can be easily reproduced in any GraphQL service implemented using the suggested tracing mechanism [here](https://github.com/Netflix/dgs-framework/issues/930).

**Comment by aabdelhafez** [comment]
Fixing that bug would be absolutely amazing!

**Comment by srinivasankavitha** [comment]
Thanks for reporting! We are not able to get to this anytime soon due to  internal priorities. We do welcome PRs, so feel free to contribute any fixes to the issue if this is blocking. We can add that to the upcoming release in that case. Thanks again!

**Comment by antholeole** [comment]
Any reason why this won't work?

```java
```

**Comment by hpuac** [comment]
Hey @antholeole, thx a lot! I can confirm that this workaround is also working for us!

**Comment by srinivasankavitha** [comment]
@antholeole - thanks so much for posting this. And you're right in that we would like to avoid adding logic specific to integrating in the apollo gateway as much as possible. It would be good to add this to our docs in any case for folks looking to integrate with Apollo's tracing. Here is our docs repo, if you're interested in contributing: 
https://github.com/Netflix/dgs

Else, I'll get to it in a bit.

**Comment by antholeole** [comment]
I’ll add this to the docs :) On Nov 14, 2022, at 5:51 PM, Kavitha Srinivasan ***@***.***> wrote:﻿
@antholeole - thanks so much for posting this. And you're right in that we would like to avoid adding logic specific to integrating in the apollo gateway as much as possible. It would be good to add this to our docs in any case for folks looking to integrate with Apollo's tracing. Here is our docs repo, if you're interested in contributing:
https://github.com/Netflix/dgs
Else, I'll get to it in a bit.
