### ISSUE TITLE
Move default values to default properties file

### ISSUE THREAD

**Issue by onobc** [Netflix/dgs-framework#104]
We currently have a few configuration properties that are using SpEL property syntax with default values embedded in the SpEL. Rather than have the default spread about the codebase, lets create a `dgs.default.properties` for these values. An EnvironmentPostProcessor can load these up into a property source w/ least priority so that they are only used if not user-specified. 

Here are the current locations that need updating:
* [DgsRestSchemaJsonController.kt](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-webmvc/src/main/kotlin/com/netflix/graphql/dgs/mvc/DgsRestSchemaJsonController.kt#L36)
* [DgsRestController.kt](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-webmvc/src/main/kotlin/com/netflix/graphql/dgs/mvc/DgsRestController.kt#L67) (once https://github.com/Netflix/dgs-framework/pull/101 is merged)
* [GraphiQLConfigurer.kt](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-graphiql-autoconfigure/src/main/java/com/netflix/graphql/dgs/graphiql/autoconfiguration/GraphiQLConfigurer.kt#L40) (once https://github.com/Netflix/dgs-framework/pull/101 is merged)

### Gotchas
* We currently are specifying default values in our [additional-spring-configuration-metadata.json](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-webmvc-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L13). If we leave them in here then they data will be in 2 places and could get out of sync. If we remove them then IDE auto-completion will not show the default value
* Once we add `@ConfigurationProperties` we will need to resist the urge to use `@DefaultValue` in the config props as that will override the default properties. 

[Original motivation](https://github.com/Netflix/dgs-framework/pull/94#discussion_r584327790) from @berngp

**Comment by berngp** [comment]
Maybe is just better to have them in the `ConfigurationProperties` until proven otherwise.

**Comment by bono007** [comment]
For me, having the defaults in the metadata files and the `@ConfigurationProperties` is fine as
1. that feeds well into IDEs and
2. we can create a doc that holds "all the properties" (similar to what [Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties) does) and that can server as the "single place to view the defaults". 

The one hole in this approach is the few places (the path properties) where we have the default in the SpEL. 

@berngp are you suggesting we should leave that as is for now (with their defaults also in the metadata files) or just do the EPP for this properties?

**Comment by berngp** [comment]
Keep the `@ConfigurationProperties` and the couple of path properties. We can add the EPP latter.

PS.
For completeness this is how a [EPP] could look like.
[EPP]:https://gist.github.com/berngp/a4900c67b3976faece831bbe2c61589b

**Comment by bono007** [comment]
> Keep the `@ConfigurationProperties` and the couple of path properties. We can add the EPP latter.

👍🏻 

> PS.
> For completeness this is how a [EPP] could look like.
> [EPP]: https://gist.github.com/berngp/a4900c67b3976faece831bbe2c61589b

Ahh yeh, I am intimately familiar w/ EPPs and ACIs as we leverage them heavily in our applications as well. I do like what you did w/ the defaults driven by the profiles - nice touch!

**Comment by berngp** [comment]
I added the link for my own reference. My short term memory is questionable.

**Comment by paulbakker** [comment]
Closing as stale.
