### ISSUE TITLE
bug: `graphql-dgs-spring-boot-micrometer` Dataloader instrumentation does not work with `DgsDataLoaderRegistryConsumer` loaders

### ISSUE THREAD

**Issue by Steven-Ireland** [Netflix/dgs-framework#1067]
## Expected behavior

Instrumented Dataloaders implementing `DgsDataLoaderRegistryConsumer` in order to get a `DataLoaderRegistry` should have their `setDataLoaderRegistry` method called prior to execution.

## Actual behavior

`setDataLoaderRegistry` is never invoked on instrumented dataloaders. 

## Steps to reproduce

1. Create a dataloader that implements `DgsDataLoaderRegistryConsumer` and `setDataLoaderRegistry`.
```java
public class SomeDataLoader
    implements MappedBatchLoaderWithContext<String, ...>, DgsDataLoaderRegistryConsumer {
  // ...
  @Override
  public void setDataLoaderRegistry(DataLoaderRegistry dataLoaderRegistry) {
    this.dataLoaderRegistry = dataLoaderRegistry;
  }
}
```
2. Add in the instrumentation package into the pom.xml (I tested on 4.9.17, but after reading a bit of the code it appears to be an issue with future versions as well)
```xml
        <dependency>
            <groupId>com.netflix.graphql.dgs</groupId>
            <artifactId>graphql-dgs-spring-boot-micrometer</artifactId>
        </dependency>
```
3. Drop a breakpoint into the dataloader's load method (or otherwise add some application logic that requires the registry) and observe that `setDataLoaderRegistry` was never called.

## Mitigation

If you turn off DataLoader instrumentation with `dgs-graphql.data-loader-instrumentation.enabled=false` the data loader registry is set on the registry consumer as expected -- but you do lose out on dataloader metrics entirely

**Comment by berngp** [comment]
Great catch @Steven-Ireland, problem is that we are wrapping the _dataloader_ with a ByteBuddy Proxy before we check if the reference implements `DgsDataLoaderRegistryConsumer`. Implemented a quick fix via PR #1068.

**Comment by berngp** [comment]
Interestingly enough I just found one _internal_ application that leverages the `DgsDataLoaderRegistryConsumer`. Could you help us understand your use case? i.e. how are you using the `dataLoaderRegistry` within the _data loader_.

**Comment by Steven-Ireland** [comment]
We're using it to grab other data loaders from a main data loader, and manage their lifecycle (load, dispatch) manually. It helps keep our application logic centered in the dataloaders for use in both domain object resolution and adjacent/dependent object resolution (for a made up example, a product dataloader could load reviews by grabbing a handle to the reviews data loader). 

We didn't really _have_ to use DGS' data loader registry to wire in the other loaders/application logic classes, but it fit our use case well enough for us to use it for now. In an ideal world we could drop the manual dispatch too, but without JS's event loop style promise resolution we still need to manually dispatch within our main dataloader. 

For now this fix lets us continue on regardless -- thanks a ton for the quick fix!
