### ISSUE TITLE
feature: Support Flow as Subscription return type

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#1076]
Currently, the subscription only supports ReactiveStream `Pulisher` as return type, if possible to add Kotlin `Flow` support, it make my codes look more consistent when I am using Kotlin Coroutines.

```kotlin
val flow = MutableSharedFlow<Event>()

fun emitEvent() {
   flow.emit(event)
   ...
}

fun eventAdded()=flow //the subscription function.
```

Internally Dgs can bridge it to a `Publisher` as required by graphql-java .

**Comment by berngp** [comment]
I think that is a good idea, thanks @hantsy for the suggestion.

**Comment by kilink** [comment]
Support for flow was added in c48492a.

**Comment by hantsy** [comment]
@kilink It seems the commit provides `Flow` as return type of Data Fetching, how about Flow support for `subscription`/event modeling?

**Comment by kilink** [comment]
You're right. I've added support for it in #1800
