### ISSUE TITLE
bug: Massive performance degradation since v4.10.4 if the graphql-dgs-spring-boot-micrometer module is active

### ISSUE THREAD

**Issue by hpuac** [Netflix/dgs-framework#1089]
Hey everyone, 

we recently updated DGS to v5.0.0 and noticed a massive increase in latencies. We did some testing and were able to target it down to the v4.10.4 release, so we downgraded to v4.10.3 to fix these latency issues in production.
After further investigation we figured out that the increased latencies are caused by the `graphql-dgs-spring-boot-micrometer`module. 
I created a simple [demo](https://github.com/hpuac/dgs-4-10-4-performance-degradation-demo) and measured the latencies. 
In the following table I averaged the latencies from 3 requests.

| DGS                                          | v4.10.2 | v4.10.3 | v4.10.4 | v5.0.0 | v5.0.1 |
|----------------------------------------------|---------|---------|---------|--------|--------|
| Without `graphql-dgs-spring-boot-micrometer` | 101ms   | 111ms   | 104ms   | 102ms  | 106ms  |
| With `graphql-dgs-spring-boot-micrometer`    | 145ms   | 147ms   | 842ms   | 867ms  | 864ms  |

It's clearly visible that there is a huge latency increase with `graphql-dgs-spring-boot-micrometer` enabled when updating from v4.10.3 to v4.10.4.
This shows best if the request contains many input arguments, so I'm sending 3000 numbers in my [test request file](https://github.com/hpuac/dgs-4-10-4-performance-degradation-demo/blob/main/request.sh#L13). 

## Expected behavior

With a release the latencies should not increase significantly.

## Actual behavior

With the update to v4.10.4 and later the latencies increase a lot if the `graphql-dgs-spring-boot-micrometer`module is active.

## Steps to reproduce

I created a repository with a minimal Sping + DGS setup to reproduce that issue:
https://github.com/hpuac/dgs-4-10-4-performance-degradation-demo

**Comment by aabdelhafez** [comment]
This is _exactly_ the problem we're having as well! Occurred right after upgrading from `v4.10.3` to `v4.10.4`.

**Comment by srinivasankavitha** [comment]
Thanks for reporting the issue. We will look into it and post an update.

**Comment by berngp** [comment]
Thanks for reporting, and special thanks for pinpointing the version that introduced the issue!

**Comment by hpuac** [comment]
Thank you a lot @berngp, I can confirm that the issue is fixed within v5.0.2! 🥳

**Comment by berngp** [comment]
On the contrary, thank you for reporting it @hpuac!
