### ISSUE TITLE
bug: org.springframework.core.KotlinDetector is not generated correctly in versions 4.10-5.0.1

### ISSUE THREAD

**Issue by ZMobile** [Netflix/dgs-framework#1091]
## Expected behavior

spring-core-5.2.12.RELEASE.jar generates a version of org.springframework.core.KotlinDetector that contains all necessary methods, namely boolean org.springframework.core.KotlinDetector.isSuspendingFunction(java.lang.reflect.Method).

## Actual behavior

The application fails, throwing this error:

`***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.netflix.graphql.dgs.internal.DataFetcherInvoker.<init>(DataFetcherInvoker.kt:39)

The following method did not exist:

    'boolean org.springframework.core.KotlinDetector.isSuspendingFunction(java.lang.reflect.Method)'

The method's class, org.springframework.core.KotlinDetector, is available from the following locations:

    jar:file:/Users/zantehays/.m2/repository/org/springframework/spring-core/5.2.12.RELEASE/spring-core-5.2.12.RELEASE.jar!/org/springframework/core/KotlinDetector.class

The class hierarchy was loaded from the following locations:

    org.springframework.core.KotlinDetector: file:/Users/zantehays/.m2/repository/org/springframework/spring-core/5.2.12.RELEASE/spring-core-5.2.12.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.core.KotlinDetector

`

## Steps to reproduce

It seems this issue is currently unavoidable and out of my control. I'll have to deactivate Netflix DGS at this time in order to avoid it. My current DGS GraphQL application used to function perfectly well prior to this issue. Granted it's been a while since I attempted to boot it up.

I suspect this might be a similar bug:
https://github.com/Netflix/dgs-framework/issues/1082

**Comment by berngp** [comment]
Our latest 4.x and 5.x releases use Spring 5.3 and Spring Boot 2.6, looks like you are using Spring Boot 2.5 or an older version.

**Comment by ZMobile** [comment]
An outdated Spring Boot Parent dependency does appear to be the culprit. Much appreciated.
