### ISSUE TITLE
bug: Exceptions thrown from dataFetchers are being thrown as `java.lang.reflect.UndeclaredThrowableException`.

### ISSUE THREAD

**Issue by maory** [Netflix/dgs-framework#1098]
## Expected behavior
`DataFetcherExceptionHandler#onException`handlerParameters Will contain the thrown exception.

## Actual behavior
`DataFetcherExceptionHandler#onException`handlerParameters contains `java.lang.reflect.UndeclaredThrowableException`, it's cause is the right exception. 

## Steps to reproduce
1. Create a simple query.
2. Create a test class for it
3. mocked class will throw a custom Exception (inherited from Exception)
4. set a breakPoint `DataFetcherExceptionHandler#onException`, see that the exception is `java.lang.reflect.UndeclaredThrowableException`

Note:
DataFetcher does throw the right exception and declares about it.

**Comment by berngp** [comment]
Hi @maory, we will need a minimal test to reproduce the issue. We use this feature extensibly.

If you need an example, and a way to set some breakpoint, you can look at our
[MicrometerServletSmokeTest](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-boot-micrometer/src/test/kotlin/com/netflix/graphql/dgs/metrics/micrometer/MicrometerServletSmokeTest.kt#L951).

**Comment by maory** [comment]
Hey @berngp, found out this issue https://github.com/Netflix/dgs-framework/issues/1098 which apperas to be the same one as I described, so tou can mark mine as duplicated.
