### ISSUE TITLE
Bad request on opening a WS subscription

### ISSUE THREAD

**Issue by Oted** [Netflix/dgs-framework#110]
Hello, so we've started experimenting with DGS and Subscriptions and ran into some issues which we can't directly see the reason for. A few bits from the code (should be reproducible):

```
type Subscription {
    livePlayers: Player
}

type Player {
    id: String!
    x: Int!
    y: Int!
}
```

```
data class Player(
        val id: String,
        val x: Int = 0,
        val y: Int = 0
)

@DgsComponent
class PlayerDataFetcher(
) {
    @DgsData(field = "livePlayers", parentType = "Subscription")
    fun livePlayers(): Publisher<Player> {
        return Flux.interval(Duration.ofSeconds(0), Duration.ofSeconds(1)).map{ Player("1")};
    }
}
```

```
@SpringBootApplication
class KotlinGraphqlApplication

fun main(args: Array<String>) {
    runApplication<KotlinGraphqlApplication>(*args)
}

@Configuration
class LocalHostCorsConfig {
    @Bean
    fun corsFilter(): FilterRegistrationBean<*> {
        val source = UrlBasedCorsConfigurationSource()
        val config = CorsConfiguration()
        config.addAllowedOrigin("http://localhost:3000")
        config.addAllowedOrigin("https://localhost:8444")
        config.addAllowedHeader("Accept")
        config.addAllowedHeader("Content-Type")
        config.addAllowedHeader("X-Requested-With")
        config.addAllowedHeader("Authorization")
        config.addAllowedMethod("GET")
        config.addAllowedMethod("POST")
        config.addAllowedMethod("OPTIONS")
        source.registerCorsConfiguration("/**", config)
        return FilterRegistrationBean(CorsFilter(source))
    }
}
```

When running the example from a local playground we receive a 400:

![image](https://user-images.githubusercontent.com/2505359/109796043-f87d8600-7c17-11eb-8e12-2879513ae771.png)

Upon some investigation it seems that ``DgsRestController.kt`` returns early due to missing body:

![image](https://user-images.githubusercontent.com/2505359/109795296-0bdc2180-7c17-11eb-85c8-eda0add0f71e.png)

Does anyone have a clue what we might be wrong here? Could it be that the UPDGRADE call from the client (would not contain a body) is causing this?

**Comment by paulbakker** [comment]
Subscriptions listen on `/subscriptions`, _not_ on `/graphql`. The reason for this is that in for example Apollo Client HTTP/WS requests can be routed to a different path.

**Comment by paulbakker** [comment]
@Oted Closing this issue, assuming the issue the path. Please re-open if this isn't the case.
