### ISSUE TITLE
documentation: modifiers in sample method is duplicated in 'Operating Caching' 

### ISSUE THREAD

**Issue by eungfue** [Netflix/dgs-framework#1100]
## What are you missing in the docs

modifier in sample method is duplicated. ('Operating Caching' chapter: https://netflix.github.io/dgs/advanced/operation-caching/)

```java
@Configuration
public class MyDgsConfiguration {

    @Bean
    public public PreparsedDocumentEntry getDocument(ExecutionInput executionInput,
                                                     Function<ExecutionInput, PreparsedDocumentEntry> parseAndValidateFunction) {
        return new CachingPreparsedDocumentProvider();
    }
}
```
## Proposed text

```java
@Configuration
public class MyDgsConfiguration {

    @Bean
    public PreparsedDocumentEntry getDocument(ExecutionInput executionInput,
                                                     Function<ExecutionInput, PreparsedDocumentEntry> parseAndValidateFunction) {
        return new CachingPreparsedDocumentProvider();
    }
}
```

**Comment by berngp** [comment]
Thank you for reporting! If by any chance you feel inclined to fix this issue you can find the source code [here](https://github.com/Netflix/dgs), if not, please let us know. All said we are always looking forward for contributions that make our docs better.

PS. We should really have executable examples as part of the doc repo.

**Comment by berngp** [comment]
The exact file is here https://github.com/Netflix/dgs/blob/main/docs/advanced/operation-caching.md

**Comment by eungfue** [comment]
Ok. I'll fix it myself :)

**Comment by berngp** [comment]
Thanks for sending the pr @eungfue .
