### ISSUE TITLE
bug: Using `@DgsDirective` with Spring CGLIB proxies generates a `NullPointerException`

### ISSUE THREAD

**Issue by noemielb** [Netflix/dgs-framework#1110]
## Some Context
In our current setup, Spring uses CGLIB proxies to serve beans.

With CGLIB proxies, annotations are not preserved unless explicitly specified in annotation definitions. CGLIB creates proxies by generating subclasses of target classes. When calling `getAnnotation` [here](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DgsSchemaProvider.kt#L470), the subclass annotations are returned, not the target class ones. Then, a `NullPointerException` is thrown [here](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DgsSchemaProvider.kt#L473) because no annotation was found.

The fact that annotations are not preserved in CGLIB proxies is a known issue. See:
- https://stackoverflow.com/questions/1706751/retain-annotations-on-cglib-proxies
- https://stackoverflow.com/questions/8974475/method-annotations-null-when-proxying-via-cglib

In fact, many of the DGS annotation based tools are simply not working with CGLIB proxies (e.g. `@DgsDirective`, `@DgsScalar`, `@RuntimeWiring`). It seems to be because `DgsSchemaProvider` uses methods such as `getAnnotation` or `isAnnotation` and these look for annotations on the proxy subclasses only.

There seem to be two solutions to this problem:
1. Add `@Inherited` to DGS annotation class definitions so that annotations are automatically inherited to sub classes.
```
@Inherited
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Component
public @interface DgsDirective {
    String name() default "";
}
``` 
2. When looking for class annotations, use Spring `AnnotationUtils`. See [findAnnotation](https://docs.spring.io/spring-framework/docs/3.1.x/javadoc-api/org/springframework/core/annotation/AnnotationUtils.html#findAnnotation(java.lang.Class,%20java.lang.Class)) that looks for annotations on superclasses as well.

If either of these solutions seem acceptable, I can open a PR.

## Expected behavior
When Spring uses CGLIB proxies, using `@DgsDirective` should work.

## Actual behavior
When Spring uses CGLIB proxies, using `@DgsDirective` triggers a `NullPointerException` and prevents the application from starting.

## Steps to reproduce
You can force Spring to use CGLIB proxies by adding `@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)` to your class definition. Here's an example:
```
@DgsDirective
@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)
public class CustomDirective implements SchemaDirectiveWiring {
  @Override
  public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> env )
  {
  ...
  }
}
```
Declaring a similar directive should trigger a `NullPointerException`.

**Comment by berngp** [comment]
Thanks for reporting the bug @noemielb

**Comment by berngp** [comment]
I think the first option, using `@Inherited`, should be ok. In general I think we should also look at using the `AnnotationUtils` instead, but this will be a larger change. Please, feel free to open the PR. If you can as well add tests, that would be fantastic.
