### ISSUE TITLE
bug: CORS error when using SSE with webflux

### ISSUE THREAD

**Issue by esfomeado** [Netflix/dgs-framework#1139]
I created a sample project making the use of webflux and disabled CORS and it works for the `/graphql` endpoint but no for the `/subscriptions` one.

## Expected behavior
It should disabled CORS for all endpoints.

## Actual behavior
It does not disabled for `subscriptions`.

## Steps to reproduce

Clone: https://github.com/esfomeado/dgs-cors

Do a request with SSE or fetch:

```
subscription {
  liveCoinsPrice {
    name,
    price,
    time
  }
}
```

**Comment by srinivasankavitha** [comment]
Thanks for reporting!

**Comment by Ancient-Dragon** [comment]
I don't have this issue with my example: https://github.com/Ancient-Dragon/dgs-sse-subscriptions-backend-example

**Comment by ClaudenirFreitas** [comment]
Could you add more info about this incident please? 
I didn't find a way to reproduce it using [this repo](https://github.com/esfomeado/dgs-cors).
Thanks in advance.

**Comment by paulbakker** [comment]
Closing this as this is now handled by Spring GraphQL with the DGS/Spring GraphQL integration.
