### ISSUE TITLE
bug: @DgsCodeRegistry not applied if bean is wrapped by Spring proxy

### ISSUE THREAD

**Issue by GFriedrich** [Netflix/dgs-framework#1163]
## Expected behavior
A method annotated with `@DgsCodeRegistry` in a Spring bean that is wrapped by a Spring CGLIB proxy should be applied.

## Actual behavior
The method is ignored an no application of the `@DgsCodeRegistry` takes place

## Root Cause
This issue is the used way of iterating over the methods in the bean at https://github.com/Netflix/dgs-framework/blob/fe6ca59c04d074a4c3f5dffc2aeceb3e8aeaf4df/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DgsSchemaProvider.kt#L220
This is not supporting beans wrapped by a proxy which in turn makes the code to miss the annotation.
The code should use the same procedure as done in other places of the class like https://github.com/Netflix/dgs-framework/blob/fe6ca59c04d074a4c3f5dffc2aeceb3e8aeaf4df/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DgsSchemaProvider.kt#L390-L392

Additionally be aware that the same issue is likely also found at
* https://github.com/Netflix/dgs-framework/blob/fe6ca59c04d074a4c3f5dffc2aeceb3e8aeaf4df/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DgsSchemaProvider.kt#L130
* https://github.com/Netflix/dgs-framework/blob/fe6ca59c04d074a4c3f5dffc2aeceb3e8aeaf4df/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DgsSchemaProvider.kt#L201
* https://github.com/Netflix/dgs-framework/blob/fe6ca59c04d074a4c3f5dffc2aeceb3e8aeaf4df/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DgsSchemaProvider.kt#L236
* https://github.com/Netflix/dgs-framework/blob/fe6ca59c04d074a4c3f5dffc2aeceb3e8aeaf4df/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DgsSchemaProvider.kt#L413

**Comment by srinivasankavitha** [comment]
Thanks for reporting this issue. Will investigate. If you are able to could
you also share an example to reproduce? Thanks!
