### ISSUE TITLE
feature: Filter produced errors before sending response

### ISSUE THREAD

**Issue by stengvac** [Netflix/dgs-framework#1166]
Hello,

## Describe the Feature Request
Add possibility to filter out some GQL errors before sending them in response. Right now when processing GQL request and lets say validation exception is produced, handled and corresponding error is created in `DataFetcherExceptionHandler` implementation `graph-java` can add another error like `NonNullableFieldWasNullError`. I would like to filter those out. 

## Describe Preferred Solution
Possibility to register error filter something like

```
interface DgsErrorFilter {
    fun filter(errors: List<GraphQLError>): List<GraphQLError> = errors
}
``` 
in case of mvc this ca be used in `DgsRestController` before result serialization.

**Comment by srinivasankavitha** [comment]
This is already supported. You can add a custom exception handler to filter out what you want for such cases: https://netflix.github.io/dgs/error-handling/#mapping-custom-exceptions

**Comment by stengvac** [comment]
Hello,

thanks for answer, but I think I did not provide enough data as it seems. because this is not what I meant. 

I did some more digging and found out, that I get one more error in response in some cases. Got
```
{
	"errors": [
		{
			"message": "Validation message",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			],
			"extensions": {
				"classification": "ValidationError"
			}
		},
		{
			"message": "The field at path '/...' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is '[Entity!]' within parent type 'Query'",
			"path": [
				"..."
			],
			"extensions": {
				"classification": "NullValueInNonNullableField"
			}
		}
	],
	"data": null
}
````

I wanted to fitler out `NullValueInNonNullableField` but seems this error is produced bcs when I put into errors only `ValidationError` then `NullValueInNonNullableField` is also present. Seems `ValidationError` does not add path in error and it makes problem + it I did probably miss used it.
