### ISSUE TITLE
bug: scalars automatically registered by `graphql-dgs-extended-scalars` are not registered in test environment

### ISSUE THREAD

**Issue by nallwhy** [Netflix/dgs-framework#1190]
## Expected behavior

Below are my schema and test code.

```grqphql
scalar Long

type Query {
  ping: Pong!
}

type Pong {
  long: Long!
}
```

```kotlin
@SpringBootTest(
    classes = [DgsAutoConfiguration::class, PingQuery::class]
)
class PingQueryTest {
    @Autowired
    lateinit var dgsQueryExecutor: DgsQueryExecutor

    @Test
    fun run() {
        val query = """
        query {
          ping {
            long
          }
        }
        """

        val result = dgsQueryExecutor.execute(query)
        ...
    }
}
```

That `ping` query works well in dev environment because `graphql-dgs-extended-scalars` automatically registers many scalars including `Long`.
So I expect the test to pass.

## Actual behavior

The test fails because `Long` scalar does not exist.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

There are problems with the GraphQL Schema:
	 * There is no scalar implementation for the named  'Long' scalar type
```

## Steps to reproduce

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by lbusch25** [comment]
@nallwhy Leaving a comment here since I am not certain if this is a bug or intended behavior due to the configuration being different beans. It would be nice if the `DgsAutoConfiguration.class` stood up extended scalars, but there is an easy workaround of adding the `DgsExtendedScalarsAutoConfiguration.class` to your `@SpringBootTest` annotation.

**Comment by srinivasankavitha** [comment]
Thanks for the response to this issue. This is intended behavior, since
extended scalars are an add-on feature and not available out of the box.
The intention is for the user to specify any classes explicitly for
@SpringBootTest.
