### ISSUE TITLE
feature: @DgsData should be @Repeatable

### ISSUE THREAD

**Issue by xenoterracide** [Netflix/dgs-framework#1193]
https://netflix.github.io/dgs/datafetching/#multiple-dgsdata-annotations-via-dgsdatalist

```java
@DgsData.List({
    @DgsData(parentType = "Query", field = "movies"),
    @DgsData(parentType = "Query", field = "shows")
})
```

couldn't `@DgsData` have [`@Repeatable`](https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html)?

**Comment by detinho** [comment]
It seems it already does have the @Repeatable.

Opened a PR https://github.com/Netflix/dgs/pull/121 to update the docs.
