### ISSUE TITLE
documentation:  import Try

### ISSUE THREAD

**Issue by xenoterracide** [Netflix/dgs-framework#1194]
## What are you missing in the docs

https://netflix.github.io/dgs/data-loaders/#implementing-a-data-loader-with-try

`Try` is missing an import, I assume it's coming from `Vavr`?

**Comment by ClaudenirFreitas** [comment]
There is [a documentation repository](https://github.com/Netflix/dgs) for this. 
[PR](https://github.com/Netflix/dgs/pull/112/files) has been created.
