### ISSUE TITLE
bug: Duplicated body of DgsWebSocketHandler.afterConnectionEstablished

### ISSUE THREAD

**Issue by nkonev** [Netflix/dgs-framework#1211]
In DgsWebSocketHandler method afterConnectionClosed() has the same body as in afterConnectionEstablished(). It looks as a copy-paste. Version is 5.2.1.
![Screenshot from 2022-09-01 14-24-07](https://user-images.githubusercontent.com/3160384/187892695-55db2d8e-e113-4760-ada4-0c8bdee59ed8.png)

**Comment by nkonev** [comment]
Also, I think, exception handling in DgsWebSocketHandler.afterConnectionClosed is missed - we need to wrap first invocation in try {} catch in order to let the second to be invoked.

**Comment by srinivasankavitha** [comment]
Thanks for catching that. Will fix in the next release.
