### ISSUE TITLE
bug: GraphiQL not working with custom endpoint path on 5.2.1

### ISSUE THREAD

**Issue by esfomeado** [Netflix/dgs-framework#1218]
## Steps to reproduce
When defining a custom endpoint path for graphql by setting the value on `dgs.graphql.path`, GraphiQL is unable to do a request because it adds `/graphiql` to the beginning of the path.

E.g.

`dgs.graphql.path` - `/api/graphql`

Request 5.1.1: `localhost:8080/api/graphql`

Request 5.2.1: localhost:8080/graphiql/api/graphql`

## Expected behavior
- GraphiQL should pick the custom path and not add `graphiql` to the beginning of the path.

## Actual behavior
GraphiQL is adding `graphiql` to the beginning of the path.

**Comment by srinivasankavitha** [comment]
Thanks for creating the issue.

**Comment by ClaudenirFreitas** [comment]
I tried to reproduce this issue but had no success ([repo](https://github.com/ClaudenirFreitas/dgs-issue-1218)).
Could you help me to reproduce it @esfomeado ?
Thanks in advance

**Comment by esfomeado** [comment]
@ClaudenirFreitas I've created a pull request on that repo with the required changes to reproduce the issue.

It seems that it only happens when webflux is used.
