### ISSUE TITLE
bug: GraphiQL does not work in latest Chrome browser Version 106.0.5249.91 (Official Build) (x86_64)

### ISSUE THREAD

**Issue by hzariv** [Netflix/dgs-framework#1260]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
GraphiQL UI should render in browser

## Actual behavior
You get a blank screen and in console you see the following errors:
react-dom.production.min.js:121 SyntaxError: Expected double-quoted property name in JSON at position 2298
    at JSON.parse (<anonymous>)
    at I.fetchSchema (GraphiQL.tsx:914:34)
    at I.componentDidMount (GraphiQL.tsx:395:12)
    at Ki (react-dom.production.min.js:179:501)
    at Ii (react-dom.production.min.js:179:278)
    at Ik (react-dom.production.min.js:178:329)
    at Sk (react-dom.production.min.js:197:312)
    at yb (react-dom.production.min.js:196:166)
    at Mi (react-dom.production.min.js:189:373)
    at db (react-dom.production.min.js:79:182)

## Steps to reproduce
Follow the instruction at https://netflix.github.io/dgs/getting-started/ and start up the server in localhost and in Chrome use URL http://localhost:8080/graphiql

Same issue and error is also shown in Safari Version 16.0 (17614.1.25.9.10, 17614)

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by hzariv** [comment]
[spring-boot-2-7-4.zip](https://github.com/Netflix/dgs-framework/files/9709846/spring-boot-2-7-4.zip)
Here is the project I used to test this.

**Comment by hzariv** [comment]
> Can't replicate the issue.
> 
> Works fine for me.

@esfomeado  did you use the attached [spring-boot-2-7-4.zip](https://github.com/Netflix/dgs-framework/files/9709846/spring-boot-2-7-4.zip) to recreate the issue as well as latest Chrome version on MacOS Monterey?

**Comment by esfomeado** [comment]
Yes I did.

**Comment by paulbakker** [comment]
closing as stale
