### ISSUE TITLE
bug: graphql-dgs-platform[-dependencies] Maven BOM downgrades dependencies like reactor-core, causing conflicts

### ISSUE THREAD

**Issue by seanf** [Netflix/dgs-framework#1269]
## Expected behavior
The Maven BOMs for DGS should cooperate with the Spring Boot Starter parent/BOMs and not modify/downgrade any versions it controls.  

Perhaps, to achieve this, the DGS BOMs (or a new BOM) needs to avoid specifying any version which is in the Spring BOMs.

## Actual behavior
If a DGS BOM is imported using Maven's `dependencyManagement`, it downgrades `io.projectreactor:reactor-core` to 3.4.10, even if Spring specifies a newer version. If using the `maven-enforcer-plugin` with [`requireUpperBoundDeps`](https://maven.apache.org/enforcer/enforcer-rules/requireUpperBoundDeps.html), the build will fail because this version of `reactor-core` is older than the one specified by `org.springframework:spring-webflux` (3.4.23). 

Without `maven-enforcer-plugin` this might manifest as a runtime exception, because `spring-webflux` is running against an older version of `reactor-core` than it was compiled/tested for. The same goes for any other Spring dependencies which are downgraded (held back) by the BOM in future.

## Steps to reproduce
Create a Maven project which extends `org.springframework.boot:spring-boot-starter-parent:2.7.4`. Add a `pom`/`import `dependency for `com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:5.2.1` in `dependencyManagement `and ordinary dependencies for `org.springframework.boot:spring-boot-starter` and `com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter`.

The attached [pom.xml](https://github.com/Netflix/dgs-framework/files/9764786/pom.xml.txt) shows the problem. Save it as `pom.xml` in its own directory.

Run `mvn enforcer:enforce` to see the conflict reported by `requireUpperBoundDeps`. Comment out the DGS dependencies to see the conflict go away.

Run `mvn help:effective-pom -Dverbose | grep -C2 reactor-core` to see the resolved version of `reactor-core` in both cases.

A similar problem can be seen with the other BOM `com.netflix.graphql.dgs:graphql-dgs-platform:5.2.1`, but I haven't created a sample for this.

## Considered workarounds
- Import `org.springframework.boot:spring-boot-starter-parent:2.7.4` as a `pom`/`import `dependency **above** the DGS BOM. This does give Spring priority over DGS, but it has a huge drawback: it seems to prevent the use of version properties to override dependency versions, which only seems to work when `org.springframework.boot:spring-boot-starter-parent` is inherited. (See https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html#appendix.dependency-versions.properties)
- Import `reactor-bom` as a `pom`/`import `dependency **above** the DGS BOM. This works, but it's another dependency version to maintain. And there may be other dependencies with the same problem in future, if they are specified by both Spring and DGS, especially if Spring upgrades the dependency but DGS doesn't.

```xml
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-bom</artifactId>
    <version>2020.0.24</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

**Comment by paulbakker** [comment]
Closing as stale
