### ISSUE TITLE
bug: "extensions" exposed in valid graphQL request 

### ISSUE THREAD

**Issue by antholeole** [Netflix/dgs-framework#1278]
## Steps to reproduce

Run the default DGS app with the following query:

```graphql
query {
  hello
}
```

or a mutation:

```graphql
mutation {
  addRating(input: {
    title: "Dahmer",
    stars: 1 # 2 scary 4 me
  }) {
    avgStars
  }
}
```

## Expected behavior

the server should respond with:

```json
{
  "data": {
    "hello": "hello, Stranger!"
  }
}
```

or 

```json
{
  "data": {
    "addRating": {
      "avgStars": 1
    }
  }
}
```

## Actual behavior

the server responds with:

```json
{
  "data": {
    "hello": "hello, Stranger!"
  },
  "extensions": {}
}
```

or:

```json
{
  "data": {
    "addRating": {
      "avgStars": 1
    }
  },
  "extensions": {}
}
```

I ran a `git bisect` and narrowed it down to commit `3cab92c3172128b37c277e89d491df3fe108bc12`. I can try to fix it after I'm done with `refactor-metrics`, unless someone beats me to it.

I didn't test for subscriptions but it's probably happening there too.

**Comment by antholeole** [comment]
Actually looking back at this, this is not really a bug - it's leftover [from DGS_RESPONSE_HEADERS_KEY](https://github.com/Netflix/dgs-framework/commit/3cab92c3172128b37c277e89d491df3fe108bc12#diff-13e2b14fd77f54bc584e10e2f751a23820d20efc08b34a0d4e2abe08aee01154R246) getting removed from extensions.

I'll leave this open if you want me to fix it during my next PR, otherwise I'll close. Test case is easy, just add this to the test added during that PR:

```kotlin
        ...
        assertThat(result.headers["myHeader"]).contains("hello")

        assertThat(result.body).isInstanceOfSatisfying(ByteArray::class.java) { body ->
            val mapper = jacksonObjectMapper()
            val (_, _, extensions) = mapper.readValue(body, GraphQLResponse::class.java)
            assertThat(extensions).isNull()
        }
```

**Comment by paulbakker** [comment]
Yeah it’s an unexpected side effect of my change. Would be good to fix for
sure.
