### ISSUE TITLE
DgsQueryExecutor & Security

### ISSUE THREAD

**Issue by fabienmifsud** [Netflix/dgs-framework#129]
Hi,

Is it possible to handle security in the DgsQueryExecutor ?

**Comment by paulbakker** [comment]
You can use Instrumentation for hooking into the execution flow: https://netflix.github.io/dgs/advanced/instrumentation/. Let me know if that helps.

**Comment by fabienmifsud** [comment]
Hi,
It is ok to get the incoming query parameter and put my logic here but in which part of the Context should I put my http header ?

**Comment by paulbakker** [comment]
@fabienmifsud we published a new datafetching guide, which covers headers: https://netflix.github.io/dgs/datafetching/. Closing this issue because there isn't anything actionable left, for now, feel free to re-open or create new issues if concrete things come up.

**Comment by fabienmifsud** [comment]
Hi @paulbakker , thank you for your support, I did make it work. Here is what I've done if that can help : 

I've annotated my Fetcher like this : 
```java
 @DgsData(parentType = "Query", field = "products")
    @RolesAllowed({"ADMIN", "USER"})
    public Iterable<Product> getAll() {
        return this.productRepository.findAll();
    }
```
And I want to unit test this method whitout inactivate the security. With your help, I did add in my test package an interceptor : 
```
  @Override
    public InstrumentationContext<ExecutionResult> beginExecution(InstrumentationExecutionParameters parameters) {

        if(parameters.getExecutionInput().getQuery().startsWith("mutation")) {
            // I want to add here a logged adminUser

            UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken("adminUser", "adminUser",
                    Arrays.asList(new SimpleGrantedAuthority("ROLE_ADMIN")));

            SecurityContextHolder.getContext().setAuthentication(token);
        } else {
            // I want to add here a logged standardUser
            UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken("standardUser", "standardUser",
                    Arrays.asList(new SimpleGrantedAuthority("ROLE_USER")));
            SecurityContextHolder.getContext().setAuthentication(token);
        }

        return super.beginExecution(parameters);
    }
```
And It works. Thank you for your help !

**Comment by sondr3** [comment]
I just hit this too in an application we're developing where we have three different kinds of roles and I want to be able to test the GraphQL queries/mutations with different roles, preferably in the same test class. With the solution from @fabienmifsud I can only globally override the auth context, but it'd be really nice if you could do so on a test-by-test/class-by-class basis. I can't figure out a good way of doing this that doesn't involve checking the name of the query/mutation and changing the user based on that... which feels very brittle.
