### ISSUE TITLE
bug: Maven - Spring Boot Plugin - Since Version 5.4.0 doesnt start anymore

### ISSUE THREAD

**Issue by juferdinand** [Netflix/dgs-framework#1291]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
Application should start without this Issue

## Actual behavior
![grafik](https://user-images.githubusercontent.com/70128315/197418006-f0741fc1-9ac8-4cd5-b1c8-bd210826f40d.png)

## Steps to reproduce
Create normal Spring Project add dgs-framework and all what is needed and start the application

## Steps to fix
Update Graphql-Java Version (I tried 19.2 and with this it starts without error)

Issue is since 5.4.0

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by berngp** [comment]
Looks like your build is being downgraded to grapql-java 18.3, and as you noticed, this won't work. Any chance you are using Spring' Dependency Management Plugin?

**Comment by berngp** [comment]
Please check https://github.com/Netflix/dgs-framework/issues/1281 you might me running into the same problem.

**Comment by juferdinand** [comment]
I just use the normal dependency tags of my pom. I can fix it by add graphql-java in dependency with higher version like 19.0. I thought it is an Problem by DGS-Framework that the Version of graphql-java is to low. 

I tried also invalidate my caches but after this the problem is still there. We can still work with it but I think the solution is not the best.

For others which have maybe the same Problem:
`<dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java</artifactId>
            <version>19.2</version>
        </dependency>
        <dependency>
            <groupId>com.netflix.graphql.dgs</groupId>
            <artifactId>graphql-dgs-spring-boot-starter</artifactId>
            <version>5.4.1</version>
        </dependency>
`

**Comment by srinivasankavitha** [comment]
So you are experiencing the issue without using the spring boot gradle plugin?

**Comment by berngp** [comment]
+1 to what @srinivasankavitha mentioned. Also @juferdinand, if you could share an example of your pom.xml it will help us understand better your problem.

**Comment by juferdinand** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.5</version>
        <relativePath/> 
    </parent>
    <groupId>org.pocketretail.cross</groupId>
    <artifactId>TicketSystem</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>TicketSystem</name>
    <description>TicketSystem</description>
    <properties>
        <java.version>18</java.version>
        <kotlin.version>1.7.20</kotlin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.netflix.graphql.dgs</groupId>
                <artifactId>graphql-dgs-platform-dependencies</artifactId>
                
                <version>5.4.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.amqp</groupId>
            <artifactId>spring-rabbit-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
            <version>4.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.netflix.graphql.dgs</groupId>
            <artifactId>graphql-dgs-subscriptions-sse-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.netflix.graphql.dgs</groupId>
            <artifactId>graphql-dgs-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.netflix.graphql.dgs</groupId>
            <artifactId>graphql-dgs-subscriptions-websockets-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-joda</artifactId>
        </dependency>
    </dependencies>


    <build>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <configuration>
                    <args>
                        <arg>-Xjsr305=strict</arg>
                    </args>
                    <compilerPlugins>
                        <plugin>spring</plugin>
                        <plugin>jpa</plugin>
                        <plugin>lombok</plugin>
                    </compilerPlugins>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-noarg</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-lombok</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>1.18.24</version>
                        <scope>runtime</scope>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

</project>


This is my pom right now, i added now the bom. But still without the graphql-java dependency it still throws the same failure

**Comment by languitar** [comment]
Facing the  same issue with a Maven project. When executing `mvn help:effective-pom -Dverbose=true` one can see that the graphql-java version is still obtained effectively from the spring-boot-dependecies package:

```
      <dependency>
        <groupId>com.graphql-java</groupId>  <!-- org.springframework.boot:spring-boot-dependencies:2.7.5, line 831 -->
        <artifactId>graphql-java</artifactId>  <!-- org.springframework.boot:spring-boot-dependencies:2.7.5, line 832 -->
        <version>18.3</version>  <!-- org.springframework.boot:spring-boot-dependencies:2.7.5, line 833 -->
      </dependency>
```

**Comment by noorul** [comment]
Facing the same issue in latest version 5.4.3. I am using maven

**Comment by MessiasLima** [comment]
These are my dependencies

![image](https://user-images.githubusercontent.com/10220064/201359349-4341c857-cb9b-4e52-ab4a-3ad567a49394.png)

I'm having the same problem

**Comment by noorul** [comment]
> Please check #1281 you might me running into the same problem.

@berngp This is still a problem with Maven. Can we remove the documenation label?

**Comment by berngp** [comment]
@noorul for Maven I suggest to open a different ticket. Most likley the
(Maven Spring Boot plugin)[https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/] is forcing the version to 18, instead of what DGS recommends which is 19. I don't know enough about the plugin to suggest how it can consider the DGS BOM.

**Comment by noorul** [comment]
@berngp I see that this issue title updated to reflect this.

**Comment by paulbakker** [comment]
Closing as stale
