### ISSUE TITLE
bug: No Responsebody if using Subscription

### ISSUE THREAD

**Issue by juferdinand** [Netflix/dgs-framework#1292]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

Get Response by API

## Actual behavior

I get no Response

## Steps to reproduce

my subscription in code

    @DgsSubscription(field = "subscribeTicketInformation")
    fun subscribeTicketInformation(): Publisher<Response> {
        return Flux.interval(Duration.ofSeconds(1)).map { t: Long ->
            Response(Http(200, "hello"))
        }
    }

schema

type Subscription{
    subscribeTicketInformation: Response
}

Request is loading but not getting any response which I can read
![grafik](https://user-images.githubusercontent.com/70128315/197544524-2c21c572-83f2-4e00-9c54-1fc48bffe488.png)

I use Postman newest version for sending the request and API doesnt send any error so idk why I get no response

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by juferdinand** [comment]
Same Issue with https://github.com/Ancient-Dragon/dgs-sse-subscriptions-backend-example

**Comment by juferdinand** [comment]
Hello again, exists any update or is this problem maybe just an problem of Applications like Postman?

thx & greetings

**Comment by paulbakker** [comment]
Looking at the provided code, I think the issue was to return an object that represents a HTTP response. Instead, the data sent back from a subscription is just data.
Closing this because it's not actionable.
