### ISSUE TITLE
documentation: Batch Loaders & supplyAsync

### ISSUE THREAD

**Issue by Steven-Ireland** [Netflix/dgs-framework#1295]
## What are you missing in the docs
`supplyAsync` is the recommended way to defer async logic in batch loaders in the docs, but can result in problems with IO bound workloads under heavy traffic. It's a great default, but the docs should address some of the shortcomings around fixed-size thread pools along with recommending alternatives when productionizing your application.

I'm totally happy to adjust either the included docs PR below as needed, otherwise feel free to pull from it and tweak it as desired! Let me know what works best 👍 

## Proposed text

I've created a PR started on the docs repo here, included below for easy reading: https://github.com/Netflix/dgs/pull/117

---

## Thread Pool Optimization

Using `supplyAsync()` without a second argument will cause the main work of a data loader to run on a [common thread pool](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html#commonPool--) 
shared with most other async operations in your application. If that data loader is responsible for calling a slow service and/or subject to heavy load, the common thread pool could become fully saturated.
In the worst case, this could result in application "freezes" as each data loader in the application awaits a free thread from the fixed-size common pool. 

To account for this, IO-bound data loaders should instead maintain their own dedicated thread pool rather than use the common pool. When choosing a thread pool, it's recommended to review the options under the [Executors Javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html),
but a safe default for IO bound workloads is usually `Executors.newCachedThreadPool()`. As opposed to the fixed-size common thread pool, `Executors.newCachedThreadPool()` will create new threads on-demand if all previously-created threads are saturated, but still prefers thread re-use when possible.

```java
@Configuration
public class SlowDataLoaderConfiguration {
    @Bean(name = "SlowDataLoaderThreadPool")
    Executor slowDataLoaderExecutor() {
        return Executors.newCachedThreadPool();
    }
}
```

Individual Bean names combined with `@Qualifier` annotations will result in the proper executor being autowired to the corresponding data loader.

```java
@DgsDataLoader(name = "slow")
public class SlowDataLoader implements MappedBatchLoader<String, Snail> {

    @Autowired
    @Qualifier("SlowDataLoaderThreadPool")
    Executor dedicatedExecutor;
    
    @Autowired
    DirectorServiceClient directorServiceClient;

    @Override
    public CompletionStage<Map<String, Snail>> load(Set<String> keys) {
        // This slow operation will now run on a dedicated thread pool instead of the common pool
        return CompletableFuture.supplyAsync(() -> directorServiceClient.loadSlowData(keys), dedicatedExecutor);
    }
}
```

**Comment by berngp** [comment]
Thanks for the PR, the doc improvements look great. It might be worth mentioning the caveats with _executors_ when dealing with _Spring Security's_ context. Ref https://docs.spring.io/spring-security/reference/features/integrations/concurrency.html

**Comment by Steven-Ireland** [comment]
Sure thing! I'll add a note on the caveat now 👍

**Comment by Steven-Ireland** [comment]
Added this to the bottom of the section:

> Note that a custom executor will not carry Spring Security context automatically like the `@DefaultExecutor` would. 
> Further documentation on passing Spring Security context between threads can be found in the [Spring Security Concurrency docs](https://docs.spring.io/spring-security/reference/features/integrations/concurrency.html).

**Comment by srinivasankavitha** [comment]
This is excellent as we have had many folks asking about this. Thanks for contributing to our docs!

**Comment by berngp** [comment]
Closing since changes were merged https://github.com/Netflix/dgs/pull/117
