### ISSUE TITLE
documentation: Link to Federation spec is a 404 

### ISSUE THREAD

**Issue by apriftis** [Netflix/dgs-framework#1315]
Hey team.

The link to Federation spec is not correct anymore
https://netflix.github.io/dgs/federation/

**Comment by ClaudenirFreitas** [comment]
There is another repository for documentation. [This one](https://github.com/Netflix/dgs).
I believe [both links](https://netflix.github.io/dgs/federation/) are correct, no?
Would you like to check, again?

**Comment by srinivasankavitha** [comment]
Yes, please check again. We have not linked to Federation 2.0 since we are not yet using it, if that is what you were expecting to see.
