### ISSUE TITLE
bug: DGS Framework not working with Spring Boot 3

### ISSUE THREAD

**Issue by osaetinevbuoma** [Netflix/dgs-framework#1340]
Hi guys.

With the new release of Spring Framework 6 and Spring Boot 3, I decided to upgrade my existing Spring Boot application. After going through the pain of changing the codebase to be compatible with Spring Boot 3, I realized that GQL queries using the DGS Framework stopped working with a 404. Reverting to Spring Boot 2.x and everything works as expected.

## Expected behavior
Should be able to hit the configured GraphQL endpoint.

## Actual behavior
You get similar error:
```
{"timestamp":"...","status":404,"error":"Not Found","message":"No message available","path":"/graphql (or your configured endpoint)"}
```

## Steps to reproduce

* Create new two projects, one a Spring Boot 3 and the other Spring Boot 2.x. 
* Add required DGS Framework dependencies.
* Create similar schema for both projects
* Start both projects (on different ports at the same time or one after the other).

Spring Boot 2.x project displays `c.n.g.d.w.a.GraphiQLConfigurer : Configuring GraphiQL to use GraphQL endpoint at '/graphql (or your configured endpoint)'` in terminal signifying OK setup of DGS Framework. Spring Boot 3 project does not display any info in terminal and returns a `404` if a query request is made to the configured endpoint. 

**NB**: Spring Boot 3 also displays the following warning:

```
o.s.c.annotation.AnnotationTypeMapping : Support for convention-based annotation attribute overrides is deprecated and will be removed in Spring Framework 6.1. Please annotate the following attributes in @com.netflix.graphql.dgs.DgsMutation with appropriate @AliasFor declarations: [field]
o.s.c.annotation.AnnotationTypeMapping : Support for convention-based annotation attribute overrides is deprecated and will be removed in Spring Framework 6.1. Please annotate the following attributes in @com.netflix.graphql.dgs.DgsQuery with appropriate @AliasFor declarations: [field]
```

**Comment by osaetinevbuoma** [comment]
To be fair, I wasn't sure if it was entirely a bug myself but good to know there's already a PR.

**Comment by GrantGochnauer** [comment]
+1 thanks!

**Comment by maximseshuk** [comment]
+1 thanks!

**Comment by raj-kindly** [comment]
Me too, not able to use dgs with spring boot 3.0

**Comment by srinivasankavitha** [comment]
We have a PR in progress that is being tested and in progress: https://github.com/Netflix/dgs-framework/pull/1230#issuecomment-1355019036

**Comment by raj-kindly** [comment]
> We have a PR in progress that is being tested and in progress: [#1230 (comment)](https://github.com/Netflix/dgs-framework/pull/1230#issuecomment-1355019036)

When is the release planned for that? Any tentative timeline?

**Comment by osaetinevbuoma** [comment]
Considering there are so many breaking changes between Spring Boot 2 & 3, I don't expect a release in the short term, and rightly so. I'd estimate Q1 2023 for a well tested, production ready version. And from Netflix's perspective, if the release does not work to the standard expected for their own applications, it's not worth releasing.

**Comment by n614cd** [comment]
@osaetinevbuoma 

The PR is well along already. From the perspective of DSG framework, the breaking changes are mostly along annotation and package changes. From looking at the PR, many of the other breaking changes (e.g. Spring Security OAuth had significant changes). 

Tim

**Comment by srinivasankavitha** [comment]
We are actively testing the changes. Given the holiday period the next couple weeks, we will resume this effort in early Jan. I expect to have a release ready for community consumption mid Jan or earlier, if possible.

**Comment by osaetinevbuoma** [comment]
Thanks @srinivasankavitha @n614cd I expected this to be the case, hence why I said Q1 estimate. Certainly no hurries and we'll look forward to the release, whenever it's ready. 👍🏼

**Comment by GrantGochnauer** [comment]
Thank you all for your work on this one! I will have to try again to get this branch working - perhaps I wait until the fork is merged into the netflix account branch

**Comment by srinivasankavitha** [comment]
I just merged the PR into a new branch named `spring-boot-3-candidate`. You
should be able to use that branch for testing with your project in the
meantime.

**Comment by raj-kindly** [comment]
Hi Guys,

Do we have some timeline for this release? We have migrated to spring boot
3 and all of that merge is pending just because of this.

**Comment by osaetinevbuoma** [comment]
Anytime now @raj-kindly. Soon, I believe but in the you can go ahead and test the `spring-boot-3-candidate` branch on your project.

**Comment by srinivasankavitha** [comment]
Yes, please test with the `spring-boot-3-candidate` branch in the meantime. We are in the process of testing and expect to do a release mid-Jan.

**Comment by raj-kindly** [comment]
Guys an update on the release timeline?

**Comment by srinivasankavitha** [comment]
We will post an update here, once the release is available in the next day
or so: https://netflix.github.io/dgs/announcements/

**Comment by osaetinevbuoma** [comment]
The PR has been merged to `master` so any day now @raj-kindly.

**Comment by osaetinevbuoma** [comment]
Closing this issue as DGS 6 is now live. https://netflix.github.io/dgs/announcements/.
