### ISSUE TITLE
bug: UploadScalar is not working when i work generateCodegen

### ISSUE THREAD

**Issue by Zoe0631** [Netflix/dgs-framework#1345]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

In my opinion, the issue is not a common situation.

- I wrote the code as below

![image](https://user-images.githubusercontent.com/98700133/204754372-1115bff4-613d-43db-ab43-282b6ede925e.png)

## Expected behavior
According to the guide, if I only declare 'scalar Upload', isn't Upload created?

## Actual behavior

- Below is the class created when using codegen. Upload scalar is not created

![image](https://user-images.githubusercontent.com/98700133/204755016-6a35c78d-c348-44b5-9a5f-52f4319d3aeb.png)

- dependency(build.gradle.kts)

  implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:5.1.1"))
  implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter")

- Upload Scalar built into the dgs framework
![image](https://user-images.githubusercontent.com/98700133/204756111-9d58924c-b4d2-4805-a979-659c8db3e067.png)

what should i do for using Upload scalar that is for access multipart/ form- data?

**Comment by Ancient-Dragon** [comment]
Prefacing this with I'm not sure if this is the "correct" way to do this, but we use the something like the following code which works for getting multipart files:

```java
    @DgsMutation
    public List<Response> upload(@InputArgument final List<Part> parts, final DataFetchingEnvironment env) {
        final List<MultipartFile> attachmentParts = env.getArgument("files");
        final List<Response> responses = new ArrayList<>();
        for (int x = 0; x < attachmentParts.size(); x++) {
            final MultipartFile part = attachmentParts.get(x);
            Path path = null;
            try {
                final String tmpdir = System.getProperty(TEMP_FILE_PATH);
                final String name = UUID.randomUUID().toString();
                path = Paths.get(tmpdir, FilenameUtils.getName(TEMP_FILE_PREFIX + name + TEMP_FILE_EXTENSION));
                Files.copy(inputStream, path);
                final Response response = facade.uploadFile(path.toFile(), part.getOriginalFilename());
                responses.add(response);
            } catch (final IOException e) {
              log.error("Cannot process file", e);
            } finally {
              try {
                if (path != null) {
                    Files.delete(path);
                }
              } catch (final IOException e) {
                  log.error("Unable to delete the file for the following reason: {}", e.getMessage(), e);
              }
            }
        }
        return responses;
    }
```

I'm not sure if parts parameter is actually needed to be honest. I've cut some of the code so it's generic but hopefully it should work for you (can also probably clean it up).

**Comment by srinivasankavitha** [comment]
You can extract the argument as a MultipartFile as shown here:
```

@DgsData(parentType = DgsConstants.MUTATION.TYPE_NAME, field =
"uploadScriptWithMultipartPOST")
public boolean uploadScript(DataFetchingEnvironment dfe) throws IOException {
    // NOTE: Cannot use @InputArgument  or Object Mapper to convert to
class, because MultipartFile cannot be
    // deserialized
    MultipartFile file = dfe.getArgument("input");
    String content = new String(file.getBytes());
    return ! content.isEmpty();
}

```
https://netflix.github.io/dgs/advanced/file-uploads/#multipart-file-upload

**Comment by paulbakker** [comment]
For the original codegen related issue, for existing custom types you need to configure a type mapping: https://netflix.github.io/dgs/generating-code-from-schema/#mapping-existing-types

For file upload support itself, this is now implemented through the Spring GraphQL fileupload module: https://netflix.github.io/dgs/advanced/file-uploads/
