### ISSUE TITLE
bug: DefaultDataFetcherExceptionHandler should not log an error on org.springframework.security.access.AccessDeniedException

### ISSUE THREAD

**Issue by EugenMayer** [Netflix/dgs-framework#1353]
Currently, every exception that happens in a graphql endpoint call is logged using the full stack trace - and it is logged as error due to

```
private fun doHandleException(handlerParameters: DataFetcherExceptionHandlerParameters): DataFetcherExceptionHandlerResult {
        val exception = handlerParameters.exception
        logger.error(
            "Exception while executing data fetcher for ${handlerParameters.path}: ${exception.message}",
            exception
        )
        val graphqlError = if (springSecurityAvailable && isSpringSecurityAccessException(exception)) {
            TypedGraphQLError.newPermissionDeniedBuilder()
                .message("%s: %s", exception::class.java.name, exception.message)
                .path(handlerParameters.path).build()
        } else if (exception is DgsEntityNotFoundException) {
            TypedGraphQLError.newNotFoundBuilder()
                .message("%s: %s", exception::class.java.name, exception.message)
                .path(handlerParameters.path).build()
        } else if (exception is DgsBadRequestException) {
            TypedGraphQLError.newBadRequestBuilder()
                .message("%s: %s", exception::class.java.name, exception.message)
                .path(handlerParameters.path).build()
        } else {
            TypedGraphQLError.newInternalErrorBuilder()
                .message("%s: %s", exception::class.java.name, exception.message)
                .path(handlerParameters.path).build()
        }
        return DataFetcherExceptionHandlerResult.newResult()
            .error(graphqlError)
            .build()
    }
```

I do not think this is how at least we should handle an `AccessDeniedException` exception. I can use this to flood the entire server logs with a fairly big stack trace without even being a legit user of the API. Spring security itself logs this below WARN and i think that is what should happen here too. Or just let us extend this "should i log it or not" decision without overriding the entire `DataFetcherExceptionHandlerResult` so we can implement our own logging filter here.

Flagged as bug since this has easy potential to flood the server logs. So the part with "do not log AccessDeniedException` as error is a bug, the one with "extend so we can filter the log severity" would be a FR of course (which i can open ,if this is something that can be discussed).

Just to be sure, https://netflix.github.io/dgs/error-handling/#mapping-custom-exceptions will not help with that, since `com.netflix.graphql.dgs.exceptions.DefaultDataFetcherExceptionHandler#doHandleException` is private. So basically we can either re-implement the entire GraphQL exception response or have the error logging being forced.

**Comment by EugenMayer** [comment]
For a temporary fix and demonstration of the implementation that i do not think should happen (since i re-implemented the AccessDenied the handling without actually wanting to)


```java
@Component
public class GlobalGraphQLExceptionHandler implements DataFetcherExceptionHandler
{
  @Override
  public CompletableFuture<DataFetcherExceptionHandlerResult> handleException(final DataFetcherExceptionHandlerParameters handlerParameters)
  {
    // We handle the access denied exception the same way as
    // com.netflix.graphql.dgs.exceptions.DefaultDataFetcherExceptionHandler.doHandleException
    // just suppressing the error log. See https://github.com/Netflix/dgs-framework/issues/1353
    if (handlerParameters.getException() instanceof AccessDeniedException) {
      var exception = handlerParameters.getException();
      var graphqlError = TypedGraphQLError.newPermissionDeniedBuilder()
        .message("%s: %s", exception.getClass(), exception.getMessage())
        .path(handlerParameters.getPath()).build();

      DataFetcherExceptionHandlerResult result = DataFetcherExceptionHandlerResult.newResult()
        .error(graphqlError)
        .build();

      return CompletableFuture.completedFuture(result);
    }

    return DataFetcherExceptionHandler.super.handleException(handlerParameters);
  }
}
```

This would suppress the error logging just for the `AccessDeniedException`, but on the downside, re-implemented the actual building of the graphql response (which is what i would like to improve with the potential FR)

**Comment by EugenMayer** [comment]
Any chance to get a response here about the current ideas/vision/opinions to this idea/issue? Thank you!

**Comment by srinivasankavitha** [comment]
You bring up a very valid point. That said, our internal tooling depends
heavily on log correlation and having some error log, especially for Access
denied exceptions great helps identify what went wrong here. So
unfortunately, I don't think we can suppress this log yet, but I will work
on finding out a path towards that.

In the meantime, the approach you tool with the custom exception handler is
probably the best way to tackle this for services wanting to suppress this
error.

I do agree with your proposal though, so will look into that.

**Comment by EugenMayer** [comment]
@srinivasankavitha i'am not really iam for you to change your internal defaults, even though, considering your motivation here, i would rather assume to stick to the more industry standard and use an option for you to have "log it all" as you wish. But of course, this is of the project owners choice what the defaults are.

I would love to see two things:
a) if the default stays for "log it all", offer a simple "log only critical" option as property to switch back to the more spring-boot logging behavior (so an easy opt out option)
b) Offer a better interface (less re-implementation when adding custom exception handling) as stated above

Of course, with b) on can simply implement hat a) would do and for us, b) is mandatory anyway. I still would say, you you agree, that a) might be what the broader audience would go for (IMHO).

Thank you for considering this!

**Comment by srinivasankavitha** [comment]
(a) is a great suggestion and an easy change for us to make. We will look
into adding that. Thanks for the discussion!

**Comment by kilink** [comment]
My two cents is that the DGS framework shouldn't be in the business of deciding how to map which exceptions to which log level. You have one opinion on what exceptions should map to what log level, but other users will have their own.

Instead, I think it's preferable to just make `DefaultDataFetcherExceptionHandler` extensible, by moving the logging to a protected method that can easily be overridden. graphql-java's own [SimpleDataFetcherExceptionHandler](https://github.com/graphql-java/graphql-java/blob/d275323dd2c49b5e71d9537d488f2ae7c0f24196/src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java#L45) does this as well.

**Comment by EugenMayer** [comment]
@kilink i would slightly disagree, DGS is of course in the business of deciding - it decides the defaults. This is fine and a good thing, defines the  character of the framework for starters and such. So i would not suggest dodging the though of 'are the defaults good enough for what we thing DGS should be seen as first'.

I questioned if the defaults are a good common choice but acknowledged that ultimately, they do not need to be, if it is easy to change (a)).

I of course agree with you on the side of extensibility and customization. You go for b), which we already do and yes, currently this re-implements way to many parts that can move without reason.

For us the extensibility you build in would not be enough, but it already helps really well with the logging decision part, so this one is covered for sure. So i would say, a good fit!
