### ISSUE TITLE
documentation: Scalars in DSG Client code sample is wrong

### ISSUE THREAD

**Issue by vap78** [Netflix/dgs-framework#1360]
## What are you missing in the docs

The following example in the documentation is wrong - it does not compile:

```
Map<Class<?>, Coercing<?, ?>> scalars = new HashMap<>();
scalars.put(java.time.LocalDateTime.class, new DateTimeScalar());

```

Used version:

com.netflix.graphql.dgs.codegen:graphql-dgs-codegen-shared-core:5.6.2

## Proposed text
What compiles for me is:

```
Map<Class<?>, Coercing<?, ?>> scalars = new HashMap<>();
scalars.put(java.time.LocalDateTime.class,  DateTimeScalar.INSTANCE.getCoercing());

```

**Comment by ClaudenirFreitas** [comment]
There is another repository for documentation.  [This one](https://github.com/Netflix/dgs).  
I suppose we can move this issue. 🤔

**Comment by brleinad** [comment]
I had the same problem and spent way too much time trying to figure this out. It would be great if this was on the docs.

@vap78 Were you using the [DateTimeScalar from the extended scalars](https://github.com/graphql-java/graphql-java-extended-scalars#datetime-scalars)? 
I could be wrong but I think the example in the docs works for custom scalars but it would be nice to have another example for the extended scalars. Somebody please correct me if I'm wrong. 

If this makes sense I can open a PR to update the docs.

**Comment by vap78** [comment]
Hi

sorry for the late reply.

These are the references I have in build.gradle:
`   api "com.netflix.graphql.dgs:graphql-dgs-client:5.5.0"
    api "com.netflix.graphql.dgs:graphql-dgs-extended-scalars"
    api 'com.netflix.graphql.dgs.codegen:graphql-dgs-codegen-shared-core:5.6.2'
`

So I guess - yes - I'm using the extended scalars library.

That's one other thing (maybe worth another ticket) - the client documentation does not say which libraries should be referenced in case one needs to use the client only. I had to do it by trial and error.

Best regards
Vasil
