### ISSUE TITLE
documentation: DGS dose not work with Spring 3.0.0

### ISSUE THREAD

**Issue by Marfien** [Netflix/dgs-framework#1373]
## What are you missing in the docs
A hint that you have to remove the usage of io.spring.dependency-management plugin (or a solve).

**Comment by ClaudenirFreitas** [comment]
There is another repository for documentation.  [This one](https://github.com/Netflix/dgs).  
I suppose we can move this issue. 🤔

**Comment by kilink** [comment]
I'm resolving this DGS does support Spring Boot 3.x now.
