### ISSUE TITLE
Loading by alternative keys

### ISSUE THREAD

**Issue by clamothe** [Netflix/dgs-framework#138]
Is there a way to use the 'Loading by alternative keys' DataLoader pattern in DGS?

https://github.com/graphql/dataloader#loading-by-alternative-keys

**Comment by paulbakker** [comment]
I'm not quite understanding what's written in the guide. Wouldn't this just be two different dataloaders?

**Comment by clamothe** [comment]
I've looked into this further. Yes, there would be two different loaders. One with `<K1, V>` and the other with `<K2, V>`. Whenever an entity is loaded by one of the loaders, it calls `prime` on the other dataloader.

Is there a way to get another dataloader from within a dataloader's `load` implementation?

**Comment by paulbakker** [comment]
Fixed by #443
