### ISSUE TITLE
Transitive Dependency Conflict with Federation >=2.1.1

### ISSUE THREAD

**Issue by samjcombs** [Netflix/dgs-framework#1393]
Is there a timetable for the upgrade of Federation jvm dependency to 2.1.1 or higher?  It is currently at 2.1.0 and fails a build pipeline in my app when i using a dependencyConvergence enforcer plugin.  I have temporarily disabled this.  I am including 2.2.0 in my project as well to support the latest version of federation spec.  

Is this on the roadmap to upgrade Federation to latest? 

Change needed:
https://github.com/apollographql/federation-jvm/releases/tag/v2.1.1

Latest: 
https://github.com/apollographql/federation-jvm/releases/tag/v2.2.0

**Comment by srinivasankavitha** [comment]
Yes, we plan on tackling this later in the quarter. I don't have a concrete
timeline yet as our planning process is underway.

**Comment by samjcombs** [comment]
Thanks, the specific bugfix I needed was here: https://github.com/apollographql/federation-jvm/pull/258

This pertains to when you define `schema` and `extend schema` in the same schema.  In my case I use custom directives on the schema definition, and i'm also using a schema extension to import apollo fed2 spec.   

This wont be an uncommon pattern in larger federated deployments IMO so the sooner DGS gets fed-jvm 2.1.1 the better. thanks for the quick reply!

**Comment by kilink** [comment]
DGS now depends on federation-graphql-java-support 3.0.0, so this should no longer be an issue.
