### ISSUE TITLE
bug: NoClassDefFound error when using 5.5.1

### ISSUE THREAD

**Issue by vap78** [Netflix/dgs-framework#1395]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

We have following dependency in our build.gradle:
    implementation platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latestRelease")
which resolves to version 5.5.1. 

Used JDK to run tests/runtime is OpenJDK 17.0.5 2022-10-18
Used Spring Boot version is 2.7.7

## Expected behavior
The application and tests should run fine.

## Actual behavior

The application start and tests fail with following exception:

> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.netflix.graphql.dgs.webmvc.autoconfigure.GraphiQLConfigurer': Resolution of declared constructors on bean Class [com.netflix.graphql.dgs.webmvc.autoconfigure.GraphiQLConfigurer] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@68699afc] failed; nested exception is java.lang.NoClassDefFoundError: jakarta/servlet/ServletContext
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:768) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:720) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.24.jar:5.3.24]
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.24.jar:5.3.24]
>         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.7.jar:2.7.7]
>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.7.jar:2.7.7]
>         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.7.jar:2.7.7]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.7.jar:2.7.7]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.7.jar:2.7.7]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.7.jar:2.7.7]
>         at nl.collectcar.api.reservation.ReservationApiApplication.main(ReservationApiApplication.java:15) ~[classes/:na]
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
>         at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[file:/:na]
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[file:/:na]
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[file:/:na]
>         at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) ~[file:/:na]
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.netflix.graphql.dgs.webmvc.autoconfigure.GraphiQLConfigurer': Resolution of declared constructors on bean Class [com.netflix.graphql.dgs.webmvc.autoconfigure.GraphiQLConfigurer] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@68699afc] failed; nested exception is java.lang.NoClassDefFoundError: jakarta/servlet/ServletContext
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:309) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1302) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1219) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1609) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1573) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1462) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1349) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.24.jar:5.3.24]
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:760) ~[spring-beans-5.3.24.jar:5.3.24]
>         ... 28 common frames omitted
> Caused by: java.lang.NoClassDefFoundError: jakarta/servlet/ServletContext
>         at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:na]
>         at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[na:na]
>         at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2555) ~[na:na]
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:304) ~[spring-beans-5.3.24.jar:5.3.24]
>         ... 43 common frames omitted
> Caused by: java.lang.ClassNotFoundException: jakarta.servlet.ServletContext
>         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[na:na]
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[na:na]
>         at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:135) ~[file:/:na]
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
>         ... 47 common frames omitted

## Steps to reproduce
 see above.

When downgrading to 5.5.0 things start working fine.

**Comment by IvanDanilau** [comment]
The same occurs for me:
spring boot - 2.7.4
jdk - coretto 17.0.5
platform version 6.0.0

**Comment by theawesomechin** [comment]
With no further changes to our application upgrading to 5.5.1 and 6.0.0. Yields the same issue for us.

Spring Boot: 3.0.0 and 2.7.7 
jdk - Corretto 19.0.1

**Comment by kevinh-autoserve1** [comment]
Same issue, release notes don't mention anything that would indicate a dependency would need changing here with 5.5.1. 

6.0 is another story.

This is the second time package dependencies have been broken by DGS updates, so obviously something is not working here  Netflix guys and gals.

**Comment by srinivasankavitha** [comment]
If you are using 5.5.0 and greater, our release notes indicate we have
switched to Spring Boot 2.7. project would require Spring Boot 2.7 to be
compatible.
If you are using 6.0.0 (latest release), you will need Spring Boot 3.0 and
JDK 17

Hope that helps.

**Comment by vap78** [comment]
We are using Spring Boot 2.7.7 and JDK 17.

There are no issues with 5.5.0. This error occurs with 5.5.1 only.

**Comment by kilink** [comment]
I believe the original issue is occurring because you are depending on `latest.release` of `graphql-dgs-platform-dependencies`, which will pull in a version that's incompatible with Spring Boot 2.7.x. You should pin the `graphql-dgs-platform-dependencies` BOM to 5.5.x to avoid that issue if you wish to remain on Spring Boot 2.7.

I cannot reproduce any of the issues with the example app either, even if I switch it to JDK17. Please re-open the issue if you are able to consistently reproduce it after confirming you are pinning the DGS BOM appropriately.
