### ISSUE TITLE
feature: update scalars to include CountryCode and Currency

### ISSUE THREAD

**Issue by setchy** [Netflix/dgs-framework#1405]
## Describe the Feature Request

[v20 of graphql-java-extended-scalars](https://github.com/graphql-java/graphql-java-extended-scalars/releases/tag/20.0) was released back in December and added support for two new scalars
* CountryCodeScalar
* CurrencyScalar

## Describe Preferred Solution

Update the [graphql-dgs-extended-scalars ](https://github.com/Netflix/dgs-framework/tree/master/graphql-dgs-extended-scalars) module to `graphql-java-extended-scalars:20.0` and associated [documentation](https://github.com/Netflix/dgs/blob/main/docs/configuration.md#dgs-extended-scalars-graphql-dgs-extended-scalars) 

To achieve it will likely trigger a bigger ask/need to update from `graphql-java:19.3` to `graphql-java:20.0`

Something else I was pondering if whether the `Locale` scalar continues to belong under `dgs.graphql.extensions.scalars.objects.enabled` or whether it should join a new grouping with `CountryCode` and `Currency`.

**Comment by setchy** [comment]
Dependant on https://github.com/Netflix/dgs-framework/issues/1467

**Comment by congotej** [comment]
Resolved by: https://github.com/Netflix/dgs-framework/pull/1547
