### ISSUE TITLE
line separator in serializedRequest by GraphQLClients.objectMapper.writeValueAsString

### ISSUE THREAD

**Issue by littlelouishu** [Netflix/dgs-framework#1407]
WebClientGraphQLClient.class
`@Suppress("BlockingMethodInNonBlockingContext") val serializedRequest = GraphQLClients.objectMapper.writeValueAsString(
            Request(
                query,
                variables,
                operationName
            )
        )`

I noticed some strange behavior (maybe strange, just because I can't get the result expected) I think in the the code above.

if the LF (\n) in json value, the result of serializedRequest is \n (I think it's because \\n is treated as 1 character).
if the escaped LF (\\\\n) in json value, the result of serializedRequest is \\\\\\\\n (It's a string has 3 characters \\ \\ n).

I expect result of serializedRequest is \\\\n in request body finally as an escaped LF(\\n), e.g. {description:"abc \\\n def"}

How can I do this? Can I customize the ObjectMapper above? 
Or, any way I can serialize a json node which has \n in it with triple-quotes? e.g. """block \\n string"""
Reference to the block string spec https://spec.graphql.org/June2018/#BlockStringCharacter
HELP!!!

**Comment by kilink** [comment]
We would need more details to understand if this is an issue with DGS or not, as it seems like this is more of a question regarding Jackson / JSON serialization. The `ObjectMapper` here is not customizable, but I am not sure why you would even need to customize it here. The JSON spec has its own rules for escaping things such as newline characters.

That said, I am able to round-trip a query with a triple-quote block, e.g. the example from the spec. Please re-open if you can provide more details or point to an actual issue in DGS itself.
