### ISSUE TITLE
feature: Ability to customize WebSocketGraphQLClient connection init message payload

### ISSUE THREAD

**Issue by gadams00** [Netflix/dgs-framework#1408]
Graphql-java-kickstart supports creating a graphql server with a custom authentication interceptor that can inspect the connection message payload for authentication tokens.  The DGS WebSocketGraphQLClient has the connection message defined in a companion object with null payload and no possibility to customize, making it incompatible with graphql-java-kickstart servers that use this feature. It would be helpful if it were possible to optionally customize the connect message payload.

**Comment by paulbakker** [comment]
Closing this issue because the transport layer for DGS is now handled by Spring GraphQL.
