### ISSUE TITLE
bug: Exception while fetching data: dataFetcher.get(environment) must not be null

### ISSUE THREAD

**Issue by biagioT** [Netflix/dgs-framework#1409]
- Spring Boot 2.7.8
- graphql-dgs-platform-dependencies: 5.5.1
- **graphql-dgs-extended-validation**
- jdk 17

I get errors if some fields of my result objects are null. Errors are present only if I use graphql-dgs-extended-validation dependency in my build.gradle (this dependency is needed to perform validations on the inputs)

## Expected behavior
Results without errors and with some null fields
```
{
	"data": {
		"examples": [{
			"code": "1234",
			"name": null,
			"field1": "hello!",
			"field2": "---"
		}]

	}
}
```

## Actual behavior
Error:
```
{
			"message": "Exception while fetching data (/examples[25]/name) : dataFetcher.get(environment) must not be null",
			"locations": [
				{
					"line": 7,
					"column": 3
				}
			],
			"path": [
				"examples",
				25,
				"name"
			],
			"extensions": {
				"classification": "DataFetchingException"
			}
		}
```

type Example:

```
type Example {
    code: String
    name: String
    field1: String
    field2: String
}
```

## Steps to reproduce
simple query

**Comment by kilink** [comment]
I tried to reproduce the issue, but am unable to. What validators are you using, and what does that configuration look like? I'll need more details, and ideally example code that triggers the issue if it's still a problem.
