### ISSUE TITLE
bug: Graphql endpoint not created when using Springboot 3.0.2 + Kotlin + Maven

### ISSUE THREAD

**Issue by arsereg** [Netflix/dgs-framework#1431]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

The Springboot application exposes an endpoint in [domain]/graphql after Springboot initialization

## Actual behavior

Springboot is not creating an endpoint in [domain]/graphql after Springboot initialization. No posible way to execute mutations or queries.

## Steps to reproduce

1- Create a Springboot 3.0 through spring.initializr or Intellij integration with Spring Initalizr
2- Add the spring-web dependency
3- Follow the steps for DGS Framework Getting Started
4- Add the DGS dependencies
5- Add the example Schema
6- Add the example datafetcher
7- Run the application

Once this has been performed, the application starts normally, however no /graphql endpoint exists

**Comment by arsereg** [comment]
.   ____          _            __ _ _
/\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/  ___)| |_)| | | | | || (_| |  ) ) ) )
 '  |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/

:: Spring Boot ::                (v3.0.2)

2023-02-19T22:29:48.077-06:00  INFO 49765 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
 .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 26 ms. Found 1 JPA repository interfaces.
 o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
 o.apache.catalina.core.StandardService   : Starting service [Tomcat]
 o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.5]
 o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
 w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 545 ms
 o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
 org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.1.6.Final
 org.hibernate.orm.deprecation            : HHH90000021: Encountered deprecated setting [javax.persistence.sharedCache.mode], use [jakarta.persistence.sharedCache.mode] instead
 com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
 com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@4d20616a
 com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
 SQL dialect                              : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
 o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
 j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
 JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
 o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
 o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
 e.k.KotlinSpringbootTestDgsApplicationKt : Started KotlinSpringbootTestDgsApplicationKt in 1.728 seconds (process running for 2.162)
 o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
 o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
 o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms

**Comment by dwilkolek** [comment]
I think you just have wrong version. 
See the [PR](https://github.com/Netflix/dgs/pull/134) above and requirements listed [here](https://netflix.github.io/dgs/getting-started/#requirements).

**Comment by kilink** [comment]
Closing, as it was likely what was mentioned in the above comment; the "Getting Started" docs were unfortunately out of date. Please re-open if you still see this issue.
