### ISSUE TITLE
bug: Reactive Security context is not available in subscriptions

### ISSUE THREAD

**Issue by sipe90** [Netflix/dgs-framework#1442]
I have a Spring Boot WebFlux application with Spring Security OAuth2 resource server authentication.
When I try to access the Security Context within a subscription, `null` is returned instead of the context.

Spring Boot version is 3.0.2 and DGS Framework version is 6.0.0

## Expected behavior

Security context (fetched with `ReactiveSecurityContextHolder.getContext()`) should not be `null` when invoked within a subscription method during an authenticated request.

## Actual behavior

`ReactiveSecurityContextHolder.getContext()` returns `null` when invoked inside a subscription method.

## Steps to reproduce

The security configuration looks like this:

```kotlin
@Configuration
@EnableWebFluxSecurity
class WebFluxSecurityConfiguration {

    @Bean
    fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        val roles = arrayOf("role1", "role2")

        return http {
            authorizeExchange {
                authorize("/actuator/health", permitAll)
                authorize(anyExchange, hasAnyRole(*roles))
            }
            oauth2ResourceServer {
                val tokenConverter = ServerBearerTokenAuthenticationConverter()
                tokenConverter.setAllowUriQueryParameter(true) // This allows passing authentication token in a query parameter in websocket requests. eg. ws://localhost:8080/subscriptions?access_token=<token>
                bearerTokenConverter = tokenConverter
                jwt {
                    jwtAuthenticationConverter = CustomAuthenticationConverter()
                }
            }
        }
    }
}
```

And the subscription like this:

```kotlin
@DgsComponent
internal class EventsDataFetcher(private val eventService: EventService) {

    private val logger = KotlinLogging.logger {}

    @DgsSubscription(field = DgsConstants.SUBSCRIPTION.Events)
    fun events(): Flux<Event> =
        ReactiveSecurityContextHolder.getContext()
            .doOnSuccess { logger.info { it } }
            .thenMany(eventService.streamEvents())
```

When subscribing to the events, `null` is logged.

With queries, the request context can be accessed:

```kotlin
@DgsComponent
class UserDataFetcher(private val userService: UserService) {

    @DgsQuery
    fun currentUser(): Mono<User> {
        return ReactiveSecurityContextHolder.getContext()
            .map { it.authentication as CustomAuthentication }
            .map { auth ->
                User(
                    id = auth.principal.id,
                    firstName = auth.principal.firstName,
                    lastName = auth.principal.lastName,
                    roles = auth.authorities
                        .filterIsInstance<RoleAuthority>()
                        .map(RoleAuthority::role)
                )
            }
    }
}
```

I also tried creating a WebSocketHandler where I also successfully managed to access the security context.

**Comment by srinivasankavitha** [comment]
This should have been fixed with this PR:
https://github.com/Netflix/dgs-framework/pull/1313

That said, we don't use webflux internally and there could be issues with
using this feature in the webflux stack. I will do some more testing to
validate this. Unfortunately, due to conflicting priorities, I won't be
able to get to this in the next few weeks.

**Comment by sipe90** [comment]
That PR doesn't seem to affect the reactive websocket implementation, which is [DgsReactiveWebsocketHandler ](https://github.com/Netflix/dgs-framework/blob/18cdb3f579937c0e662be9570f218697768bfd64/graphql-dgs-spring-webflux-autoconfigure/src/main/kotlin/com/netflix/graphql/dgs/webflux/handlers/DgsReactiveWebsocketHandler.kt)from `graphql-dgs-spring-webflux-autoconfigure`.

**Comment by sipe90** [comment]
I've managed to come up with a workaround using a custom context:

```kotlin
@Component
class DgsSecurityContextBuilder : DgsReactiveCustomContextBuilderWithRequest<CamsAuthentication> {
    override fun build(
        extensions: Map<String, Any>?,
        headers: HttpHeaders?,
        serverRequest: ServerRequest?
    ): Mono<CamsAuthentication> {
        return ReactiveSecurityContextHolder.getContext().map { it.authentication as CustomAuthentication }
    }
}
```

```kotlin
@DgsSubscription(field = DgsConstants.SUBSCRIPTION.Events)
fun events(dfe: DataFetchingEnvironment): Flux<Event> {
	val auth = DgsContext.getCustomContext<CustomAuthentication>(dfe)

	if (!auth.authorities.contains(ActionAuthority(Action.STREAM_EVENTS))) {
		return Flux.error(AccessDeniedException("Forbidden"))
	}

	return eventService.streamEvents()
}
```

I would still prefer to be able to access the authentication from Spring's context since I use Reactive Method Security with custom AuthorizationInterceptors and annotations.

This workaround should suffice for now, but I hope this issue gets fixed soon.

**Comment by Mechwv** [comment]
@sipe90 Thx for your solution, this workaround works fine for subscriptions (just tested it out myself)

**Comment by srinivasankavitha** [comment]
Thanks for posting an update with the workaround. We will put in a fix
shortly for this issue.

**Comment by StringKe** [comment]
@sipe90 Implementing DgsReactiveCustomContextBuilderWithRequest in webflux websocket without any data.

Have you encountered this problem?

**Comment by lthoulon-locala** [comment]
This looks like it's still an issue, right ? It seems linked to my question here: https://github.com/Netflix/dgs-framework/discussions/1644

**Comment by lthoulon-locala** [comment]
> @sipe90 Implementing DgsReactiveCustomContextBuilderWithRequest in webflux websocket without any data.
> 
> Have you encountered this problem?

I got the same issue here. Workaround doesn't work for me. It doesn't seem logical that it would fix the problem either as it is trying to get the authentication from the context that is not filled. 🤷

**Comment by lthoulon-locala** [comment]
Actually the workaround works when the authorization header is provided on the handshake request.

**Comment by srinivasankavitha** [comment]
@lthoulon-locala - does setting the auth header in the handshake request unblock you?

**Comment by lthoulon-locala** [comment]
@srinivasankavitha 
Here it was I was able to do with the auth header in the handshake request:
```kotlin
@DgsComponent
class AggregateSubscriptions(val handler: AggregateSubscriptionsHandler) {
    @DgsSubscription
    fun aggregateNotifications(
        @InputArgument id: UUID,
        @InputArgument notificationTypes: List<NotificationType>?,
        dfe: DataFetchingEnvironment
    ) = let {
        val auth = DgsContext.getCustomContext<Authentication>(dfe)
        handler.aggregateNotifications(id, notificationTypes, auth)
    }
}

@Component
class AggregateSubscriptionsHandler {
    // I put the 3 annotations that I tested but of course one should only use one at the time.
    @PreAuthorize("hasAuthority('$AGGREGATE_READ')") // Rincewind: THAT DOESN'T WORK
    @PreAuthorize("@myPermissionEvaluator.hasAuthority(#auth, '$AGGREGATE_READ')")
    @Secured(AGGREGATE_READ)
    fun aggregateNotifications(id: UUID, notificationTypes: List<NotificationType>?, auth: Authentication) =
        Flux.interval(Duration.ofMillis(1000))
            .map {
                Notification.Builder()
                    .withAggregateId(id.toString())
                    .withNotificationType(NotificationType.AdvertiserAdded)
                    .withPayload(listOf(KeyValue.Builder().withKey("t").withValue(it.toString()).build()))
                    .build()
            }
}
```

So yes, this unblocks me although it's not ideal because i'll have different code in my queries and subscriptions. Also it means I can't use GraphiQL to test my subscriptions as it sends the authz parameters as part of the `connection_init` message. Hopefully Postman's GraphQL client uses headers still.

One interesting fact is that `@Secured` works. That means it's able to access the `Authorities`. Not sure how it does it yet while `PreAuthorize` isn't able to do so.

Any chance we could get a fix soon on this matter ?
Thanks

**Comment by lthoulon-locala** [comment]
Referencing this feature request: #450

**Comment by srinivasankavitha** [comment]
Thanks for the context @lthoulon-locala. As mentioned in the linked issue, we won't be able to prioritize this anytime soon, since Webflux stack is not internally used as much. We do accept contributions, in case you are interested or need this sooner.

**Comment by paulbakker** [comment]
WebFlux support is now coming from Spring GraphQL. See https://netflix.github.io/dgs/spring-graphql-integration/.
Closing this issue since it's not actionable anymore.
