### ISSUE TITLE
DgsQuery pass local context without returning any data (allow all child data fetchers to do the work)

### ISSUE THREAD

**Issue by connected-tcaceres** [Netflix/dgs-framework#1443]
Hello,
I was wondering if something was possible using dgs.
How would I go about ONLY fetching some data and passing down information to child data fetchers, and not actually return anything from the DgsQuery itself.
I would like the individual @DgsData functions to return the data that is required.

```
type Query {
getSomething: Something
}

type Something {
SomethingField1: String
SomethingField2: String
}

@DgsQuery(field = "getSomething")
fun getSomething(dfe: DgsDataFetchingEnvironment) {
//database call to get some information i want to pass down to @DgsData functions below
val someDataToPassDown = database.getData()

}

@DgsData(parentType = "getSomething",  field = "SomethingField1") {
fun getSomethingField1(dfe : DgsDataFetchingEnvironment) {
val localContext = dge.getLocalContext()
somethingService.getById(localContext.id1)
}

@DgsData(parentType = "getSomething",  field = "SomethingField2")
fun getSomethingField2(dfe : DgsDataFetchingEnvironment) {
val localContext = dge.getLocalContext()
somethingService.getById(localContext.id2)
}
```

**Comment by srinivasankavitha** [comment]
Please check out these docs for examples : https://netflix.github.io/dgs/advanced/context-passing/
Hope that helps.

I am closing this issue since this is more of a discussion item. Please feel free to open a new issue if you find that something is not working as expected.
