### ISSUE TITLE
feature: Support SSE on Webflux

### ISSUE THREAD

**Issue by esfomeado** [Netflix/dgs-framework#1448]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue. Also consider discussing your idea on
the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) first.

## Describe the Feature Request
As of now only WebSockets are supported on Webflux.

It would be helpful if SSE were supported as well.

## Describe Preferred Solution
Similar to how it happens now for MVC.

If the SSE module is included wire up the SSE handler.

**Comment by srinivasankavitha** [comment]
Thanks for creating an issue. We won't be able to prioritize this anytime
soon since webflux stack is not use internally yet. We do welcome PR
contributions if anyone is interested.

**Comment by paulbakker** [comment]
WebFlux support now comes from Spring GraphQL, so this would have to be implemented there. Closing this issue as not actionable.
