### ISSUE TITLE
feature: Consider switching graphiql CDN from unpkg to jsdelivr or another

### ISSUE THREAD

**Issue by jrogers** [Netflix/dgs-framework#1454]
## Describe the Feature Request

Unpkg seems to be flaky from time to time. For example at the moment loading react is failing, so graphiql isn't loading in netflix dgs installs - https://github.com/mjackson/unpkg/issues/356

## Describe Preferred Solution
Change to a larger/possibly more reliable npm cdn like jsdeliver - https://www.jsdelivr.com/package/npm/graphiql
Or serving from dgs as static resources

**Comment by jimaek** [comment]
Let me know if the jsDelivr team can help with anything :) We're very active and proactive

**Comment by srinivasankavitha** [comment]
Thanks for creating this issue. We will try this out :)

**Comment by srinivasankavitha** [comment]
Available in the latest 6.0.3 release
