### ISSUE TITLE
bug: subscription's type GQL_START must have value "subscribe" instead of "start"

### ISSUE THREAD

**Issue by dutchenkoOleg** [Netflix/dgs-framework#1471]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

Subscriptions should accept message with type `subscribe`. As it specified in protocol over WebSockets 
https://github.com/enisdenjo/graphql-ws/blob/fbb763a662802a6a2584b0cbeb9cf1bde38158e0/PROTOCOL.md#subscribe

```json
{
    "id": 1,
    "type": "subscribe",
    "payload": {
        "variables": {},
        "extensions": {},
        "operationName": null,
        "query": "..."
    }
}
```

## Actual behavior

Subscriptions expect payload type with value "start".

## Steps to reproduce

_Sorry I'm from "frontend" world and not familiar with Java_ 
_My investigation was end with that search https://github.com/Netflix/dgs-framework/search?q=GQL_START_

----

Can anyone tell what going wrong?

**Comment by srinivasankavitha** [comment]
I suspect the client is not setting the `SEC_WEBSOCKET_PROTOCOL` header in the request and therefore the frameowrk is defaulting to the older websocket protocol. Please ensure that the header is set approrpriately to the protocol value: https://github.com/enisdenjo/graphql-ws/blob/fbb763a662802a6a2584b0cbeb9cf1bde38158e0/PROTOCOL.md#communication

The check that is triggered is here:
https://github.com/Netflix/dgs-framework/blob/b6481e702857ce7fab62ee3a6010e4735f080545/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsHandshakeInterceptor.kt#L37

Hope this helps.
