### ISSUE TITLE
feature: update to latest graphql-java 19.x release

### ISSUE THREAD

**Issue by setchy** [Netflix/dgs-framework#1472]
## Describe the Feature Request
Depending on how easy/long it takes to action updating to graphql-java 20.x (https://github.com/Netflix/dgs-framework/issues/1467), there may be value in the near-term releasing a new version using the latest graphql-java 19.x ([19.5](https://github.com/graphql-java/graphql-java/releases/tag/v19.5) at time of issue creation).

Both [19.4](https://github.com/graphql-java/graphql-java/releases/tag/v19.4) and [19.5](https://github.com/graphql-java/graphql-java/releases/tag/v19.5) contained security fixes

## Describe Preferred Solution
Updating to latest 19.x series of dependencies

## Describe Alternatives
Put focus/energy into https://github.com/Netflix/dgs-framework/issues/1467

**Comment by srinivasankavitha** [comment]
Thanks for the issue @setchy. We will be updating this soon.

**Comment by congotej** [comment]
Thank you for the suggestion! @setchy this was just released in [v6.0.3](https://github.com/Netflix/dgs-framework/releases/tag/v6.0.3)!
