### ISSUE TITLE
InvalidSyntaxError while runnig spring boot app based on graphql-dgs-spring-boot-starter

### ISSUE THREAD

**Issue by kgromov** [Netflix/dgs-framework#1484]
### Discussed in https://github.com/Netflix/dgs-framework/discussions/1479

<div type='discussions-op-text'>

<sup>Originally posted by **kgromov** April 14, 2023</sup>
Hi, I faced with the following issue:  
```
InvalidSyntaxError while runnig spring boot app based on graphql-dgs-spring-boot-starter
```
Below are some details/expectations.     

## Expected behavior:
Application is up and running with successfully generated classes from defined schema
_____
## Actual behavior:
Application is failing on startup with not meaningful error message
_____
## Steps to reproduce:

- I'm a  using ``graphql-dgs-platform-dependencies:6.0.1`` with spring-boot 3.+ (3.05), java 17 and code generation plugin ('com.netflix.dgs.codegen' version "5.7.0") for home examples.
- Code generation is passed successfully application is failed at startup with the following unclear error:   
```
There are problems with the GraphQL Schema:
	 * InvalidSyntaxError{ message=Invalid Syntax : offending token '"name"' at line 2 column 3 ,offendingToken="name" ,locations=[SourceLocation{line=2, column=3}] ,sourcePreview={
  "name": "Untitled GraphQL Schema",
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
}
```
____________________
Absolutely same schema is working fine with ``spring-boot-starter-graphql`` based spring boot app v3.0.5 and java 17 (there is only difference in ``graphql-java`` version - 19.5 vs 19.3 in spring-boot-starter-graphql) with hand written classes corresponding to schema types.
To my mind if schema is incorrect code generation should fail, isn't it?

Here is schema:
```
type Query {
    category(id: String): Category
    categoryByName(name: String): Category
    categories: [Category]
    recipe(id: String): Recipe
    recipes: [Recipe]
}

type Mutation {
    addRecipe(description: String): Recipe
    addRecipeWithPayload(recipeDto: RecipeDto): Recipe
    addCategory(name: String): Category
}

type Category {
    id: ID
    name: String
    recipes: [Recipe]
}

type Recipe {
    id: ID
    description: String
    prepTime: Int
    cookTime: Int
    servings: Int
    source: String
    url: String
    notes: String
    difficulty: Difficulty
    category: Category
}

input RecipeDto {
    description: String
    prepTime: Int
    cookTime: Int
    servings: Int
    source: String
    url: String
    notes: String
    difficulty: Difficulty
    categoryId: String
}

enum Difficulty {
    EASY, MODERATE, KIND_OF_HARD, HARD
}
```
Full source code can be found [here](https://github.com/kgromov/dgs-graphql)
Working solution without netflix platform/starters - [here](https://github.com/kgromov/recipe-graphql/tree/batching-web-mvc-h2-spring-boot-3).    

Thanks in advance
</div>

**Comment by coleturner** [comment]
Hey @kgromov thank you for sharing this issue and your source code. I was able to determine that the issue seems to be that when there is a .graphqlconfig file in the `schema/` path, it is being ingested as possible schema. On our end, we're going to dig deeper into why that is, however, in the meantime, my suggestion would be to move this file outside of `schema/`. If you can, I would move it to your application repository root folder.

After our investigation, we may update this thread with our findings. Please let us know whether the alternative suggestion above is helpful or not.

**Comment by kgromov** [comment]
Hi, @coleturner, moving .graphqlconfig outside ``shema`` folder helped.
So I guess issue can be closed.
