### ISSUE TITLE
feature: use CustomObjectMapper to serialize subscription data

### ISSUE THREAD

**Issue by clayembry** [Netflix/dgs-framework#1528]
## Describe the Feature Request
A [CustomObjectMapper](https://netflix.github.io/dgs/advanced/custom-object-mapper/) can be supplied for serializing GraphQL responses. But that object mapper is not used to serialize subscription data. The [objectMapper](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/WebsocketGraphQLWSProtocolHandler.kt#LL109C53-L109C53) used to serialize subscription data is instantiated in the [companion object for the WebsocketGraphQLWSProtocolHandler](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/WebsocketGraphQLWSProtocolHandler.kt#L151) class.

This is causing our subscriptions to fail sending data because the objects we are trying to send contain `OffsetDateTime` fields that cause the ObjectMapper to throw exceptions because the `JavaTimeModule` is not registered with the subscription ObjectMapper.

## Describe Preferred Solution
Please consider injecting the CustomObjectMapper into the `WebsocketGraphQLWSProtocolHandler` class to use for serializing subscription data.

**Comment by coleturner** [comment]
Hey @clayembry 👋 

Our team met to discuss this issue and we came to the conclusion that we would prefer to internalize the mapping of objects used across the DGS framework, so we will instead add `OffsetDateTime` and map it to `JavaTimeModule`. Thanks for your patience as we hope to release this in the next week or two.

**Comment by clayembry** [comment]
@coleturner - your fix did not fix the problem we are facing. Because neither `WebsocketGraphQLWSProtocolHandler` or `WebsocketGraphQLTransportWSProtocolHandler` inject the `dgsObjectMapper`.

Both of those classes that we are having issues with just instantiate their own plain ObjectMapper in the companion object using `val objectMapper = jacksonObjectMapper()`.
- https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/WebsocketGraphQLTransportWSProtocolHandler.kt#L226
- https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/WebsocketGraphQLWSProtocolHandler.kt#L151

Please fix so that those two classes inject the `dgsObjectMapper` and use it instead.
