### ISSUE TITLE
feature: Adding new response type on batch data loaders

### ISSUE THREAD

**Issue by SaranSundar** [Netflix/dgs-framework#1530]
For batch data loaders the only signature I see is 

`CompletionStage<List<V>> load(List<K> keys)`

Was wondering if it's possible to support `Flux<V> load(List<K> keys)`

It feels more readable and intuitive in Java.

**Comment by coleturner** [comment]
Hey @SaranSundar the functionality for data loaders is actually provided by graphql-java:
https://github.com/graphql-java/java-dataloader
