### ISSUE TITLE
feature: Do not log the invalid query as part of the 400 response

### ISSUE THREAD

**Issue by srinivasankavitha** [Netflix/dgs-framework#1560]
Requested by a DGS user since logging the query results in security issues:
```
We're running into a security issue where DGS is trying to be very helpful and echoes back the invalid query within the 400 response. Is there a way to "reduce its desire to help" and only provide minimal error communication?
```

**Comment by gracecding** [comment]
The logging for invalid queries comes from [graphql-java](https://github.com/graphql-java/graphql-java/blob/a54bb43936a3b68fe44ee55032e407c8a703c263/src/main/java/graphql/GraphQL.java#L514). To disable this logging, turn off the lognotsafe logger in your application.yml: `logging.level.notprivacysafe: OFF`

**Comment by gracecding** [comment]
[This PR](https://github.com/Netflix/dgs/pull/148) adds a logging page to the DGS docs.
