### ISSUE TITLE
bug: A variables value that has been set to null in a graphql request now results in an exception with Netflix DGS 7.2.0.  No exceptions in prior Netflix DGS versions.

### ISSUE THREAD

**Issue by smgonzales** [Netflix/dgs-framework#1562]
Our services use [Apollo Rover](https://www.apollographql.com/docs/rover/) to introspect our subgraphs during our pipeline builds.  Moving to Netflix DGS 7.2.0 with [Apollo Rover](https://www.apollographql.com/docs/rover/) causes the introspection from [Apollo Rover](https://www.apollographql.com/docs/rover/) to fail with a a Bad Request 400 error.  This behavior is not present in the proceeding Netflix DGS 7.1.0 version or other versions prior.

Subgraph introspect graphql Post body sent by Apollo Rover is the following:

Rover command: `rover subgraph introspect http://localhost:8085/graphql`

Post body received by DgsRestController.kt:

`{"variables":null,"query":"query SubgraphIntrospectQuery {\n    # eslint-disable-next-line\n    _service {\n        sdl\n    }\n}","operationName":"SubgraphIntrospectQuery"}`

The mapper line indicated below from DgsRestController.kt throws an exception since **variables** is null, but the variables in the InputQuery data class is not nullable nor is there code to populate an empty map if the **variables** is null.  Code prior to 7.2.0 handled the case where **variables** was null or an empty JSON object map.

```
       if (GraphQLMediaTypes.includesApplicationGraphQL(headers)) {
            inputQuery = InputQuery(query = body.bufferedReader().readText())
        } else {
            try {
               inputQuery = mapper.readValue(body)  // EXCEPTION OCCURS HERE
            } catch (ex: Exception) {
                return when (ex) {
                    is JsonParseException ->
                        ResponseEntity.badRequest()
                            .body("Invalid query - ${ex.message ?: "no details found in the error message"}.")
                    is MismatchedInputException ->
                        ResponseEntity.badRequest()
                            .body("Invalid query - No content to map to input.")

                    else ->
                        ResponseEntity.badRequest()
                            .body("Invalid query - ${ex.message ?: "no additional details found"}.")
                }
            }
        }
```

```
        private data class InputQuery(
            val query: String?,
            val operationName: String? = null,
            val variables: Map<String, Any> = mapOf(),
            val extensions: Map<String, Any> = mapOf()
        )
```

## Expected behavior

There is nothing in the GraphQL specification regarding the empty value for **variables** in the POST request so I'm uncertain if this is now becomes a bug in Apollo Rover itself or if the DgsRestController.kt should continue to handle **variables** being either null, not present at all, or an empty map.  Ideally Apollo Rover would simply not include the **variables** in the body at all, but as far as I can tell a null for **variables** has been the behavior for a while.

If the library is wanting to continue to preserve behavior prior to 7.2.0 then a null **variables** should continue to work as with past behavior.  A null **variables** results in an empty map in the InputQuery data class.

## Actual behavior

A null **variables** results in MismatchedInputException with the following stack trace:

```
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.netflix.graphql.dgs.mvc.DgsRestController$Companion$InputQuery] value failed for JSON property variables due to missing (therefore NULL) value for creator parameter variables which is a non-nullable type
 at [Source: (org.springframework.web.util.ContentCachingRequestWrapper$ContentCachingInputStream); line: 1, column: 173] (through reference chain: com.netflix.graphql.dgs.mvc.DgsRestController$Companion$InputQuery["variables"])
```

## Steps to reproduce

On any service using Netflix DGS 7.2.0 execute the Apollo Rover introspect command.  The command will issue a POST request where **variables** is null.

Rover command: `rover subgraph introspect http://localhost:8085/graphql`

Overview: https://www.apollographql.com/docs/rover/
Install:  https://www.apollographql.com/docs/rover/getting-started

**Comment by srinivasankavitha** [comment]
@smgonzales - thank you for the detailed report. In the last release, we did introduce this regression and will fix the behavior  in the upcoming release this week.

**Comment by srinivasankavitha** [comment]
PR for fix: https://github.com/Netflix/dgs-framework/pull/1564
