### ISSUE TITLE
bug: Ignore unknown json properties when parsing request object into InputQuery type

### ISSUE THREAD

**Issue by jrogers** [Netflix/dgs-framework#1577]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

That request parsing be resilient to unknown properties in the graphql request. This seems to have been a regression in 7.x.

## Actual behavior

If a graphql request is called by an older graphql implementation and say sets the operation name in the JSON serialization as legacy `operation_name` the JSON parsing code will fail here and return bad request - https://github.com/Netflix/dgs-framework/blob/df1693edb934634a7775a7ff982e2caa339b0617/graphql-dgs-spring-webmvc/src/main/kotlin/com/netflix/graphql/dgs/mvc/DgsRestController.kt#L115
This is because it's is trying to strictly map to the new `InputQuery` type and does not ignore unknown properties. Previously the code prior to v7, would parse the request into the map, and it would simply end up not setting the operation name (which is fine).

Possible fix, add `@JsonIgnoreProperties(ignoreUnknown = true)` to the `InputQuery` type to make it more resilient - https://github.com/Netflix/dgs-framework/blob/df1693edb934634a7775a7ff982e2caa339b0617/graphql-dgs-spring-webmvc/src/main/kotlin/com/netflix/graphql/dgs/mvc/DgsRestController.kt#L82

Note that because the `operationName` field on the `InputQuery` type is nullable, not setting it at all works as expected.

## Steps to reproduce

Create a graphql request to any endpoint but change `operationName` property to `operation_name`, or even easier add an unknown/non-standard property to the request json. It will fail with 400.

**Comment by gracecding** [comment]
We will look into this.

**Comment by congotej** [comment]
Hi @jrogers! I am going to go ahead and close this, as the fix was just merged and should be out in the next release. Thanks for bringing this up!
