### ISSUE TITLE
bug: incorrect Validation error fields have different nullability shapes with union

### ISSUE THREAD

**Issue by Jarda8** [Netflix/dgs-framework#1583]
There is an incorrect query validation in tests when using the generate query classes. The GraphQL schema is as follows:
```
type Entity {
    id: String!
}

type Type1 {
    entity: Entity! # note the difference in nullability
}

type Type2 {
    entity: Entity # note the difference in nullability
}

union TypesUnion =  Type1 | Type2
```
Now, when a test query is called with DgsQueryExecutor.execute(...) and there is a projection containing both `onType1().entity().id()` and `onType2().entity().id()`, an error is thrown saying "Validation error (FieldsConflict@[<>]) : 'entity' : fields have different nullability shapes".

When only one or the other is used in the projection, one of the fields is renamed, or both `entity` fields are either nullable or not, everything is OK. Those types in the union should be unrelated and it should be OK to have fields with the same name and type but different nullability.

## Expected behavior
The test query validation will pass in the case given above.

## Actual behavior
A query validation error is thrown.

## Steps to reproduce

Creating the schema described above and calling a DGS test query via `DgsQueryExecutor` containing the a projection with the fields described above.

**Comment by srinivasankavitha** [comment]
This error is a validation error in graphql-java and expected for the schema you have set up. The [spec ](http://spec.graphql.org/June2018/#sec-Field-Selection-Merging )states: 
```
If multiple field selections with the same response names are encountered during execution, the field and arguments to execute and the resulting value should be unambiguous. Therefore any two field selections which might both be encountered for the same object are only valid if they are equivalent.

During execution, the simultaneous execution of fields with the same response name is accomplished by [MergeSelectionSets](http://spec.graphql.org/June2018/#MergeSelectionSets())() and [CollectFields](http://spec.graphql.org/June2018/#CollectFields())().

For simple hand‐written GraphQL, this rule is obviously a clear developer error, however nested fragments can make this difficult to detect manually.
```

Closing this as it is not supported per GraphQL spec.

**Comment by Jarda8** [comment]
Strange, but OK. Thanks for the explanation.
