### ISSUE TITLE
bug: NPE on upgrade

### ISSUE THREAD

**Issue by GellertH** [Netflix/dgs-framework#1586]
## Background
I'm updating DGS libraries from 4.10.2 to 5.5.3 due to newline(\n) handling, then running a @SpringBootTest integration test which uses DgsQueryExecutor directly to fire queries to the running test server.

## Expected behavior
Tests pass. Without issue.
## Actual behavior
The bug https://github.com/Netflix/dgs-framework/issues/1105 gets reproduced exactly. 
TLDR: Custom headers throw NPE due to requestData.webRequest being null in the context.
## Steps to reproduce
Use The following relevant lib versions:
- id 'org.springframework.boot' version '2.7.0'
- implementation(platform('com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:5.5.3'))
- implementation('com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:5.5.3')
- implementation('com.netflix.graphql.dgs:graphql-dgs-extended-scalars:5.5.3')

_Note: 
THis is fixed in https://github.com/Netflix/dgs-framework/pull/1421 but is not contained in 5.5.3

Workaround: 
Use a MockHttpServletRequest to pass the headers and wrap the DgsQueryExecutor bean in the text context with a custom implementation of DgsQueryExecutor overriding all methods that pass headers.

**Comment by srinivasankavitha** [comment]
Hi @GellertH - We decided to add new features and fixes in the Spring Boot 3 compatible versions of DGS , i.e >6.x. Unless there are major security fixes, or other critical fixes, we are not backporting changes to reduce our maintenance overhead. Please switch to the latest 7.x version if possible.
