### ISSUE TITLE
Incorrect mapping for array of inputs

### ISSUE THREAD

**Issue by Fruko** [Netflix/dgs-framework#159]
Hello,

I noticed that DGS maps the input type to LinkedHashMap instead of instance of class. I checked documentation and examples and it seems as a bug to me, if not please feel free to close

given the schema such as
```
    incorrectMapping(reviews: [SubmittedReview!]!): Boolean!
```

and related data fetcher

```
    @DgsData(parentType = DgsConstants.MUTATION.TYPE_NAME, field = "incorrectMapping")
    public boolean incorrectMapping(@InputArgument("reviews") List<SubmittedReview> reviews) {
        return true;
    }
```

the result should be list of `SubmittedReview` class instances instead of `LinkedHashMap`

![image](https://user-images.githubusercontent.com/10186522/111323381-1c09ed00-866a-11eb-85da-3bd3505261ee.png)

**reproduction repo**: https://github.com/Fruko/dgs-examples-java
**example mutation:** 
```
mutation {
     incorrectMapping(reviews: [{showId: 0, username: "test", starScore: 1}])
}
```

**Comment by paulbakker** [comment]
@Fruko The missing piece in your code example is the `collectionType` parameter in `@InputArgument`. That's needed for List to figure out the type contained in the list. I agree this is confusing, I'll look into at least adding some logging with hints if this is missing.

This is mentioned in the docs under `Using @InputArgument with lists` here: https://netflix.github.io/dgs/datafetching/
