### ISSUE TITLE
bug: When use apollo-link-batch-http cause exception

### ISSUE THREAD

**Issue by WenSteven** [Netflix/dgs-framework#1608]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Steps to reproduce

About apollo-link-batch: https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/

When I use apollo-link-batch request graphql，response  is `Invalid query - No content to map to input.`

so my graphql request would  be :

<img width="472" alt="image" src="https://github.com/Netflix/dgs-framework/assets/16606173/9856482b-4dc0-4545-affe-d77f9ff7fc5e">

that is json array，but in `DgsRestController` line 115 : `inputQuery = mapper.readValue(body)` CAUSE exception

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by kailyak** [comment]
Thanks for opening the issue. We currently do not support batch requests since this is not widely used internally. We will add it to our backlog to prioritize for future based on use cases.

**Comment by paulbakker** [comment]
Closing this issue because the transport layer for DGS is now handled by Spring GraphQL.
