### ISSUE TITLE
Use servlet context path for GraphiQL graphql path

### ISSUE THREAD

**Issue by jandrade1** [Netflix/dgs-framework#171]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
When using GraphiQL in an application with a servlet context path other than `/`, it should take the context path into account for the GraphQL endpoint.

## Actual behavior
When using GraphiQL in an application with a servlet context path other than `/`,  it tries to call the GraphQL endpoint under `/graphql` (without the context path) which causes a 404

## Steps to reproduce
In a Spring Boot application, configure the servlet context path to an alternate path by adding the `server.servlet.context-path` property (for example, `server.servlet.context-path=/foo`). Then go to the GraphiQL page, open Chrome developer tools, and notice the 404 error in the console.

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by jandrade1** [comment]
@bono007 , created this issue as you requested in https://github.com/Netflix/dgs-framework/pull/153#issuecomment-803182665.

In case it helps, the first thing that came to mind as a solution to this is to autowire the `ServletContext` directly into `GraphiQLConfigurer`, then grab the context path from it (`context.getContextPath()`) and prepend it to `configProps.path` when you add the transformer.

**Comment by bono007** [comment]
Thx for the detailed writeup @jandrade1 . 

> Note: A test case would be highly appreciated, but we understand that's not always possible

❤️ it. This is the 1st thing I do before fixing a bug - write a test and watch it go from 🔴 -> 🟢 

And injecting the `ServletContext` would be a good approach as well. 

Picking this up tomorrow am.
