### ISSUE TITLE
feature: Spring Boot 3.1.x Support

### ISSUE THREAD

**Issue by Wallman** [Netflix/dgs-framework#1712]
Would love support for Spring Boot 3.1.x !

Not sure how it works but currently locked in at 3.0.8? https://github.com/Netflix/dgs-framework/blob/master/dependencies.lock#L10

**Comment by paulbakker** [comment]
Spring Boot 3.1 (and 3.2-RC2) are supported.
Just force the version you want instead of getting it from the DGS BOM.

The Spring Boot version from the DGS BOM is more like a minimal version.
