### ISSUE TITLE
feature: Spring Boot 3.2.x Support

### ISSUE THREAD

**Issue by iuriichulovskyi** [Netflix/dgs-framework#1733]
## Describe the Feature Request
Could you please add support for Spring Boot 3.2.x?
Looks like Spring Boot 3.2.0 requires `<graphql-java.version>21.3</graphql-java.version>`.  
But DGS platform strictly require version `21.2` https://github.com/Netflix/dgs-framework/blob/969b7212778a2fa457105e024213abd8c0734713/graphql-dgs-platform/build.gradle.kts#L52C1-L52C1

Could you please migrate to version 21.3 to be compatible with Spring Boot 3.2.0?

**Comment by Emily** [comment]
see https://github.com/Netflix/dgs-framework/releases/tag/v8.2.0
