### ISSUE TITLE
bug: UnknownOperationException should return 400 instead of 500

### ISSUE THREAD

**Issue by pjungels-paraport** [Netflix/dgs-framework#1751]
## Expected behavior
`{ "operationName": "books", "variables": {}, "query": "{ books {\nid\nname\n} }" }`
When this type of request/query is submitted (note, the operationName "books" without a matching named query), an UnknownOperationException is thrown from graphql.language.NodeUtil. When an UnknownOperationException is thrown, the result should be ResponseEntity.badRequest... since it is a malformed request.

## Actual behavior
When this type of query is submitted and an UnknownOperationException is thrown, the current behavior is that an Internal Server Error is returned to the caller.

## Steps to reproduce
Submit a named query with non-matching operationName. Or submit a non-named query with any operationName specified. Or submit two named queries without an operationName specified.

**Comment by pjungels-paraport** [comment]
Looks like I don't have access to create a branch/submit a pull request. Can I get access? Otherwise I can just share the code here.

**Comment by paulbakker** [comment]
> Looks like I don't have access to create a branch/submit a pull request. Can I get access? Otherwise I can just share the code here.

The common workflow on Github is to fork the repo to your personal account, and create a PR from there to the the main repo.
