### ISSUE TITLE
feature: Ability to assign existing interface to an input type

### ISSUE THREAD

**Issue by jblacker** [Netflix/dgs-framework#1765]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue. Also consider discussing your idea on
the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) first.

## Describe the Feature Request
There's a lot of schemas that have input types that are very similar, but have a few small differences. An example of this would be for a mutation that creates an entity vs one that updates an existing entity. These input objects would be identical except that the update one would include an ID. When writing code related to these input objects we often have to either convert them to another type that has all the shared fields, or have multiple "paths" to handle the different types. The ideal situation would be that we can manually create an interface that contains the shared fields and have that interface be added to the generated type.

## Describe Preferred Solution
It would be great if within the Gradle configuration we can specify what interfaces should be added to what generated types. The configuration for this could look similar to the `typeMapping` configuration option, except you can specify an existing interface to be added to that type (maybe even an array of interfaces optionally). I would imagine it looking something like this:
```
generateJava {
  attachInterfaces = [MyInputType: [com.mystuff.MyInterface, com.mystuff.AnotherInterface], 
                      AnotherInputType: [com.mystuff.MyInterface]]
```

## Describe Alternatives
The main underlying issue here is that you cannot use interfaces with GraphQL input types so I can't use the traditional GraphQL interfaces to handle this. Additionally, I didn't want to manually map the types, but I know that this is something that I can do as well by manually creating the generated input objects & interfaces and map that instead. I would prefer the codegenerator to do this though as it would eliminate having to create a lot of POJO/POKOs manually.

**Comment by jblacker** [comment]
Let me know if I should actually move this request to the codegen repo. I didn't realize it was separate initially.

**Comment by kilink** [comment]
@jblacker yeah, I think this issue belongs in the dgs-codegen repo; I'll close this one so it'd be great if you open one there. Thanks!
