### ISSUE TITLE
bug: DataFetchingEnvironment::localContext overwritten by Spring Actuator for Nested Data Fetchers

### ISSUE THREAD

**Issue by kevinlee2198** [Netflix/dgs-framework#1780]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
When Spring boot actuator is present, values passed to child data fetcher via `localContext` should be accessible following the [documentation](https://netflix.github.io/dgs/advanced/context-passing/).

## Actual behavior
Values are overridden to instead be a Map containing a `SimpleObservation` value.  
Class cast exception then occurs follows:
```
"message": "java.lang.ClassCastException: class graphql.GraphQLContext cannot be cast to class java.util.Map (graphql.GraphQLContext is in unnamed module of loader 'app'; java.util.Map is in module java.base of loader 'bootstrap')",
```

## Steps to reproduce
1. Create Spring boot project with web, graphql, actuator, and dgs dependencies
2. Create nested data fetcher like the [preload example in the documentation](https://netflix.github.io/dgs/advanced/context-passing/)
3. Run a graphql query, querying for the child attribute of the parent

Minimal Reproducible Example: https://github.com/kevinlee2198/dgs-local-context-demo

Note: Remove the actuator dependency and the query works as expected

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by kilink** [comment]
In your example app, you are including the dependency `spring-boot-starter-graphql`, which is causing this issue (see this [code](https://github.com/spring-projects/spring-graphql/blob/main/spring-graphql/src/main/java/org/springframework/graphql/observation/GraphQlObservationInstrumentation.java#L192)). If you remove that dependency, your example app works fine.

**Comment by kilink** [comment]
Here is the [related issue](https://github.com/spring-projects/spring-graphql/issues/918) in spring-graphl.

**Comment by kevinlee2198** [comment]
Got it, thanks for being on top of this.
