### ISSUE TITLE
DgsContext.getRequestData shared across requests

### ISSUE THREAD

**Issue by osi** [Netflix/dgs-framework#180]
## Expected behavior

`DgsContext.getRequestData` contains information for the _active_ request. 

## Actual behavior

If some requests invoke `DgsQueryExecutor.execute` passing in a WebRequest, and some don't, the ones that don't will see a  value for the request data incorrectly.

## Steps to reproduce

`DefaultDgsQueryExecutor.contextBuilder` is a shared component. However, https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsQueryExecutor.kt#L84 is directly setting an instance variable containing a web request.

If you mix requests against the `DgsRestController` controller (which passes in a `WebRequest`) with requests to `DgsSSESubscriptionHandler` (which does not pass in a `WebRequest`), the context on the subscriptions will contain request data from one of the non-subscription requests.

The context builder is stateful and incorrectly shares state across requests.

**Comment by paulbakker** [comment]
Fixed by #183
