### ISSUE TITLE
documentation: java client request example has small bug

### ISSUE THREAD

**Issue by rachelsleet** [Netflix/dgs-framework#182]
## What are you missing in the docs
In the [Java Client](https://netflix.github.io/dgs/advanced/java-client/) section the Rest Template example isn't working. The response is initialized with name `response` and is later referred to as `graphQLResponse`.

I tried opening a PR in the repo https://github.com/Netflix/dgs/pulls as suggested, but got denied:
`fatal: unable to access 'https://github.com/Netflix/dgs.git/': The requested URL returned error: 403` :( 

## Proposed change
docs/advanced/java-client.md 
Line 80

```
-    TicksConnection ticks = graphQLResponse.extractValueAsObject("ticks", TicksConnection.class);
+    TicksConnection ticks = response.extractValueAsObject("ticks", TicksConnection.class);
```

Thanks! Happy to answer any questions.

**Comment by paulbakker** [comment]
Thanks for reporting! Fixed in this commit: https://github.com/Netflix/dgs/commit/914352cc439c8d868f9144f1f8786ae6d9da1b7f

I don't know why you were unable to clone the repo - that should just work. Let us know if that remains to be a problem in the future.
