### ISSUE TITLE
documentation: error handling example is outdated for currentl graphql-java version

### ISSUE THREAD

**Issue by Patrickkooijman** [Netflix/dgs-framework#1832]
## What are you missing in the docs
The [error-handling](https://netflix.github.io/dgs/error-handling/) page shows an example which ends with a delegate call to handle other exceptions then `MyException`.` 

`
         return DataFetcherExceptionHandler.super.handleException(handlerParameters);
`

This default method was however deprecated and is removed in `graphql-java` 21.3, https://github.com/graphql-java/graphql-java/commit/1021219732d24866fb5957d8d8dc473b5d588f03

**Comment by paulbakker** [comment]
Updated the title to reflect it's about the graphql-java version, not Java itself.

Thanks for reporting @Patrickkooijman, we missed that.

**Comment by awesor** [comment]
Out of curiosity for someone who found this issue as they were upgrading versions and has a reference to that exact line of code in their codebase that's causing strife, what is the recommended line of code here (until of course the docs are updated) for a default handling of exceptions?  Should we just not have a default case?

Thanks again @Patrickkooijman for reporting this!

**Comment by ChristopherGustafson** [comment]
I solved this by creating an instance of `SimpleDataFetcherExceptionHandler` myself, and then calling `simpleDataFetcherExceptionHandler.handleException()` instead of `super.handleException()`. Similar to how the initial implementation looked like.

**Comment by paulbakker** [comment]
Fixed in https://github.com/Netflix/dgs/pull/193
