### ISSUE TITLE
bug: Switching to `graphql-dgs-spring-graphql-starter` breaks `Upload` GraphQL scalar

### ISSUE THREAD

**Issue by vigenere23** [Netflix/dgs-framework#1889]
## Expected behavior

Should work like before, as described by the documentation.

## Actual behavior

Since switching from `graphql-dgs-spring-boot-starter` to `graphql-dgs-spring-graphql-starter`, we now have a runtime error at the start of our application, stating `There is no scalar implementation for the named  'Upload' scalar type`. We have followed the documentation and it was working before the switch.

## Steps to reproduce

- Following this doc : https://netflix.github.io/dgs/advanced/file-uploads/
- Using codegen, we also added `Upload: "org.springframework.web.multipart.MultipartFile"` to the `typeMapping` plugin configuration
- In our data-fetcher, we receive a `MultipartFile` as input, which does compile

We are using Gradle with Kotlin and are on the latest version of both dgs codegen (6.1.6), dgs framework (8.5.6) and spring-boot (3.2.4). Here are all the dgs libraries that we are using :

```
implementation("com.netflix.graphql.dgs:graphql-dgs-spring-graphql-starter")
implementation("com.netflix.graphql.dgs:graphql-dgs-extended-scalars")
implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-micrometer")
implementation("com.netflix.graphql.dgs:graphql-dgs-pagination")
```

We are also using the `spring-boot-starter-web` library.

**Comment by srinivasankavitha** [comment]
WIth spring-graphql, you now need to add an external dependency for file uploads: https://netflix.github.io/dgs/spring-graphql-integration/#file-uploads

**Comment by vigenere23** [comment]
Wow thanks for the quick response! Should that section also be part of the "File Uploads" specific documentation page? Or at least a link that refers the page you mentioned?

**Comment by srinivasankavitha** [comment]
Yes, that's a good idea. I will fix that.
