### ISSUE TITLE
documentation: Incorrect Information in DGS Framework Documentation Regarding WebSocket Sub-Protocols

### ISSUE THREAD

**Issue by kobinarth-panchalingam** [Netflix/dgs-framework#1899]
## What are you missing in the docs
![image](https://github.com/Netflix/dgs-framework/assets/83297374/100f507a-fd51-4ab0-bbbc-d987536c2a1b)

The documentation for the DGS Framework currently contains incorrect information regarding the WebSocket sub-protocols graphql-transport-ws and graphql-ws. Specifically, the documentation states that graphql-ws is the deprecated sub-protocol, which is inaccurate. graphql-transport-ws is the deprecated sub-protocol, while graphql-ws is the newer protocol supported by the framework.

## Proposed text

Update the correct subprotocol names.

**Comment by srinivasankavitha** [comment]
Thanks for pointing out the confusion. We are referring to teh sub protocol names here, which are admittedly confusing. Please see https://www.apollographql.com/docs/react/data/subscriptions/#websocket-subprotocols
The deprecated protocol is referred to as subscriptions-transport-ws uses `graphql-ws` as the sub protocol.

**Comment by srinivasankavitha** [comment]
https://github.com/Netflix/dgs/pull/179
