### ISSUE TITLE
bug: unmapped fields after switching to Spring GraphQL integration

### ISSUE THREAD

**Issue by ychescale9** [Netflix/dgs-framework#1906]
## Expected behavior

No issue after switching to Spring GraphQL integration

## Actual behavior

I'm getting the same unmapped fields error as mentioned in https://github.com/Netflix/dgs-framework/issues/1885 after migrating to Spring GraphQL integration.

```
Unmapped fields: {Query=[_service]}
Unmapped registrations: {}
Skipped types: []
```

## Steps to reproduce

The only changes I made to migrate was switching the following dependencies:

```diff
-spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
+spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter-webflux" }

-dgs-starter = { module = "com.netflix.graphql.dgs:graphql-dgs-webflux-starter"}
+dgs-starter = { module = "com.netflix.graphql.dgs:graphql-dgs-spring-graphql-starter"}
```

Spring Boot: 3.2.5
DGS: 8.5.8

Please let me know if I'm missing anything obvious, otherwise I'll try to reproduce it in a test repo.

**Comment by ychescale9** [comment]
Thanks, disabling schema inspection does fix the unmapped fields errors. However I'm still getting the following when trying to open graphiql:

```
This application has no configured error view, so you are seeing this as a fallback.

Fri May 10 09:58:05 AEST 2024
[4c2a6599-2] There was an unexpected error (type=Not Found, status=404).
```

Has anything changed with spring-graphql?

**Comment by srinivasankavitha** [comment]
No changes with the spring-graphql integration regarding this behavior.  I'm not sure what this error is caused by either. You could try checking all the properties you are using to make sure nothing is misconfigured wrt graphql paths etc. : https://netflix.github.io/dgs/spring-graphql-integration/#dgs-configuration-with-spring-graphql

**Comment by ychescale9** [comment]
I'm not setting any of these properties before migrating to Spring GraphQl integration. I'll try to reproduce it in a sample project.

**Comment by ychescale9** [comment]
Looks like it's the url:
- `http://localhost:8000/graphiql/index.html` -> whitelabel error page
- `http://localhost:8000/graphiql` redirects to `http://localhost:8000/graphiql?path=/graphql` -> ✅
