### ISSUE TITLE
bug: "path" is not mapped from DataFetchingException to TypedGraphQLError

### ISSUE THREAD

**Issue by njuro** [Netflix/dgs-framework#1909]
Hi, in version 8.6.0, [GraphQLJavaErrorInstrumentation](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/GraphQLJavaErrorInstrumentation.kt) was introduced which maps exceptions to `TypedGraphqlError`. However in the case of `DataFetchingException` when the error builder is used, the `path` parameter [is not mapped](https://github.com/Netflix/dgs-framework/blob/c3e01f779109e47ce9f27924728d7a644b01fb80/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/GraphQLJavaErrorInstrumentation.kt#L53) and that information is therefore lost.

## Expected behavior
The mapped `TypedGraphqlError` should contain path if the original exception contained path.
## Actual behavior
The mapped `TypedGraphqlError` does not contain any path.
## Steps to reproduce
Throw data fetching exception and let the instrumentation math it to GQL error

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by srinivasankavitha** [comment]
Thanks for flagging. Fixed in #1910
