### ISSUE TITLE
Parameter 0 of constructor in com.netflix.graphql.dgs.webmvc.autoconfigure.DgsWebMvcConfigurationProperties required a bean of type 'java.lang.String' that could not be found. bug: 

### ISSUE THREAD

**Issue by JuneGe** [Netflix/dgs-framework#191]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

APPLICATION SUCCESS TO START

## Actual behavior
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.netflix.graphql.dgs.webmvc.autoconfigure.DgsWebMvcConfigurationProperties required a bean of type 'java.lang.String' that could not be found.

Action:

Consider defining a bean of type 'java.lang.String' in your configuration.

## Steps to reproduce

_Note: A test case would be highly appreciated, but we understand that's not always possible_ 
Development of language： java
framework：Spring boot
Version: 3.9.3
maven configuration：

        <dependency>
            <groupId>com.netflix.graphql.dgs</groupId>
            <artifactId>graphql-dgs-spring-boot-starter</artifactId>
            <version>${dgs.framework.version}</version>
        </dependency>

**Comment by paulbakker** [comment]
This is the same report as https://github.com/Netflix/dgs-framework/issues/181? 
Can you provide code to reproduce? Only the maven dependency doesn’t help much reproducing this.
