### ISSUE TITLE
feature: allow to customize code generation to not include a constructor with all arguments

### ISSUE THREAD

**Issue by tigermarques** [Netflix/dgs-framework#193]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue. Also consider discussing your idea on
the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) first.

## Describe the Feature Request
Currently, when types are generated from the schema, the following is created:
* empty constructor
* all arguments constructor
* getters and setters
* builder that uses the empty constructor

I have a use case where a type has a few hundred properties. This means that the code generation will create a constructor with a few hundred parameters, which goes beyond the supported limit (at least for Java 8, which is what I am using)

I would like a setting to exist that would allow to disable this constructor, since I don not need it anyway, I only use the getters and setters.

I don't know if there is a better alternative to avoid these kind of problems. Thank you!

**Comment by conker84** [comment]
Hi everybody. I would like to contribute on this. Can someone of the dev team mentor me about where to start and how the feature would look like?
