### ISSUE TITLE
bug: Java client query Invalid syntax when custom Scalar used

### ISSUE THREAD

**Issue by Fruko** [Netflix/dgs-framework#194]
## Expected behavior

When GraphQLRequest gets executed using generated code, no syntax error is thrown and data is returned. We are using a custom Scalar as an input parameter `UUID` as a parameter to get single entity by ID. When we generate the Java client to call such query in our service should return the same data as if the query is executed from browser/Postman

## Actual behavior
Invalid syntax error is thrown during execution:
`[GraphQLError(message=Invalid Syntax : Invalid syntax: token recognition error at: '-f' at line 1 column 37, path=[], locations=[{line=1, column=37}], extensions=GraphQLErrorExtensions(errorType=null, errorDetail=null, origin=, debugInfo=GraphQLErrorDebugInfo(subquery=, variables={}), classification=InvalidSyntax))]`

## Steps to reproduce
given the schema
```
type Query {
    testUUID: UUID
    testClientUUID(test: UUID!): UUID!
    testStr: String
    testClientStr(test: String!): String!
}

scalar UUID
```
and the Data fetcher 
```
@DgsComponent
public class ClientTestUUIDDataFetcher {
    @DgsData(parentType = DgsConstants.QUERY.TYPE_NAME, field = "testClientUUID")
    public UUID testClientUUID(@InputArgument("test") UUID test) {
        return test;
    }

    @DgsData(parentType = DgsConstants.QUERY.TYPE_NAME, field = "testUUID")
    public UUID testUUID() {
        return getData();
    }

    public UUID getData() {
        RestTemplate dgsRestTemplate = new RestTemplate();

        DefaultGraphQLClient graphQLClient = new DefaultGraphQLClient("http://localhost:8080/graphql");
        GraphQLResponse response = graphQLClient.executeQuery(buildQuery(), new HashMap<>(), (url, headers, body) -> {
            /**
             * The requestHeaders providers headers typically required to call a GraphQL endpoint, including the Accept and Content-Type headers.
             * To use RestTemplate, the requestHeaders need to be transformed into Spring's HttpHeaders.
             */
            HttpHeaders requestHeaders = new HttpHeaders();
            headers.forEach(requestHeaders::put);

            /**
             * Use RestTemplate to call the GraphQL service.
             * The response type should simply be String, because the parsing will be done by the GraphQLClient.
             */
            ResponseEntity<String> exchange = dgsRestTemplate.exchange(url, HttpMethod.POST, new HttpEntity(body, requestHeaders), String.class);

            /**
             * Return a HttpResponse, which contains the HTTP status code and response body (as a String).
             * The way to get these depend on the HTTP client.
             */
            return new HttpResponse(exchange.getStatusCodeValue(), exchange.getBody());
        });

        // prevent extraction that hides the real error
        if(response.hasErrors()) {
            System.out.println(response.getErrors());
            return null;
        }

        UUID test = response.extractValueAsObject("testClient", UUID.class);
        return UUID.fromString(test.toString());
    }

    private String buildQuery() {
        GraphQLQueryRequest graphQLQueryRequest =
                new GraphQLQueryRequest(
                        new TestClientUUIDGraphQLQuery.Builder()
                        .test(UUID.randomUUID()).build()
                );
        return graphQLQueryRequest.serialize();
    }
}
```

- run the project and execute this query 
 ```
{
    testUUID
}
 ```

Where `testUUID` ends up calling query `testClientUUID` which results in syntax error

- note that I have also added same query with `String` input instead of `UUID` input which works perfectly fine

### Reproduction repo
https://github.com/Fruko/dgs-examples-java

**Comment by Fruko** [comment]
I have just found a workaround by overriding the generated builder `TestClientUUIDGraphQLQuery` to use `String` instead of `UUID` 
which makes it work fine

**Comment by sbilello** [comment]
@Fruko Is there no need to register a scalar for UUID something like [register scalar for UUID?](https://netflix.github.io/dgs/scalars/)

**Comment by Fruko** [comment]
@sbilello there is uuid scalar registered, the app wouldnt start if it werent I believe

**Comment by sbilello** [comment]
so you didn't have to manually register. is it out of the box?

**Comment by Fruko** [comment]
no, you have to register it on your own e.g. https://github.com/Fruko/dgs-examples-java/blob/main/src/main/java/com/example/demo/scalars/UUIDScalar.java

**Comment by paulbakker** [comment]
We've just added support (in the 4.0 release candidate), to register a scalar when creating the `GraphQLQueryRequerst`. I think that's what you want to use here.

https://github.com/Netflix/dgs-framework/pull/333
