### ISSUE TITLE
Custom ExecutionStrategy

### ISSUE THREAD

**Issue by Meemaw** [Netflix/dgs-framework#1967]
Hi, I'm trying to configure custom ExecutionStrategy where we could do query caching.

I have a problem wiring things up correctly, as it seems I would need `DgsQueryExecutor` that I would call as a fallback when value is not in cache. This created a cyclic dependency.

Is there some way to achieve that differently?

**Comment by srinivasankavitha** [comment]
Hi - you can always create a bean for the execution strategy and add a qualifier `query` for queries and `mutation` for mutations. 

Example: 
```
@Bean("mutation")
  public ExecutionStrategy mutationExecutionStrategy(DataFetcherExceptionHandler exceptionHandler) {
    return new AsyncExecutionStrategy(exceptionHandler);
  }
```
Hope this helps.

**Comment by Meemaw** [comment]
Works, thanks!
