### ISSUE TITLE
Get request headers/ip inside ExecutionStrategy

### ISSUE THREAD

**Issue by Meemaw** [Netflix/dgs-framework#1968]
Is there a way to get request headers/ip in ExecutionStrategy?

There is `ExecutionContext` and `ExecutionStrategyParameters` available on the `execute` method but I haven't found request info anywhere.

**Comment by Meemaw** [comment]
Found DGSContext where headers can be extracted from. No ip though, since its not using the servlet api it seems.

**Comment by srinivasankavitha** [comment]
Yes, the DGSContext can be used for headers only. We don't have anything for ip.

**Comment by paulbakker** [comment]
Implement `DgsCustomContextBuilderWithRequest`, that gives you the `webRequest`. At runtime, in a servlet environment, that will be backed by the ServletRequest, which gives you access to what you want.
