### ISSUE TITLE
bug: Multiple data loaders found shown happens when handling requests 

### ISSUE THREAD

**Issue by kzwang** [Netflix/dgs-framework#2005]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

When multiple data loaders are using `@DgsDataLoader` with the same name, it should validate that and fail early.

## Actual behavior

App starts up successfully, but failed to handle requests with error "Multiple data loaders found"

## Steps to reproduce

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by mrvaruntandon** [comment]
@kzwang in which version you are seeing this issue?
