### ISSUE TITLE
bug: NoUniqueBeanDefinitionException when using org.springframework.boot:spring-boot-starter-data-rest dependency with dgs framework.

### ISSUE THREAD

**Issue by iparadiso** [Netflix/dgs-framework#2030]
NoUniqueBeanDefinitionException thrown in WebMvcArgumentHandlerConfiguration#dgsWebDataBinderFactory when using org.springframework.boot:spring-boot-starter-data-rest dependency.  This is due to ObjectProvider containing two `RequestMappingHandlerAdapter` instances one from OSS spring web and the other from RepositoryRestMvcConfiguration. 

## Expected behavior

DGS framework uses qualified injection for the spring OSS web instance.  @Qualifier("requestMappingHandlerAdapter").

## Actual behavior

NoUniqueBeanDefinitionException.  

Description:

Parameter 0 of method requestHeaderMapResolver in com.netflix.graphql.dgs.springgraphql.autoconfig.DgsSpringGraphQLAutoConfiguration$WebMvcArgumentHandlerConfiguration required a single bean, but 2 were found:
	- requestMappingHandlerAdapter: defined by method 'requestMappingHandlerAdapter' in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]
	- repositoryExporterHandlerAdapter: defined by method 'repositoryExporterHandlerAdapter' in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]

## Steps to reproduce

Add org.springframework.boot:spring-boot-starter-data-rest dependency dependency with basic Repository bean.

**Comment by iparadiso** [comment]
Will follow up wth a PR.

**Comment by paulbakker** [comment]
Fixed in #2031
