### ISSUE TITLE
documentation: It contains invalid link as url

### ISSUE THREAD

**Issue by Sujin1135** [Netflix/dgs-framework#2034]
## Proposed text

https://netflix.github.io/dgs/federation/

The above url is saying GraphQL Federation and contains the link in a text as "Federation Spec" to move apollo's federation spec page. but this page is not found.

<img width="785" alt="Screenshot 2024-10-14 at 1 19 48 AM" src="https://github.com/user-attachments/assets/b26ebb8e-8ed5-4ab3-b9ed-00807778c4b4">

<img width="1020" alt="Screenshot 2024-10-14 at 1 17 10 AM" src="https://github.com/user-attachments/assets/76011c8c-c644-4ef7-bf32-fd17970b20e3">

Please fix it to a valid url.

**Comment by paulbakker** [comment]
Thanks for reporting @Sujin1135, I just pushed a fix with the updated link.
