### ISSUE TITLE
documentation: dynamic schemas

### ISSUE THREAD

**Issue by brmakana** [Netflix/dgs-framework#204]
## What are you missing in the docs
Hello, I'm interested in using the dynamic schema features as described here: https://netflix.github.io/dgs/advanced/dynamic-schemas/. It mentions a `@DgsTypeDefinitionFactory`, which doesn't exist; it also mentions `TypeDefinitionFactory`, but then shows an example with `TypeDefinitionRegistry`. 

Would it be possible to clarify this page a little?

**Comment by srinivasankavitha** [comment]
Thanks for reporting, will fix this asap.

**Comment by srinivasankavitha** [comment]
Fixed by https://github.com/Netflix/dgs/pull/22.
