### ISSUE TITLE
Invalid link in code documentation

### ISSUE THREAD

**Issue by driptaroop** [Netflix/dgs-framework#22]
There are some documentation in code contains a link to a manual. For example, [this one](https://github.com/Netflix/dgs-framework/blob/5da78c93b382a040a54a207b8ee4d2c1b5287da8/graphql-dgs/src/main/java/com/netflix/graphql/dgs/DgsCodeRegistry.java#L26). I assume this link is from the internal netflix manual. Is there any plan to make these internal documentations open source? or else, is it possible to remove these links from the codes (this might be a bit confusing otherwise)? 
Thank you. 😄

**Comment by paulbakker** [comment]
The docs are open sourced already: https://netflix.github.io/dgs/getting-started/

The link in the code obviously needs to be updated. Thanks for reporting!

**Comment by driptaroop** [comment]
@paulbakker although not related, I found another dead link in the documentation. in the `Java GraphQL Client` page, this link, 
![image](https://user-images.githubusercontent.com/9862551/107789983-8d483e80-6d52-11eb-9d04-2e9f8586068b.png)
points to https://netflix.github.io/dgs/advanced/error-handling which just throws a 404 error instead.

**Comment by srinivasankavitha** [comment]
Thanks for bringing this to our attention. We will fix.

**Comment by paulbakker** [comment]
Fixed links in javadoc: https://github.com/Netflix/dgs-framework/commit/1344b2ae8438c12d994b5f07326a81a0b905c6d1

**Comment by paulbakker** [comment]
Fixed broken links in java-client docs as well.

**Comment by paulbakker** [comment]
I think I've fixed all the broken links. Thanks a lot for reporting!
