### ISSUE TITLE
documentation: SSE Subscriptions documentation & example

### ISSUE THREAD

**Issue by ddalcu** [Netflix/dgs-framework#236]
Do you have an example for both on the Server Side & Client side (Vanilla JS preferred) on how to do SSE Subscriptions using DGS ?

**Comment by srinivasankavitha** [comment]
We don't have an example documented yet. Thanks for reporting, we will add this.

**Comment by ddalcu** [comment]
is it possible ? Maybe pointing to an example while the documentation is being written out ?

**Comment by srinivasankavitha** [comment]
Apologies for the delay. We don't have an example ready yet to be shared as it is currently custom to our internal use case. We will share it once we have something. Owing to higher priority issues, we haven't been able to get to this yet.

**Comment by hantsy** [comment]
It seems the SSE is only designed for traditional WebMvc applications.

In my opinion, SSE/WebSocket(if Dgs team plans to support both protocols) should be implemented in WebMvc and WebFlux respectively, not the current state.

**Comment by hantsy** [comment]
And there is no simple method in the DgsQueryExecutor to handle subscribing actions to a `GraphQL Subscription`.

**Comment by hantsy** [comment]
I created an example of [sse subscription](https://github.com/hantsy/spring-graphql-sample/tree/master/dgs-subscription-sse).

I have [a UI client](https://github.com/hantsy/spring-graphql-sample/tree/master/dgs-subscription-ui) to demo subscription in the same repo, but it used Angular GraphQL and WebSocket.

For the client UI example for SSE, I think you can have a look at [another example](https://github.com/hantsy/angular-spring-sse-sample) of mine.  Send the raw JSON request to /graphql, and subscribe /subsctptions endpoint.

**Comment by Ancient-Dragon** [comment]
@srinivasankavitha are there any updates to this? Does dgs support sse for subscriptions and if not can we reuse this issue for it or should I create a new issue?

**Comment by hantsy** [comment]
@Ancient-Dragon  Dgs support SSE in the traditional WebMvc stack. Check my example the links in my last comments.

**Comment by Ancient-Dragon** [comment]
@hantsy Apologies I'm not familiar with kotlin, I couldn't see where it was setting the fact that it was using SSE rather than websockets. I can see now that it's brought in via dependencies sorry about that! Will this be added to the official documentation (I couldn't find it here either)?

**Comment by Ancient-Dragon** [comment]
I was able to confirm it with a basic example here (backend): https://github.com/Ancient-Dragon/dgs-sse-subscriptions-backend-example and here (frontend): https://github.com/Ancient-Dragon/dgs-sse-subscriptions-post-example 

To run you just need to run the backend and the dev command in frontend as well as the server command and it should give you the error I was referring to.

**Comment by paulbakker** [comment]
Closing this as SSE is now supported through the Spring GraphQL integration.
