### ISSUE TITLE
feature:  Send specific HTTP Status Code

### ISSUE THREAD

**Issue by juferdinand** [Netflix/dgs-framework#237]
## Describe the Feature Request

Can I send an specific HTTP Status Code?

## Describe Preferred Solution

Send 200, 201, 500 or something else if something happend like in Spring Web with HttpServletResponse.

Thanks for answer

**Comment by paulbakker** [comment]
Note that this typically isn't appropriate for GraphQL. In GraphQL errors are returned as part of the response, and responses can be partially successful, with some fields having errors.
That means for most cases, a 200 is required to be sent back.

What exactly is the use case you're thinking about?

**Comment by juferdinand** [comment]
Ah okay I understand. 

In the past I checked anytime the Responsecode if an Request was valid or anything went wrong. But now I need to find an another Method, maybe you have an Solution :)

Thx for answer

**Comment by juferdinand** [comment]
Other question I have too, how I can access Cookie and set Cookie with this Framework :)

**Comment by juferdinand** [comment]
@paulbakker For Response I use now Entity, but I don't know how to add  HttpOnlyCookies. If not yet implemented I would like something like this:

```
@dgsQuery(field="someQuery")
fun someFunction( response:DgsHttpResponse, request: DgsHttpRequest){
   response.addCookie(name = "", value = "")
   val cookieValue = request.getCookie(name = "")
}
```

I just know GraphQLForJava have an solution for it, but it works not with DGS. Thx for answer

**Comment by hantsy** [comment]
@juferdinand I think it can be fetched forms `DgsDataFetchingEnvironment`.

**Comment by paulbakker** [comment]
This can be done using `DgsRequestData` as shown in the example from @hantsy, and documented here: https://netflix.github.io/dgs/datafetching/#using-dgsrequestdata.
