### ISSUE TITLE
Need a fix in documentation

### ISSUE THREAD

**Issue by adil-waqar** [Netflix/dgs-framework#24]
First of all, what an awesome project. I've just started to play with this framework and I hope to use it in production, where I work.

So, while following the getting started guide, I saw a missing dependency that wasn't mentioned in the docs, which was `com.apollographql.federation:federation-graphql-java-support:0.6.1`. Also to mention that this was only available at `jcenter` so I had to add that as one of the gradle repositories in the following manner:
```groovy
repositories {
	mavenCentral()
	jcenter()
}
```

Also the documentation said to add the dependency in the following manner for `gradle`:
```groovy
dependencies {
    api "com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:latest.release"
}
```
In fact, I had to do the following for it work
```groovy
dependencies {
    implementation "com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:latest.release"
}
```
I'm overall new to the Java ecosystem so there might be something that I'm missing. Thank you!

**Comment by bearchit** [comment]
Thank you @adil-waqar

**Comment by setchy** [comment]
I'd be careful using `com.apollographql.federation:federation-graphql-java-support:0.6.1`  as that is based on `graphql-java:16.1` 

If you look inside the graphql-dgs Versions.kt you'll see they're using `graphql-java:15.0` and `com.apollographql.federation:federation-graphql-java-support:0.5.0`

There were a few breaking changes in graphql-jave between 15.0 and 16.1

**Comment by adil-waqar** [comment]
> I'd be careful using `com.apollographql.federation:federation-graphql-java-support:0.6.1`  as that is based on `graphql-java:16.1` 
> 
> If you look inside the graphql-dgs Versions.kt you'll see they're using `graphql-java:15.0` and `com.apollographql.federation:federation-graphql-java-support:0.5.0`
> 
> There were a few breaking changes in graphql-jave between 15.0 and 16.1
> 

Oh thanks! Didn't know that.

**Comment by paulbakker** [comment]
Thanks for catching this. Fixed in this PR: https://github.com/Netflix/dgs/pull/8

**Comment by tata406** [comment]
> First of all, what an awesome project. I've just started to play with this framework and I hope to use it in production, where I work.
> 
> So, while following the getting started guide, I saw a missing dependency that wasn't mentioned in the docs, which was `com.apollographql.federation:federation-graphql-java-support:0.6.1`. Also to mention that this was only available at `jcenter` so I had to add that as one of the gradle repositories in the following manner:
> ```groovy
> repositories {
> 	mavenCentral()
> 	jcenter()
> }
> ```
> 
> Also the documentation said to add the dependency in the following manner for `gradle`:
> ```groovy
> dependencies {
>     api "com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:latest.release"
> }
> ```
> In fact, I had to do the following for it work
> ```groovy
> dependencies {
>     implementation "com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:latest.release"
> }
> ```
> I'm overall new to the Java ecosystem so there might be something that I'm missing. Thank you!
