### ISSUE TITLE
Upgrade to Spring Boot 2.3.9.RELEASE

### ISSUE THREAD

**Issue by berngp** [Netflix/dgs-framework#256]
The [Spring Boot v2.3.9.RELEASE] is the latest `2.3` version and comes with several fixes to the framework as well as dependencies offered by the Spring Boot Dependencies BOM. The latter comes with upgraded dependencies, such as Micrometer 1.5.11 which addresses some problems found on the 1.5.7 and 1.5.8 versions. 

[Spring Boot v2.3.9.RELEASE]: https://github.com/spring-projects/spring-boot/releases/tag/v2.3.9.RELEASE

Ref. https://github.com/Netflix/dgs-examples-java/pull/6

**Comment by sbilello** [comment]
@berngp Is there any problem to support [spring-boot-2.4.4](https://spring.io/blog/2021/03/18/spring-boot-2-4-4-available-now)?

**Comment by berngp** [comment]
Internally we are not ready to move to Spring Boot 2.4 yet.
