### ISSUE TITLE
feature [graphql-dgs-extended-scalars]: Automatically add the scalars to the schema.

### ISSUE THREAD

**Issue by berngp** [Netflix/dgs-framework#260]
## Context
The `graphql-dgs-extended-scalars` module automatically registers the _Extended Scalars_ but it will not automatically declare them in the _schema_. This forces the developer to manually declare the scalars.

## Describe the Feature Request

An improvement suggested for the `graphql-dgs-extended-scalars` module would be to _auto-register_ as well the scalars in the _schema_.

**Comment by berngp** [comment]
We are debating if we should register the _scalars_ automatically in the _type registry_ or keep it explicit.

**Comment by hantsy** [comment]
I think currently registering scalar types automatically is ok. 

**removing the scalar declaring** will confuse those who newly come to the GraphQL world,  those scalar types are **NOT** part of the standard GraphQL spec.

**Comment by berngp** [comment]
Marking it as a won't fix since, as @hantsy points out, those scalar types are NOT part of the standard GraphQL spec and adding them will cause confusion.
