### ISSUE TITLE
bug: dgsQueryExecutor.executeAndExtractJsonPathAsObject cannot deserialize DateTime scalars

### ISSUE THREAD

**Issue by richardcresswell** [Netflix/dgs-framework#269]
## Expected behavior

The framework should serialize the json response to an object, including DateTime scalar values.

## Actual behavior

Jackson's ObjectMapper does not know about the scalar and a DgsQueryExecutionDataExtractionException is thrown.

## Steps to reproduce

Please see the issue I opened in [dgs-examples-java](https://github.com/Netflix/dgs-examples-java/issues/7).

**Comment by richardcresswell** [comment]
I'm not sure if this is as simple as adding

    .registerModule(JavaTimeModule())

to the ObjectMapper initialization.

**Comment by srinivasankavitha** [comment]
Thanks for reporting, we will look into it.

**Comment by richardcresswell** [comment]
@srinivasankavitha I managed to fix it and will have a pull request in soon.
