### ISSUE TITLE
bug: DgsWebMvcConfigurationProperties missing default values

### ISSUE THREAD

**Issue by luispollo** [Netflix/dgs-framework#270]
Got this exception while running some Spring Boot tests that loaded `DgsWebMvcAutoConfiguration`:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'dgs.graphql' to com.netflix.graphql.dgs.webmvc.autoconfigure.DgsWebMvcConfigurationProperties:

    Reason: org.springframework.boot.context.properties.bind.DefaultValue missing element value

Action:

Update your application's configuration
``` 

The issue seems to be with these two lines: https://github.com/Netflix/dgs-framework/blob/7b8f85822784eea3f210aa59e1b018fbdf9d77fb/graphql-dgs-spring-webmvc-autoconfigure/src/main/kotlin/com/netflix/graphql/dgs/webmvc/autoconfigure/DgsWebMvcConfigurationProperties.kt#L33-L34

I don't think you can have `@DefaultValue` without actually specifying a default value... 🙂 

## Expected behavior
Spring Boot application starts correctly when DGS library is included.

## Actual behavior
Application failed to start due missing configuration defaults

## Steps to reproduce
Create a test class annotated with `@SpringBootTest` that has `DgsWebMvcAutoConfiguration` and no config properties defined for DGS.

**Comment by luispollo** [comment]
Turns out this was caused by running the test with the IntelliJ test runner instead of gradle. Closing.

**Comment by clamothe** [comment]
This breaks running the application as a Spring Boot IntelliJ configuration.

**Comment by bono007** [comment]
> The DefaultValue annotation isn't intended to be used without a value.

The `@DefaultValue` annotation is used w/o a value on a nested configuration properties to ensure that a non-null instance is used even when no properties are bound to it. Look for the following snippet under the [Constructor Binding section](https://docs.spring.io/spring-boot/docs/2.3.9.RELEASE/reference/htmlsingle/#dependency-versions): 

> If you wish you return a non-null instance of Security even when no properties are bound to it, you can use an empty @DefaultValue annotation to do so:

**Comment by clamothe** [comment]
Ah okay, we're experiencing this due using a Spring Boot version that doesn't support this usage. I'll look into updating.

**Comment by CacheControl** [comment]
Upgrading from springboot 2.2 to 2.4 fixed this for us.
