### ISSUE TITLE
Upgrade the recommendation of graphql-java-extended-scalars to 16.0.0

### ISSUE THREAD

**Issue by berngp** [Netflix/dgs-framework#272]
The graphql-java-extended-scalars 16.0.0 is now available in Maven Central. Since we are recommending graphql-java 16.+ we should upgrade the `graphql-java-extended-scalars` recommendation as well.

ref. https://github.com/graphql-java/graphql-java-extended-scalars/issues/38

**Comment by marceloverdijk** [comment]
https://github.com/Netflix/dgs-framework/pull/273
