### ISSUE TITLE
Using DGS Platform and DGS Codegen in Gradle project causes issue with `api` scope

### ISSUE THREAD

**Issue by marceloverdijk** [Netflix/dgs-framework#274]
I tried to use the DGS Platform/BOM adding below to my Gradle project as documented [here](https://netflix.github.io/dgs/advanced/platform-bom/):

```
dependencies {
    // DGS BOM/platform dependency. This is the only place you set version of DGS
    api(platform('com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:3.10.2'))
    ..
```

If I understand correctly to use the `api` I need to change the `java` plugin to the `java-platform` plugin in my Gradle build file as otherwise I get a:

``` 
Could not find method api() for arguments [DefaultExternalModuleDependency{group='com.netflix.graphql.dgs', name='graphql-dgs-platform-dependencies', version='3.11.0', configuration='default'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

But when I do that, ~`id "java"~, id "java-platform" I get:

```
The "java-platform" plugin cannot be applied together with the "java" (or "java-library") plugin. A project is either a platform or a library but cannot be both at the same time.
```

So it seems some other plugin is adding it?

Looking further I found out it is the DGS Codegen plugin causing the issue as it is applying the Java plugin :dizzy_face::wink:

https://github.com/Netflix/dgs-codegen/blob/master/graphql-dgs-codegen-gradle/src/main/kotlin/com/netflix/graphql/dgs/codegen/gradle/CodegenPlugin.kt#L29

I reverted back to the Java plugin and changed:

```
dependencies {
    // DGS BOM/platform dependency. This is the only place you set version of DGS
    api(platform('com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:3.10.2'))
    ..
```

to

```
dependencies {
    // DGS BOM/platform dependency. This is the only place you set version of DGS
    implementation(platform('com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:3.10.2'))
    ..
```

and that seems to work as well. I have no experience so far using the Java Platform plugin or using`api` so I'm not sure using `implementation` instead could have side effects?

Probably good to mentions this in the docs?
And maybe avoid applying the Java plugin automatically in the DGS Codegen plugin if the Java Platform plugin is already applied?

**Comment by marceloverdijk** [comment]
Btw looking at the Spring documentation regarding their Platform/BOM support for Gradle they use this example:

```
dependencies {
	implementation platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
}
```

Note they use `implementation`.

**Comment by marceloverdijk** [comment]
I played a bit with the codegen adding the Java plugin conditionally like:

```
class CodegenPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        if (!project.getPluginManager().hasPlugin("java-platform")) {
            project.plugins.apply(JavaPlugin::class.java)
        }
        val taskProvider = project.tasks.register("generateJava", GenerateJavaTask::class.java)
        project.getTasksByName("compileJava", false).forEach {
            it.dependsOn(taskProvider.get())
        }

        project.getTasksByName("compileKotlin", false).forEach {
            it.dependsOn(taskProvider.get())
        }

        val javaConvention = project.convention.getPlugin(JavaPluginConvention::class.java)
        val sourceSets = javaConvention.sourceSets
        val mainSourceSet = sourceSets.getByName(SourceSet.MAIN_SOURCE_SET_NAME)
        val outputDir = taskProvider.get().getOutputDir()

        mainSourceSet.java.srcDirs(outputDir)
    }
}
```

That works for not applying the Java plugin, but then it will fail on:

```
val javaConvention = project.convention.getPlugin(JavaPluginConvention::class.java)
```

as when having the `java-platform` plugin there is no `JavaPluginConvention`. The `java-platform` plugin does not seem to have a similar convention, so I'm wondering if my assumption to use the `java-platform` plugin is correct?

**Comment by berngp** [comment]
@marceloverdijk using the `api` scope for the platform is not required. You can use `compile` or `implementation` as well. I'll add this to the docs to make it clear. You also don't need to use the `java-platform` plugin because you are only consuming the BOM, and not producing one.

**Comment by marceloverdijk** [comment]
Indeed. So probably docs could best mention `implementation`, as `api` in most cases doesn't make send or either won't work.

**Comment by paulbakker** [comment]
Fixed in this PR https://github.com/Netflix/dgs/pull/32
