### ISSUE TITLE
Is WebFlux supported?

### ISSUE THREAD

**Issue by konstantinblaesi** [Netflix/dgs-framework#28]

**Comment by paulbakker** [comment]
Not currently - we are planning to support it at some point though. 

The code that creates the HTTP endpoint is already in a separate module, so the idea is we add another module based on WebFlux.

**Comment by paulbakker** [comment]
@ooga we're planning to pick this up very soon actually. At the very least we will need help with reviews etc. once we have something.

**Comment by paulbakker** [comment]
Created a more descriptive issue for this: https://github.com/Netflix/dgs-framework/issues/143
Will get started on this soon.

I'm closing this issue, the work will be tracked in #143.
