### ISSUE TITLE
bug: WebSocket Subscriptions seem to ignore variables

### ISSUE THREAD

**Issue by MarkPollmann** [Netflix/dgs-framework#283]
## Expected behavior
Subscription should take variables (defined with `$..`, not inlined into the document) into account
## Actual behavior
Queries with variables work fine.

Subscriptions with inlined inputs work fine.

Subscriptions with variables seem to ignore those variables. 

## Steps to reproduce

This is what we get. Variable machineId is defined but seem to get ignored:

![Screenshot 2021-04-21 at 14 25 15](https://user-images.githubusercontent.com/5286559/115558025-96094380-a2b2-11eb-88ae-d063e704b641.JPG)

I believe the following line in `com.netflix.graphql.dgs.subscriptions.websockets.DgsWebSocketHandler.kt` is the problem:

![Screenshot 2021-04-21 at 14 28 13](https://user-images.githubusercontent.com/5286559/115553571-d6b28e00-a2ad-11eb-89fc-9e19dfe9634a.JPG)

Should it take a second parameter like so: 
`val executionResult: ExecutionResult = dgsQueryExecutor.execute(payload.query, payload.variables)`?

Unfortunately I can't build a reproducible case right now but if it is needed, let me know.

**Comment by derSchtefan** [comment]
We run into the same problem.

**Comment by srinivasankavitha** [comment]
Thanks for reporting, we will look into this soon.

**Comment by UglyHobbitFeet** [comment]
Yep, we're also seeing the same issue. Looking forward to this being patched!

**Comment by srinivasankavitha** [comment]
This issue is now fixed and will be available in the next release. Closing this.
