### ISSUE TITLE
documentation: typeMapping definition has no effect if type name and class name are the same

### ISSUE THREAD

**Issue by fhaertig** [Netflix/dgs-framework#310]
## What are you missing in the docs

My config of the generateJava task looks like this since I only want code generation for GQL client and use my own API classes in fetchers:

`generateJava {
    schemaPaths = ["${projectDir}/src/main/resources/schema"]
    packageName = 'my.company.package' 
    generateClient = true
    generateDataTypes = false
    typeMapping = [
        "Foobar": "my.company.package.FoobarResult",
        "FoobarInput": "my.company.package.FoobarInput"
    ]
}`

This works - but I realized that the second type mapping has actually no effect because DGS somehow figures this out from the method signature in my DgsFetcher if the schema type and the java class have the same name . if they don't, the mapping definition for **query result classes/types** has actually no effect!

Would be nice to add a hint that we only need a type mapping if the names don't match

**Comment by paulbakker** [comment]
I'm not really understanding the issue you're describing. The type mapping is for codegen only, the framework doesn't have any knowledge about it.

**Comment by fhaertig** [comment]
I can image it is a bit confusing... I'm basically referring to this section: 

> When you have existing classes that you want to use instead of generating a class for a certain type, you can configure the plugin to do so using a typeMapping. The typeMapping configuration is a Map where each key is a GraphQL type and each value is a fully qualified Java/Kotlin type.

_https://netflix.github.io/dgs/generating-code-from-schema/#mapping-existing-types_

Applied to my example - the following is actually needed if my gql type/java type are not equally named:
`typeMapping = [ "Foobar": "my.company.package.FoobarResult" ]`

but the following actually is not needed, because it "magically" recognized the class name: 
`typeMapping = [ "FoobarInput": "my.company.package.FoobarInput" ]`

We ran into an issue where changing the typeMapping had no effect and this was our realization.

**Comment by paulbakker** [comment]
I think this was a side effect of a bug fixed in: https://github.com/Netflix/dgs-codegen/pull/183
