### ISSUE TITLE
bug: Bad serialization of Extended Scalar types (ie. JSON)

### ISSUE THREAD

**Issue by federico-s** [Netflix/dgs-framework#317]
## Expected behavior
I'm using the JSON extended scalar in my entity and I wrote a mutation to add the entity. 
Schema:
```
type Document {
    uuid: String!
    publishDate: DateTime
    content: String
    properties: JSON
}

type Mutation {
    addDocument(input: AddDocumentInput): Document
}

input AddDocumentInput {
    publishDate: DateTime!,
    content: String,
    properties: JSON!
}
```
I expect that calling this mutation using the dgs-client will work and produce the same output as the GraphiQL console.

The (working) query received from the GraphiQL console is the following:
`c.n.graphql.dgs.mvc.DgsRestController    : Reading input value: '{"query":"mutation {\n  addDocument(input: {\n    properties: {\n      customerId: \"0000121\"\n    }\n      publishDate: \"2021-05-06T09:20:51+02:00\"\n  }) {\n    uuid\n    properties\n  }\n}","variables":null}'
`

## Actual behavior
Executing the mutation with the dgs-client prompts the following error in the server:
`java.lang.IllegalArgumentException: Cannot construct instance of java.util.LinkedHashMap (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{customerId=0000121}')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: it.federicos.searchdocument.model.AddDocumentInput["properties"])
`

The query reiceved from the dgs-client is the following:
`c.n.graphql.dgs.mvc.DgsRestController    : Reading input value: '{"query":"mutation {addDocument(input: {publishDate:\"2021-05-06T18:36:51.706+02:00\",content:null,properties:\"{customerId=0000121}\"}){ uuid  properties } }","variables":{},"operationName":null}'
`

As you can see, there's difference between the `properties` field serialization.

## Steps to reproduce
Client method that invokes the mutation:
```
public Document addDocument(AddDocumentInput addDocumentInput) {

        GraphQLQueryRequest graphQLQueryRequest = new GraphQLQueryRequest(
                new AddDocumentGraphQLQuery.Builder()
                    .input(addDocumentInput)
                    .build(),
                new AddDocumentProjectionRoot()
                        .uuid()
                        .publishDate()
                        .content()
                        .properties()
        );

        String query = graphQLQueryRequest.serialize();
        GraphQLResponse response = graphQLClient.executeQuery(query, new HashMap<>(), graphQLRequestExecutor);

        return response.extractValueAsObject("addDocument", Document.class);
    }
```
Model (generated with the codegen plugin):
```
public class AddDocumentInput {
  
  private OffsetDateTime publishDate;

  private String content;

  private Map properties;

  // contructor, getters, setters, ....
}
```

**Comment by berngp** [comment]
This behavior depend on...

1. How you generate your client, and how you map the scalars/types, in this case let's say JSON and DateTime. For example, using Gradle Kotlin you will have something like:
```
tasks.withType<com.netflix.graphql.dgs.codegen.gradle.GenerateJavaTask> {
    generateClient = true
    packageName = "com.example.demo.generated"
    typeMapping = mutableMapOf(
        "DateTime" to "java.time.OffsetDateTime",
        "JSON" to "java.util.Map"
    )
}
```

2. You register the scalars in the server so it knows how to serialize/deserialize the request and response. More info [here](https://netflix.github.io/dgs/scalars/).
