### ISSUE TITLE
`4.0.0` platform not published on Maven Central?

### ISSUE THREAD

**Issue by marceloverdijk** [Netflix/dgs-framework#354]
Maven Central does not seem to have the `4.0.0` release, and as that was released yesterday it should be synced by now.
As there were similar issues for codegen artifacts not published in the past I'm raising the issue for the framework here.

**Comment by berngp** [comment]
Looking into it.

**Comment by berngp** [comment]
Looks like Maven Central had a hiccup. I do see the artifacts now.
https://repo1.maven.org/maven2/com/netflix/graphql/dgs/graphql-dgs-extended-scalars/

**Comment by marceloverdijk** [comment]
OK I can see this:

![image](https://user-images.githubusercontent.com/197004/119200707-bda82300-ba8d-11eb-8020-8c417970273e.png)

but platform only has:

![image](https://user-images.githubusercontent.com/197004/119200749-d6183d80-ba8d-11eb-9cb4-dbeb1dd10347.png)


Maybe no new platform release was done yet?

**Comment by berngp** [comment]
@marceloverdijk , I think its a UI issue since the artifacts are available https://repo1.maven.org/maven2/com/netflix/graphql/dgs/graphql-dgs-platform/4.0.0/

**Comment by marceloverdijk** [comment]
Yes you are right, I can resolve the dependency! 
Weird thing is initially I updated the dependency version in my build file but it was not working; thats why I checked the Maven Central GUI and noticed it seemed not to be there.
As I can resolve the artifacts now, closing the issue.
Thx!
