### ISSUE TITLE
Provide an easy way to access the input arguments on the query in child data fetchers.

### ISSUE THREAD

**Issue by srinivasankavitha** [Netflix/dgs-framework#36]
Currently, we can access this information via this:
```
// This gives you the first field that was selected on the query
Field result = (Field)(dfe.getOperationDefinition().getSelectionSet().getSelections().get(0));
// This gives you the first argument's value and so on
result.getArguments().get(0).getValue();
```
We could either enhance the DgsDataFetchingEnvironment or add @RootInputArgument annotation to easily access this.

**Comment by paulbakker** [comment]
We had some discussion about this and aren't sure about how useful this feature is.
The example given in https://github.com/Netflix/dgs-framework/discussions/23 was the following: 

```
type Query {
    getContact (customerId: ID!): Contact
}

type Contact {
    email: String
    address: [Address]
}

type Address {
    street: String!
    number: String!
    additional: String
    pincode: String!
    city: String!
    country: String!
}
```

In this example, it _would_ be useful to easily access the `customerId` in a datafetcher for address, hence the idea to introduce something like `@RootInputArgument`. Note however that we could already pass this kind of context to child data fetchers in different ways, either by adding a field on (in this example) `Contact`, or by using `localContext`. Different ways of handling are described here: https://netflix.github.io/dgs/advanced/context-passing/

An argument can be made that a `RootInputArgument` annotation is easier to use than `localContext`. However, the scenario is very specific. Take a slightly different scenario where the argument is a list of customerIds.

```
type Query {
    getContact (customerIds: [ID!]): Contact
}
```

In an address datafetcher, we would need the specific customerId of the customer we are resolving the address for. The `@RootInputArgument` just gives the list and would be useless.
This makes it questionable how often the pattern would actually be used. 

The downside of adding annotations for not-so-common use cases is that in the end, we would end up with an API similar to DataFetchingEnvironment itself, but in annotations, which would just be confusing.

We decided to defer this feature until we have a more clear idea of it's usefulness.
**If you have a strong use case for this feature, please comment and explain the scenario!**
