### ISSUE TITLE
How to use  nested query with query template

### ISSUE THREAD

**Issue by dennisit** [Netflix/dgs-framework#365]
Please do not create issues for questions. Use
the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) instead!

query($userId:Int){
    userInfo(id:$userId){
        age
        name
        itemId
    }
    itemList(ids: $userinfo.itemId){
        name
        price
    }
}

**Comment by srinivasankavitha** [comment]
@dennisit - were you responding to another question here? It ended up as a new issue :)

**Comment by srinivasankavitha** [comment]
Closing this issue. Please start a discussion if needed.
