### ISSUE TITLE
documentation: Update language for inclusivity

### ISSUE THREAD

**Issue by nephyst** [Netflix/dgs-framework#373]
There are at least three locations where documentation includes non-inclusive terms:
https://github.com/Netflix/dgs-framework/search?q=whitelist

Inclusive language is a standard required by the code of conduct:
https://github.com/Netflix/dgs-framework/blob/master/CODE_OF_CONDUCT.md

**Comment by srinivasankavitha** [comment]
Sorry about this. Thanks for pointing this out. Will fix this issue asap.

**Comment by srinivasankavitha** [comment]
Fixed and merged PR #378.
