### ISSUE TITLE
feature: Integration with WebFlux ReactiveSecurityContextHolder

### ISSUE THREAD

**Issue by driverpt** [Netflix/dgs-framework#375]
## Describe the Feature Request
Currently we are trying to access `ReactiveSecurityContextHolder` to fetch the Principal, since we are dependant on Roles to show the proper Data.

e.g.:
```
  @DgsQuery(field = "stuffByFilter")
  public CompletionStage<List<Stuff>> leaves(@InputArgument("filter") final StuffFilter filter) {
    return ReactiveSecurityContextHolder.getContext()
      .map(SecurityContext::getAuthentication)
      .map(Authentication::getPrincipal)
      .map(Object::toString)
      .doOnNext(log::info)
      .flatMapMany(principal -> randomStuff())
      .collectList()
      .toFuture();
  }
```
The above code returns empty list as no logging is generated and no breakpoints are hit.

## Describe Preferred Solution
Ideally we could get the current Principal available in the WebFlux Call chain via `ReactiveSecurityContextHolder`

**Comment by driverpt** [comment]
Please let me know if i'm doing something wrong

**Comment by hantsy** [comment]
Make sure you have set the authentication in the Security Context(by Spring Secuirty filter or manually) before fetching it.

**Comment by AlexRiedler** [comment]
I have tested with having a seperate controller, and a DgsData with PreAuthorize annotation, it appears that DGS is losing the ReactiveSecurityContext somehow during the transition. Not sure exactly where yet, but this is probably something much needed for a lot of people.

**Comment by AlexRiedler** [comment]
Okay, after messing around inside dgs-framework, I think I have a path forward but would love input from the maintainers.

I modified DataFetcherResultProcessor:

```kt
 interface DataFetcherResultProcessor {
     fun supportsType(originalResult: Any): Boolean
     fun process(originalResult: Any, dfe: DataFetchingEnvironment): Any
 }
```

this is a relatively trivial change, allowing access to the dfe (or potential we should allow access to DgsDataFetchingEnvironment instead) inside of Mono/FluxDataFetcherResultProcessors.

I then had to implement my own custom Mono/Flux implementation converters since spring-security is not included in these modules.

```kt
class MonoDataFetcherResultProcessor : DataFetcherResultProcessor {
    override fun supportsType(originalResult: Any): Boolean {
        return originalResult is Mono<*>
    }

    override fun process(originalResult: Any, dfe: DataFetchingEnvironment): Any {
        if (originalResult is Mono<*>) {
            val context = ReactiveSecurityContextHolder.withAuthentication((dfe.getContext<DgsContext>().customContext as SecurityContext).authentication)
            return originalResult.contextWrite(context).toFuture()
        } else {
            throw IllegalArgumentException("Instance passed to ${this::class.qualifiedName} was not a Mono<*>. It was a ${originalResult::class.qualifiedName} instead")
        }
    }
}
```

noting that my customContext is:

```kt
@Component
class SecurityContextDgs : DgsReactiveCustomContextBuilderWithRequest<SecurityContext> {
    override fun build(
        extensions: Map<String, Any>?,
        headers: HttpHeaders?,
        serverRequest: ServerRequest?
    ): Mono<SecurityContext> {
        return ReactiveSecurityContextHolder.getContext()
    }
}
```


This could probably be improved in some way, but it does work e2e for me on my fork + custom implementations.

What are peoples thoughts and suggestions?

**Comment by cnolte** [comment]
How do you use the MonoDataFetcherResultProcessor class? Is it a @Component?

**Comment by AlexRiedler** [comment]
@cnolte they are Beans on my security configuration class, much like DgsWebFluxAutoConfiguration ones in graphql-dgs-spring-webflux-autoconfigure (which I commented out for my testing).

**Comment by paulbakker** [comment]
The PR from @AlexRiedler has been merged. Is there more that needs to happen for this issue to be completed?

**Comment by asavov** [comment]
As of today, using latest DGS (4.9.17), I'm **not** able to access `ReactiveSecurityContextHolder` from within `@DgsQuery` annotated `@DgsComponent` method.

    @DgsQuery(field = "regions")
    Mono<List<Region>> queryRegions() {

        return ReactiveSecurityContextHolder.getContext()
                .flatMap(securityContext -> {
                    log.info("[NEVER been logged] securityContext: {}", securityContext);
                    return regionsCall(securityContext);
                });
    }

Manually configured `AuthenticationWebFilter` is setting `SecurityContextImpl` by AuthenticationWebFilter#onAuthenticationSuccess.

Is there anything that should be done in advance to have access to `SecurityContext` through `ReactiveSecurityContextHolder`?
Thanks.

**Comment by denniseffing** [comment]
@AlexRiedler Is there any reason why the `MonoDataFetcherResultProcessor` and `SecurityContextDgs` are not merged as well? Your solution works flawlessly, so thank you very much! Not sure if there's a better solution but atleast it works.

@paulbakker As far as I understand to close this issue the classes mentioned above should be merged and configured in the correct DGS auto configuration classes.

**Comment by gnoeley** [comment]
@AlexRiedler I proposed a more permanent solution to the context issue in the above PR. Given your previous focus on this area would appreciate any feedback you are willing to provide on the approach taken.

@denniseffing would this cover what you had in-mind regarding merging this solution in the framework?

**Comment by denniseffing** [comment]
@gnoeley Yes! We discovered that the existing solution proposed in https://github.com/Netflix/dgs-framework/issues/375#issuecomment-864326805 has another issue though: It works for `@DgsQuery` but *does not* work for `@DgsEntityFetcher` when using federation. Would it be possible to consider this in your current PR so that it works for `@DgsEntityFetcher` as well?

**Comment by gnoeley** [comment]
We aren't currently using the federated functionality so I wouldn't be confident introducing the change in this PR... but it would probably be possible to use the `ReactiveDgsContext` it introduces here [is Mono<*> -> result.toFuture()](https://github.com/Netflix/dgs-framework/blob/0bd898e241f73a9d024be94105286aef2013d7e4/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/federation/DefaultDgsFederationResolver.kt#L104) in a future change to achieve that?

**Comment by berngp** [comment]
Latest 4.x and 5.x should address this issue. Don't hesitate to let us know if you run into issues.

**Comment by berngp** [comment]
Thanks @gnoeley for the help.

**Comment by denniseffing** [comment]
@berngp The issue seems fixed for data fetchers but not for entity fetchers. Are we doing something wrong or are you confident that the issue is fixed for entity fetchers as well?

**Comment by hwhh** [comment]
I've just be following this thread and was wondering if it is possible to obtain the SecurityContext from using a datafetcher within a SchemaDirectiveWiring. 

When debugging the code, I can see within the `reactorContext` there is a `SecurityContext` key/value, but I don't know how to access it/retrieve it properly. I've tired accessing it using the `ReactiveSecurityContextHolder`, too but to no avail. 

Currently, my code looks as follows:

```
DataFetcher<?> authDataFetcher = DataFetcherFactories
                .wrapDataFetcher(originalFetcher, ((dataFetchingEnvironment, value) -> {
                    ReactiveDgsContext context = ReactiveDgsContext.from(dataFetchingEnvironment);
                    if(context != null){
                        ContextView reactiveContext = context.getReactorContext();
                    }
```

Any help would be much appreciated!

<img width="1332" alt="image" src="https://github.com/Netflix/dgs-framework/assets/17745809/6b6ad84d-9114-4007-8bfd-b80d3e51ef6f">

**Comment by libvirgo** [comment]
> I've just be following this thread and was wondering if it is possible to obtain the SecurityContext from using a datafetcher within a SchemaDirectiveWiring.
> 
> When debugging the code, I can see within the `reactorContext` there is a `SecurityContext` key/value, but I don't know how to access it/retrieve it properly. I've tired accessing it using the `ReactiveSecurityContextHolder`, too but to no avail.
> 
> Currently, my code looks as follows:
> 
> ```
> DataFetcher<?> authDataFetcher = DataFetcherFactories
>                 .wrapDataFetcher(originalFetcher, ((dataFetchingEnvironment, value) -> {
>                     ReactiveDgsContext context = ReactiveDgsContext.from(dataFetchingEnvironment);
>                     if(context != null){
>                         ContextView reactiveContext = context.getReactorContext();
>                     }
> ```
> 
> Any help would be much appreciated!
> 
> <img alt="image" width="1259" src="https://user-images.githubusercontent.com/17745809/239657641-60884d87-2c9d-400c-a58a-0bc93b137bd9.png">

I try to use follow code to get SecurityContextImpl.

```kotlin
// ctx is ReactorContext
val securityContext = ctx.get<Mono<SecurityContextImpl>>(SecurityContext::class.java).block()
```
![image](https://github.com/Netflix/dgs-framework/assets/35420870/a2099ffc-589f-40bd-b95c-63ea4b7cf2e1)
