### ISSUE TITLE
feature: allow for returning Mono/Flux within dataFetchers/mutations.

### ISSUE THREAD

**Issue by ruseinov** [Netflix/dgs-framework#376]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue. Also consider discussing your idea on
the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) first.

## Describe the Feature Request
Currently when one returns a Mono/Flux within, for example, a DataFetcher - that results in a `null`. 
There are more details here: https://github.com/Netflix/dgs-examples-webflux/issues/5 and a workaround that involves converting `Mono/Flux` to a `CompletableFuture`. 

One of the use-cases for this is DGS + Webflux + ReactiveMongoTemplate integration. At the moment that requires extra effort/boilerplate and I am guessing a slight overhead, because the CompletableFuture returned by the Datafetchers is then converted back to Mono. 
It also makes using reactive Mongo with DGS + Webflux a bit confusing, because when using Spring MVC you can use Mongo/Flux as return types for your endpoints and in DGS it results in an error. 

## Describe Preferred Solution
Allow for returning a `Mono/Flux` within Mutations/Datafetchers/Subscriptions and automatically convert those to Entities/Lists of entities. 

## Describe Alternatives
Could be seen in https://github.com/Netflix/dgs-examples-webflux/issues/5 , basically converting reactor stuff to CompletableFutures.

**Comment by driverpt** [comment]
+1

**Comment by paulbakker** [comment]
This obviously makes sense to support. The one problem is that `graphql-java` doesn't support Flux/Mono, so internally everything still has to be `CompletableFuture`. 

I've added some code that basically does the conversion automatically. I think that would work well, but please test it out.

https://github.com/Netflix/dgs-framework/pull/389

**Comment by paulbakker** [comment]
This was released in: https://github.com/Netflix/dgs-framework/releases/tag/v4.2.0

**Comment by ruseinov** [comment]
Thanks a lot!
