### ISSUE TITLE
feature: Simplify exception handling 

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#402]
Currently, when handling exceptions, according to the docs, we have to define a custom `DataFetcherExceptionHandler`.

For custom exceptions declared in the application, it is not flexible enough.

Hope to add an annotation to simplify the exception handling.

eg. 

```java
@DgsError(errorType="NOT_FOUND", xxxx)
public class AuthorNotFoundException extends RuntimeException {
    public AuthorNotFoundException(String id) {
        super("Author: " + id + " was not found.");
    }
}
```

Or provide a generic interface for developers.

```java
public class AuthorNotFoundException extends DgsException {
    public AuthorNotFoundException(String id) {
        super("NOT_FOUND",  "Author: " + id + " was not found.");
    }
}
```

Let's DgsFramework to scan and handle the exceptions at runtime.

**Comment by paulbakker** [comment]
How is the behavior of such exceptions different from normal exceptions? Is it about setting the `errorType`?

**Comment by hantsy** [comment]
Yes, set up an `errorType` and other possible attributes. Quarkus/MP GraphQL provides such a simple way to handle exceptions.

**Comment by paulbakker** [comment]
This can now be done with `@ControllerAdvice` which comes from Spring GraphQL integration. https://docs.spring.io/spring-graphql/reference/controllers.html#controllers.exception-handler
