### ISSUE TITLE
feature: Add a built-in Bean Validation exception handler

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#403]
Currently, when application bean validation annotations on input type and DataFectchers method arguments, the application will report an `Internally` error type with no detailed validation messages.

Of course, add an `ExceptionHandler` can overcome this temporarily. 

But still, hope there is an official exception handler to do this. 

1. set the error type to `BAD_REQUEST` or `UNPROCESSABLE_ENTITY`.
2. add validation messages to the `extensions` part.

**Comment by paulbakker** [comment]
Closing this issue, this has been supported for a long time through the validation module. E.g. see tests: graphql-dgs-extended-validation/src/test/kotlin/com/netflix/graphql/dgs/autoconfig/DgsExtendedValidationAutoConfigurationTests.kt
