### ISSUE TITLE
bug:  Error: dependent service is not initialized

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#404]
I followed the guide and try to add a lambda DataLoader in a  `@DgsComponent` .

```java
@DgsDataLoader(name = "authorsLoader")
 public BatchLoader<String, Author> authorBatchLoader = keys ->
            CompletableFuture.supplyAsync(() ->
                    this.authorService.getAuthorByIdIn(keys)
            );
```

And when running the application, got the error `authorService` is not initialized.

The `authorService` is injected by the constructor.

**Comment by hantsy** [comment]
Hope the `BatchLoader` can be defined as a `Bean` method with the annotation `DgsDataLoader` if it is required in the Dgs framework.

**Comment by berngp** [comment]
@hantsy you can define a _bean_ annotated with `@DgsDataLoader`, an example of this will be the [ExampleLoaderWithContext] where the bean is defined in the `Configuration` defined in [MultiDataLoaderInstrumentationProvidersProviderTest].
You can also define a `@DgsComponent`, that is a _bean_, that defines a method annotated with `@DgsDataLoader`, an example of this are the _data loaders_ defined in the  [MicrometerServletSmokeTest].


The example you post doesn't provide the context on how the `authorService` is injected, how you are defining the _bean_ that will provide the _data loader_ such reference. Most likely the part that is problematic here is how you are defining the bean.


[ExampleLoaderWithContext]: https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-example-shared/src/main/java/com/netflix/graphql/dgs/example/shared/dataLoader/ExampleLoaderWithContext.java#L33
[MultiDataLoaderInstrumentationProvidersProviderTest]: https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/test/kotlin/com/netflix/graphql/dgs/internal/MultiDataLoaderInstrumentationProvidersProviderTest.kt#L88
[MicrometerServletSmokeTest]:https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-boot-micrometer/src/test/kotlin/com/netflix/graphql/dgs/metrics/micrometer/MicrometerServletSmokeTest.kt#L692

**Comment by hantsy** [comment]
`DgsDataLoader` only accepts `TYPE` and `Field` as the target, can not apply on method.

My issue is when defining it via a lambda, it can not invoke the injected `authorService` in this `@DgsComponent`.

The complete codes is here.
https://github.com/hantsy/spring-graphql-sample/blob/master/dgs-codegen/src/main/java/com/example/demo/gql/PostsDataFetcher.java#L46-L50 , this does not work, I use a standalone DataLoader instead.

**Comment by paulbakker** [comment]
Defining data loaders as lamdas sits outside the scope of dependency injection. I don't think there's much we can do about that. 

Because it's easy to create data loaders as beans, there is a good alternative, so I think we should close this issue as "won't fix".

**Comment by hantsy** [comment]
@paulbakker  As `@DgsData`, I think it is better to add a `METHOD` taraget to the existing `@DgsDataLoader`.
