### ISSUE TITLE
Getting KotlinReflectionInternalError: Unresolved class: error while serializing UUID in GraphQLQueryRequest object

### ISSUE THREAD

**Issue by marepab** [Netflix/dgs-framework#416]
### Discussed in https://github.com/Netflix/dgs-framework/discussions/406

<div type='discussions-op-text'>

<sup>Originally posted by **marepab** June 15, 2021</sup>
Hi Team, 
I created a GraphQLQueryRequest. Added values for required  and trying to execute below as part of Junits.
Please note that there is a UUID property in my input object. However I am getting below error when running test cases at serialize method of InputValueSerializer
When I have other properties like int, strings etc I get no issues.
I am using : graphql-dgs-client:4.1.0 jar
there were no issues when i used graphql-dgs-client:3.10.2 jar.

```
MyInput myInput =
        new MyInput.Builder().someUUID(UUID.randomUUID()).build();
    GraphQLQueryRequest request =
        new GraphQLQueryRequest(
            new MyInputGraphQLQuery.Builder().myInput(myInput).build());
    ExecutionResult response = dgsQueryExecutor.execute(request.serialize());
```
**kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: class java.lang.System$2**
	at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:319)
	at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:43)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:53)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:44)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:179)
	at kotlin.reflect.jvm.internal.KClassImpl.isCompanion(KClassImpl.kt:280)
	at com.netflix.graphql.dgs.client.codegen.InputValueSerializer.serialize(GraphQLQueryRequest.kt:125)
	at com.netflix.graphql.dgs.client.codegen.InputValueSerializer.serialize(GraphQLQueryRequest.kt:126)
	at com.netflix.graphql.dgs.client.codegen.GraphQLQueryRequest.serialize(GraphQLQueryRequest.kt:51)
	at 

</div>

**Comment by hantsy** [comment]
Do you add a custom UUID scalar type ?  eg. https://github.com/hantsy/spring-graphql-sample/blob/master/dgs-codegen/src/main/java/com/example/demo/gql/UUIDScalar.java

**Comment by marepab** [comment]
Yes and we are doing Runtime Wiring for custom scalar

**Comment by hantsy** [comment]
When using the client API, I think it should get the same result in the GraphiQL UI. The serialization and deserialization are dependent on Jackson.

You can try to return a String type of the execution result, and use json path to read the result. The String type result  should be a JSON String.

**Comment by marepab** [comment]
You mean hard coding the query something like this....?

```
   String query =
        "mutation{"
            + "addEmployee(employee:{"
            + "	empUUID: \"42e312ed-675e-45da-8a5e-0b81b9656a17\","
            + "	countryCode: \"IN\"})"
            + "}";
    String response = dgsQueryExecutor.executeAndExtractJsonPath(query, "data.addEmployee");
```

Hard coding query this way is working fine, however this is not maintainable. GraphQLQueryRequest and serialising is more convenient.

**Comment by paulbakker** [comment]
Because UUID is a scalar, you need to create the `GraphQLRequest` with that scalar in the setup. We described this in the release notes when this was added (https://github.com/Netflix/dgs-framework/releases/tag/v4.0.0) but I think we failed to actually put it in the docs. I'll fix that.

This test shows that the mechanic works, and that's how you use it. Notice the `Map` passed in mapping a Java type to a Scalar implementation. 

```
@Test
    fun `serialize with UUID scalar - #416`() {
        val randomUUID = UUID.randomUUID()
        val query = TestNamedGraphQLQuery().apply {
            input["id"] = randomUUID
        }

        val request =
            GraphQLQueryRequest(query, MovieProjection(), mapOf(UUID::class.java to UUIDScalar))

        val result = request.serialize()
        assertThat(result).isEqualTo("query TestNamedQuery {test(id: \"$randomUUID\") }")
    }

    object UUIDScalar : Coercing<UUID, String> {
        override fun serialize(uuid: Any): String {
            return uuid.toString()
        }

        override fun parseValue(input: Any): UUID {
            return UUID.fromString(input.toString())
        }

        override fun parseLiteral(input: Any): UUID {
            return UUID.fromString(input.toString())
        }
    }
```

**Comment by paulbakker** [comment]
New docs: https://netflix.github.io/dgs/advanced/java-client/#scalars-in-dgs-client
