### ISSUE TITLE
feature: Add @DgsDirective to simplify the directive declaration

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#419]
I followed the steps of the discussion posts and tried to add a simple uppercase directive in my sample project, but it does not work as expected.

The uppercase directive wring class.

```java
public class UppercaseDirectiveWiring implements SchemaDirectiveWiring {
    @Override
    public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> env) {

        var field = env.getElement();
        var parentType = env.getFieldsContainer();

        var originalDataFetcher = env.getCodeRegistry().getDataFetcher(parentType, field);
        var dataFetcher = DataFetcherFactories.wrapDataFetcher(originalDataFetcher,
                (dataFetchingEnvironment, value) -> {
                    if (value instanceof String s) {
                        return s.toUpperCase();
                    }
                    return value;
                }
        );

        env.getCodeRegistry().dataFetcher(parentType, field, dataFetcher);
        return field;
    }
}
```

And I created a bean `@DgsRuntimeWiring` in the data fetchers.  The complete codes is here: https://github.com/hantsy/spring-graphql-sample/blob/master/dgs-codegen/src/main/java/com/example/demo/gql/PostsDataFetcher.java#L24

```java
@DgsComponent
public class PostsDataFetcher {

    @DgsRuntimeWiring
    RuntimeWiring.Builder runtimeWiring(RuntimeWiring.Builder builder) {
        return builder.directive("uppercase", new UppercaseDirectiveWiring());
    }
```

The partial content of the schema file:

```gql
directive @uppercase on FIELD_DEFINITION

scalar LocalDateTime
scalar UUID

type Post{
    id: ID!
    title: String! @uppercase
    content: String
    comments: [Comment]
    status: PostStatus
    createdAt: LocalDateTime
    authorId:String
    author:Author
}
```

When running the application, and test it on Graphiql, but it does not work. Not sure where is wrong.

This directive is working with my other Graphql example written in GraphQL Java and Spring Graphql.

Check: https://github.com/hantsy/spring-graphql-sample/tree/master/graphql-java/src/main/java/com/example/demo/gql/directives

## Expected behavior

Similar to the existing `@DgsScalar`, I hope to add a `@DgsDirective` and apply it on the user's `SchemaDirectiveWiring` class directly to simplify the registration of a directive. eg. 

```java
@DgsDirective(name="uppercase")
public class UppercaseDirectiveWiring implements SchemaDirectiveWiring {}
```

**Comment by ankit-joinwal** [comment]
Try to make your UppercaseDirectiveWiring a Spring Component by adding @Component and see if it works.

**Comment by hantsy** [comment]
@ankit-joinwal  Check [UppercaseDirectWiring](https://github.com/hantsy/spring-graphql-sample/blob/master/dgs-codegen/src/main/java/com/example/demo/gql/directives/UppercaseDirectiveWiring.java) and [CustomRuntimeWiring](https://github.com/hantsy/spring-graphql-sample/blob/master/dgs-codegen/src/main/java/com/example/demo/gql/CustomRuntimeWiring.java), got the same result, no effect on response data.

**Comment by WtfJoke** [comment]
@hantsy I checked out your project and found the problem in your setup.
If you make your runtimewiring method public its working (also you need to remove the second param of the method annotated with `DgsRuntimeWiring`.

Here the full code of CustomRuntimeWiring:
```java
@DgsComponent
public class CustomRuntimeWiring {

    private final UppercaseDirectiveWiring uppercaseDirectiveWiring;

    public CustomRuntimeWiring(UppercaseDirectiveWiring uppercaseDirectiveWiring){
        this.uppercaseDirectiveWiring = uppercaseDirectiveWiring;
    }

    @DgsRuntimeWiring
    public RuntimeWiring.Builder customRuntimeWiring(RuntimeWiring.Builder builder) {
        return builder.directive("uppercase", uppercaseDirectiveWiring);
    }
}
```
