### ISSUE TITLE
bug: Generating client queries/mutations from nested types only creates top level type

### ISSUE THREAD

**Issue by anderssandven** [Netflix/dgs-framework#420]
### Discussed in https://github.com/Netflix/dgs-framework/discussions/370

<div type='discussions-op-text'>

<sup>Originally posted by **anderssandven** May 28, 2021</sup>
I have a schema like this:
```
type Mutation {
	one: One
}

type One {
	two(three: Three!): Two
}

type Two {
	test: String
}

input Three {
	test3: String
}
```

When doing code generation I expect to get multiple queries generated. The queries generated are:
OneGraphQLQuery.java  
OneProjectionRoot.java  
OneTwoProjection.java

I expect to get a OneTwoGraphlQuery aswell because I cannot supply any arguments through OneGraphqlQuery. 

</div>

**Comment by srinivasankavitha** [comment]
We didn't support subqueries earlier. This PR fixes that issue: https://github.com/Netflix/dgs-framework/pull/415

**Comment by anderssandven** [comment]
Good news. I will close this issue then.
