### ISSUE TITLE
bug: Generated client interfaces does not extend other interfaces 

### ISSUE THREAD

**Issue by anderssandven** [Netflix/dgs-framework#421]
I have a schema like this:

```
interface Error {
   message: String
}

interface SpecializedError implements Error {
   messsage: String
   specializedError: String
}

type ValidationError implements SpecializedError, Error {
   message: String
   specializedError: String
}

type TestPayload {
   errors: [Error!]
   result: ResultType
}

type ResultType {
   success: Boolean!
}
```

## Expected behavior
I want the generated interface SpecializedError to extend Error so that my TestPayload error field can contain both ValidationError and other error types that implement Error directly.

## Actual behavior
Interfaces do not extend other interfaces. However, concrete classes implement multiple interfaces.

If I have some shared code that internally generates SpecializedErrors, it would be nice to use that type even though the payload returns Error. Its very cumbersome to write reusable code in my resolvers when its split up like this.

## Steps to reproduce
Generate code from the schema above and view its output. This is using the Java codegen.

Let me know if I can assist with more information.

**Comment by paulbakker** [comment]
We're lacking support for interfaces implementing interfaces. We have another issue open on this on the codegen project: https://github.com/Netflix/dgs-codegen/issues/181

I'm closing this issue as duplicate, but it will be addressed.
