### ISSUE TITLE
feature: Add Upload support when enabling code gen

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#434]
When Gradle code gen is enabled, and I added `Upload` type in the GraphQl schema like this.

```gql
scalar Upload

type Mutation {
    upload(file: Upload!): Boolean
}
```

The `compileJava` task will be failed due to there is no an `Upload` class in the generated types folder, but it is imported in the generated client query classes. 

```bash 
D:\hantsylabs\spring-graphql-sample\dgs-codegen\build\generated\com\example\demo\gql\client\UploadGraphQLQuery.java:3: error: cannot find symbol
import com.example.demo.gql.types.Upload;
                                 ^
  symbol:   class Upload
  location: package com.example.demo.gql.types
```

The sample codes: https://github.com/hantsy/spring-graphql-sample/tree/master/dgs-codegen

A working example without code gen: https://github.com/hantsy/spring-graphql-sample/tree/master/dgs-fileupload

**Comment by paulbakker** [comment]
As a quick workaround, we usually add `@skipcodegen` to such fields: https://github.com/Netflix/dgs-examples-java/blob/main/src/main/resources/schema/schema.graphqls#L8

However, I'm keeping the issue open because better support should be there.

**Comment by srinivasankavitha** [comment]
You can also add a type mapping in codegen config to explicitly map the Upload scalar to MultipartFile.
https://netflix.github.io/dgs/generating-code-from-schema/#mapping-existing-types

**Comment by hantsy** [comment]
@srinivasankavitha The `typeMapping` is easy to set up, but it works for file upload? I found the fileUpload handling is every special in GraphQL Upload spec.

**Comment by paulbakker** [comment]
You basically just want to map it to `MultipartFile`: https://netflix.github.io/dgs/advanced/file-uploads/
