### ISSUE TITLE
feature: Add Multipart support to GraphQLClient

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#437]
I can not find  an approach to use `GraphQLClient` to send a query which includes a `Upload`. 
or let me know how to do it?

**Comment by paulbakker** [comment]
Example: https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-example-java/src/test/java/FileUploadMutationTest.java

Also, for questions, please create a question on the discussion forum instead of creating an issue.

**Comment by hantsy** [comment]
@paulbakker I mean  [Java GraphQL Client](https://netflix.github.io/dgs/advanced/java-client/) not `DgsQueryExecutor `.

**Comment by hantsy** [comment]
@paulbakker And I browsed the codes of `DgsQueryExecutor`, it delegates the query execution to the  `GrapQL` directly, not via `GraphQLClient`.
