### ISSUE TITLE
feature: Add Subscription support to GraphQLClient

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#438]
Currently, it is easy to handle general queries, but how to subscribe to a  `Subscription` with the `GraphQLClient`?

**Comment by hantsy** [comment]
I mean  [Java GraphQL Client](https://netflix.github.io/dgs/advanced/java-client/) not `DgsQueryExecutor `.

**Comment by srinivasankavitha** [comment]
Thanks for creating the issue. We will add it to our backlog.

**Comment by paulbakker** [comment]
Merged in #522
