### ISSUE TITLE
bug: Compile failure when shortProjectionNames is enabled

### ISSUE THREAD

**Issue by n614cd** [Netflix/dgs-framework#445]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior. 
Generates valid Java

## Actual behavior
Generates compile failure on two classes : Project_RequirementProjection and Project_RequirementsProjection

## Steps to reproduce
Using the Gitlab GraphQL schema (downloaded the schema vi graphql-cli), as the schema source. 
I used the following generateJava section in Gradle build script:
generateJava{
  schemaPaths = ["${projectDir}/src/main/resources/gitlab/schema.graphql"]
  packageName = "xxx.yyy.zzz" 
  generateClient = true
  generateDataTypes = false
  includeQueries = ["project"]
  includeMutations = [""]
  //shortProjectionNames = true
  maxProjectionDepth = 2    
}
[schema.zip](https://github.com/Netflix/dgs-framework/files/6720241/schema.zip)

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by srinivasankavitha** [comment]
Thanks for reporting. We actually dropped support for this feature because it is hard to address all scenarios such as the one you pointed out. We will be removing this option as well.
