### ISSUE TITLE
bug: Subscriptions fail when `variables` is null

### ISSUE THREAD

**Issue by metsfan** [Netflix/dgs-framework#449]
## Expected behavior
The Apollo iOS client will send a `null` value for the `variables` parameter if the subscription has no variables. However the subscription query params parser in DGS fails if variables is null. 

## Actual behavior
I would expect DGS to be able to handle a null variables array. 

## Steps to reproduce
Create a subscription without any variables

**Comment by srinivasankavitha** [comment]
Thanks for reporting, will fix.

**Comment by metsfan** [comment]
Thank you!

**Comment by srinivasankavitha** [comment]
Fixed and merged in PR linked above.
