### ISSUE TITLE
bug: Subscriptions are not removed on GQL_STOP

### ISSUE THREAD

**Issue by stdevi** [Netflix/dgs-framework#452]
Subscriptions per session are stored in the `subscriptions` map:

https://github.com/Netflix/dgs-framework/blob/0bcd586d41bf54e29dc42f9e7970f7b41ff32f02/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L37

Where a key is a session id and a value is a map of session subscriptions.

At line 75, subscriptions are removed by the **operation id**:

https://github.com/Netflix/dgs-framework/blob/0bcd586d41bf54e29dc42f9e7970f7b41ff32f02/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L72-L75

However, the keys of the `subscriptions` map are **session ids** and not operation ids:
https://github.com/Netflix/dgs-framework/blob/0bcd586d41bf54e29dc42f9e7970f7b41ff32f02/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L99

As a result, the subscription will not be removed on the GQL_STOP message since the `subscriptions` map does not contain the corresponding element by the operation id key.

## Expected behavior

Subscriptions are removed from the `subscriptions` map on the GQL_STOP message.

## Actual behavior

Subscriptions are not removed from the `subscriptions` map on the GQL_STOP message, because it removes not from the inner map of the `subscriptions` map, but from the `subscriptions` itself that stores subscriptions per session.

## Steps to reproduce

1. Create a subscription
2. Send GQL_STOP message
3. Subscription is still in the memory

**Comment by stdevi** [comment]
@srinivasankavitha thanks! In addition, I'd like to highlight that the wrong id is used on subscription complete:

https://github.com/Netflix/dgs-framework/blob/382cb449ed1b00e2b05ae1503384fdcf1bc8692b/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L135 

It should be: `subscriptions[session.id]?.remove(id)`
\
Also, looks like the `cleanupSubscriptionsForSession` function supposes to remove subscriptions from the corresponding map however id does not:

https://github.com/Netflix/dgs-framework/blob/382cb449ed1b00e2b05ae1503384fdcf1bc8692b/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L86-L90

It means that after timeout even if a session is closed, it won't be removed from `subscriptions`. Probably, moving fixed line 79:

https://github.com/Netflix/dgs-framework/blob/382cb449ed1b00e2b05ae1503384fdcf1bc8692b/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L79

to the `cleanupSubscriptionsForSession` function should help.


Another issue with `DgsWebSocketHandler` is that it looks like `subscriptions` supposes to store multiple subscriptions per session. However, at line 99, all session subscriptions are overwritten on every new subscription:

https://github.com/Netflix/dgs-framework/blob/382cb449ed1b00e2b05ae1503384fdcf1bc8692b/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L99

As a result, we can have only 1 subscription per session. I guess, it can be fixed by this code: 
```
subscriptions
    .computeIfAbsent(session.id) { mutableMapOf() }
    .plusAssign(id to s)
```

I can open a PR if needed, but I've seen that you already opened one.

**Comment by srinivasankavitha** [comment]
Thanks for pointing these out. Will fix as part of the same PR!

**Comment by srinivasankavitha** [comment]
Fixed and merged.

**Comment by stdevi** [comment]
Thanks 👍
