### ISSUE TITLE
bug: config dgs.graphql.graphiql.path not working

### ISSUE THREAD

**Issue by brianlschultz1969** [Netflix/dgs-framework#455]
## Expected behavior
Changing the config "dgs.graphql.graphiql.path" should change graphiql endpoint

Changing to something like:
dgs.graphql.graphiql.path: /personalize/graphiql

Should allow access like:
http://localhost:8080/personalize/graphiql/

## Actual behavior
The default config value (/graphiql) is always used
http://localhost:8080/graphiql/

## Steps to reproduce
1. Add config to application.yml: dgs.graphql.graphiql.path: /personalize/graphiql
2. Restart application
3. Open browser - enter url http://localhost:8080/personalize/graphiql/
4. Get a 404 error
5. 
_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by brianlschultz1969** [comment]
Looks like this is related to me using the webflux package - **com.netflix.graphql.dgs:graphql-dgs-webflux-starter**

Looks like the **DgsWebfluxConfigurationProperties** does not contains the graphiql config like the **DgsWebMvcConfigurationProperties** does

**Comment by marcelcastilho** [comment]
It's not working when you configure the WebFlux base path as well: `spring.webflux.base-path: some-path`.

Can we append the path to the configuration as you are doing for the [WebMvc](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-webmvc-autoconfigure/src/main/kotlin/com/netflix/graphql/dgs/webmvc/autoconfigure/GraphiQLConfigurer.kt#L58), or am I missing some important detail?

**Comment by brianlschultz1969** [comment]
I just tried that but it ends up having another side effect.  

The graphiql path now works with new url (i.e. http://localhost:8080/personalize/graphiql/index.html) 

But now the graphiql is trying to call itstelf instead of "graphql" when submitting requests from the graphiql UI and I get 404 not found

Very odd.

**Comment by pj28105** [comment]
Is this issue fixed ?

Not able to access /graphql & /graphiql endpoints.

**Comment by paulbakker** [comment]
Closing as this is not reproducible. Also this is now handled by Spring Graphql. See https://netflix.github.io/dgs/spring-graphql-integration/.
