### ISSUE TITLE
bug: Union type interface is not generated with codegen with generateInterfaces

### ISSUE THREAD

**Issue by catdalfonso** [Netflix/dgs-framework#483]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

DGS generates an interface for a union type.

## Actual behavior

In one of our types, we reference a union type in one of our types, like so:

```
union FizzBuzz = Fizz | Buzz 

type Foo implements Bar {
   fizzBuzz: [FizzBuzz!]!
}
```

This generates the following:
```
public interface IFoo {
  List<IFizzBuzz> getFizzBuzz();
}
```

However, `IFizzBuzz` is not generated, causing errors on build.

Our `build.gradle` looks like the following:
```
generateJava {
    schemaPaths = ["${projectDir}/src/main/resources/schema"]
    packageName = 'com.example.dto'
    generateClient = true
    generateInterfaces = true
    typeMapping = [
            "Locale" : "java.util.Locale",
            "JSON" : "java.util.Map",
            "DateTime" : "java.time.OffsetDateTime",
            "Url" : "java.net.URL"
    ]
}
```

## Steps to reproduce

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by berngp** [comment]
This is a DGS Codegen issue, the repo of such project is https://github.com/Netflix/dgs-codegen
