### ISSUE TITLE
Is it possible to include an @InputArgument and a DgsDataFetchingEnvironment in the same fetcher?

### ISSUE THREAD

**Issue by itsandreramon** [Netflix/dgs-framework#484]
I am currently struggling to get this running:

```kotlin
@DgsQuery
@DgsData(parentType = "Query", field = "headers")
fun optimizeWaypoints(
    @InputArgument directions: DirectionsInput,
    environment: DgsDataFetchingEnvironment,
): Mono<Directions>
```

The [examples](https://netflix.github.io/dgs/datafetching/) only show methods with the single DgsDataFetchingEnvironment argument. Removing the @InputArgument parameter from the method works correctly. I need to read the header from the same request in the method.

The query returns:

```
{
  "data": {
    "optimizeWaypoints": null
  }
}
```

Thanks!

**Comment by itsandreramon** [comment]
The following worked:

```
@DgsQuery
fun optimizeWaypoints(
    @InputArgument directions: DirectionsInput,
    @RequestHeader("authorization") token: String,
): Mono<Directions> {
```

**Comment by paulbakker** [comment]
For future reference, combining `@InputArgument` and `DgsDataFetchingEnvironment` arguments does work. I'm not sure why it didn't in your case.

I do notice that in your original example you have both `@DgsQuery` and `@DgsData`. There should only be one.
