### ISSUE TITLE
GraphQL Java 17.0-beta1 is available

### ISSUE THREAD

**Issue by andimarek** [Netflix/dgs-framework#489]
Hi,

we just released GraphQL Java `17.0-beta1`. See https://github.com/graphql-java/graphql-java/releases/tag/v17.0-beta1 for the release notes.

We did release a beta to get early feedback from projects like DGS. It would be great if you could try it out let us know.

Thanks!

**Comment by andimarek** [comment]
Sorry, the bug label is wrong :-)

**Comment by paulbakker** [comment]
Thanks @andimarek, I'm looking into it!

**Comment by paulbakker** [comment]
@andimarek I've done testing with `17.0-beta1` and it's looking good. This includes experimenting with `spring-graphql`, which is working fine now that it's only using the new `graphQLContext` instead of also setting `context`.

I have no further concerns about `17.0`.
