### ISSUE TITLE
Code Gen should generate example data fetchers for mutations

### ISSUE THREAD

**Issue by la289** [Netflix/dgs-framework#503]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
example resolver/DataLoader for mutations should be generated. I didn't notice anything in the docs specifying that only Query types would be generated. Hopefully this is a bug and not a feature request. 

## Actual behavior
example resolver/DataLoader for mutations are not generated

## Steps to reproduce
Use the code-gen plugin's generateJava task through gradle with a schemaPath defined, `generateClient = true` and a packageName defined.

**Comment by paulbakker** [comment]
We didn't see a lot of use from the generated examples. Is it something that's useful to you? Can you explain how you use it?
That might help shape ideas what to do with this in the future.

We never implemented it for mutations, so it's just a missing feature, but that's fine.

**Comment by la289** [comment]
Ah thanks for clarifying. Sorry that I mis-categorized it as a bug. 

The best use case the way I see it is that by generating the data loaders, we are able to have the actual data loaders inherit from the generated class. This provides compilation time type safety checking since any schema changes that don't have matching data loader changes would fail to compile. 

Let me know your thoughts/if there is another way that we can get this safety check.

Thanks

**Comment by srinivasankavitha** [comment]
We don't plan to actively support generation of data fetchers, this was more of an experimental feature, but we haven't got much sue out of it.
