### ISSUE TITLE
feature: Configuration property to disable DGS

### ISSUE THREAD

**Issue by EugenMayer** [Netflix/dgs-framework#517]
Relates to discussion: https://github.com/Netflix/dgs-framework/discussions/514

When introducing DGS or when running in different profiles, it would be very handy to be able to disable DGS using a property. 

It is not possible to exclude `DgsAutoConfiguration`,`DgsWebMvcAutoConfiguration` using spring.autoconfigure.exclude since this would still include the rest  controller and fail to start due to `DgsWebMvcConfigurationProperties` failing.

It would be helpful to have something like flyway offers with

```
@ConditionalOnProperty(prefix = "spring.flyway", name = "enabled", matchIfMissing = true)
```
on all the required Components. Similar to the existing 

```
@ConditionalOnProperty(name = ["dgs.graphql.graphiql.enabled"], havingValue = "true", matchIfMissing = true)
```

But for the entire DGS framework. Any thoughts why this is a bad idea?

**Comment by Akaame** [comment]
Hello,

> It is not possible to exclude DgsAutoConfiguration,DgsWebMvcAutoConfiguration using spring.autoconfigure.exclude since this would still include the rest controller and fail to start due to DgsWebMvcConfigurationProperties failing.

Can you share a minimal example repo with this happening? For me 
```java
@EnableAutoConfiguration(exclude = {DgsAutoConfiguration.class, DgsWebMvcAutoConfiguration.class})
```

seemed to work.

Regards.

**Comment by EugenMayer** [comment]
Hello @akaame - currently on holidays but will try that ASAP when i'am back. Fairly sure this did not work for us due to the rest controller.

**Comment by EugenMayer** [comment]
I'am not sure how we handle to not implement this right. But testing this

```
@Configuration
@ConditionalOnProperty(name = "company.graphql.disable", havingValue = "true", matchIfMissing = true)
@EnableAutoConfiguration(exclude = {DgsAutoConfiguration.class, DgsWebMvcAutoConfiguration.class})
public class GraphQlDisabler
{
}
```

does work just like intended as you have been suggesting @Akaame - sorry for the nice, it seem to work just fine. Not sure how this happened to fail the first time we implemented this.

IMHO this issue could be closed.

**Comment by paulbakker** [comment]
Closing as suggested :-)
