### ISSUE TITLE
feature: Provide support for Spring's @CookieValue annotation

### ISSUE THREAD

**Issue by iuliiasobolevska** [Netflix/dgs-framework#530]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue. Also consider discussing your idea on
the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) first.

## Describe the Feature Request
Similar to @RequestParam, @RequestHeader and @InputArgument, provide support for Spring's @CookieValue annotation.

Currently, I can get cookie value by following one of the following paths:
1. Writing a ton of boilerplate code:
```
        final DgsWebMvcRequestData requestData =
                (DgsWebMvcRequestData) DgsContext.getRequestData(dfe);
        if (requestData != null && requestData.getWebRequest() != null) {
            final ServletWebRequest webRequest = (ServletWebRequest) requestData.getWebRequest();
            final HttpServletRequest request = webRequest.getRequest();
            final Cookie[] cookies = request.getCookies();
            if (cookies != null) {
                final Cookie myCookieValue =  Arrays.stream(cookies)
                        .filter(cookie -> cookie.getName().equals("cookie-name"))
                        .findFirst()
                        .orElse(null);
            }
        }
```
Pro: I get cookie as a `javax.servlet.http.Cookie` object.
Cons: too much code for getting one cookie, doesn't help with writing unit tests (mocking) either

2. Using `@RequestHeader`
```
@RequestHeader(value = "Cookie", required = false) @Nullable final String cookies)
```
Pro: concise way to get to all cookies as a String
Cons: now I have to figure out how to extract my cookie from the cookies string (either by implementing it myself or by pulling some external library). Either option is not great given that I could just use Servlet functionality. 

## Describe Preferred Solution
Suport:
```
@CookieValue("cookie-name", required = false) @Nullable final String cookieValue)
```

**Comment by paulbakker** [comment]
Implemented in #542 and merged. Thanks for the suggestion @iuliiasobolevska
