### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by umesh-kushwaha** [Netflix/dgs-framework#552]
I am using @connection directive for pagination and generating the classes. v4.5.0 released the @connection. I have added following dependencies in my project .
`implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latest.release"))
	implementation "com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter"`

And code gen plugin

`	id "com.netflix.dgs.codegen" version 'latest.release'
`
Application throwing the error 

Description:

There are problems with the GraphQL Schema:
	 * The field type 'VideoConnection' is not present when resolving type 'Query' [@7:1]
	 * 'Video' [@1:1] tried to use an undeclared directive 'connection'

I am following this page https://github.com/Netflix/dgs-framework/releases/tag/v4.5.0

Let me know if I need to add any other dependencies

**Comment by srinivasankavitha** [comment]
You will need to also add this dependency to use the `@connection` directive: `com.netflix.graphql.dgs:graphql-dgs-pagination:<version>`
In addition, in the schema, you will need to declare the `@connection` directive: `directive @connection on OBJECT`

You can also take a look at the example in the framework project for the usage: https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-example-shared/src/main/resources/schema/schema.graphqls#L30
