### ISSUE TITLE
bug:  `DgsReactiveWebsocketHandler` dose not use the Spring managed ObjectMapper

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#565]
Explored `DgsReactiveWebsocketHandler` from `graphql-dgs-spring-webflux-autoconfigure` module , it defined a  `Jackson2JsonDecoder` and a `Jackson2JsonEncoder` as properties, but used a built-in `ObjectMapper` of the decoder.

**[Expected]**: 

It is better to expose an `ObjectMapper` property  and make it injectable.

**Comment by paulbakker** [comment]
That's by design - we want to control the objectmapper that's used because otherwise unexpected results can happen.
