### ISSUE TITLE
bug: upgrading to 4.6.0 leads to issues with custom scalar types 

### ISSUE THREAD

**Issue by EugenMayer** [Netflix/dgs-framework#578]
upgrading from `4.5.1` to `4.6.0` leads to

```
Specified type 'class java.lang.Long' is invalid. Found java.lang.String instead.com.netflix.graphql.dgs.exceptions.DgsInvalidInputArgumentException: Specified type 'class java.lang.Long' is invalid.
```

Are there any changes in 4.6.0 regarding this? i could not catch anything in the changelogs. 

This error is triggered in a test 

```
    final String query = "query{attachmentRevisions(first:3, offset:0, attachmentId:0){edges{node{id{fileId}}}}}";
    final String path = "data.attachmentRevisions.edges[*].node.id.fileId";
    final List<Long> result = dgsQueryExecutor.executeAndExtractJsonPath(query, path);
```

With the following `graphqls` Quer definition

```
    attachmentRevisions(
        first: Int!, offset: Int!, attachmentId: ID!,
    ): AttachmentRevisionGraphQlViewConnection!
```

Where the `ID!` is a Long.

We are including `com.netflix.graphql.dgs:graphql-dgs-extended-scalars` in our project. And including the `Long` as a scalar using 

```
scalar Long
```

in our `graphqls`.

**Comment by EugenMayer** [comment]
@bergdavidj @paulbakker thank you for clarifying this issue. I understand that GraphQL has a string opinion about ID's being `Strings`, to be honest that is far fetched from common in java-based backend / persistence implementations (at least as being the default way of thinking of IDs).

I liked the more open way to allow IDs to be whatever more then now enforcing me to explicitly cast the ID in every DataFetcher over and over again. But well it is GQL RFC so I guess it is somewhat understandable.

Is there a world / chance where we could discuss if we could implement a converter in DGS, something like

`@InputArgument(cast = "java.lang.Long" String attachmentId)` 

or just something like

`@InputArgument(castTo=DgsCast.toLong String attachmentId)`

`@InputArgument(toInt=DgsCast.toInt String attachmentId)`

where `DgsCast` is an `Enum` - the latter would limit the implementation to specific types so it does not get out of hand. Simple conversions - that's it, not a magic full fledged DGS type caster.

What do you think, should I start a discussion for that or do you just no see a chance for that?

**Comment by berngp** [comment]
I think is worth discussing. I'm not sure if this should be specific to the ID type, but I lean towards it. For other transformations developers would already have the option of using scalars

**Comment by EugenMayer** [comment]
thank you. created https://github.com/Netflix/dgs-framework/discussions/587 as an follow up discussion
