### ISSUE TITLE
JsonPath is bringing in problematic transitive libraries

### ISSUE THREAD

**Issue by bono007** [Netflix/dgs-framework#58]
We are getting ready to use DGS for our Spring Boot applications at my company and I am super excited about what you all have put together - thank you. 

One concern I have is around some of the transitive library baggage that is coming along for the ride in the starter. Namely `json-path`, which itself imposes a messy transitive library chain along with it. 

```java
|    |    |    +--- com.jayway.jsonpath:json-path:2.5.0
|    |    |    |    +--- net.minidev:json-smart:2.3
|    |    |    |    |    \--- net.minidev:accessors-smart:1.2
|    |    |    |    |         \--- org.ow2.asm:asm:5.0.4 -> 9.0
```

## Background

- The [com.jayway.jsonpath:json-path](https://github.com/json-path/JsonPath) lib seems to be the only solid Java based JSONPath implementation so I understand why its used here. It's also used in Spring Boot test modules and in Spring Cloud Contract Verifier modules. 

- Up until [recently](https://github.com/json-path/JsonPath/commit/8ad474399810219f6f2f10433bb977e70f77abfe) it had not seen a release in 3 years. 

- It brings in [json-smart](https://mvnrepository.com/artifact/net.minidev/json-smart) which brings in [accessors-smart](https://mvnrepository.com/artifact/net.minidev/accessors-smart) both of which have not been released on Maven central since 2017. However, each of these do have recent releases on RedHat GA repository. It is hard to tell what the state of the libs are, if they are maintained, etc.

- The `smart-accessors` in turn brings in ancient `asm 5`. 

## Problem 

The last item has caused quite a few issues for consumers of `json-path` as the current state of the world is `asm 9`. Typically version alignment handle this when using Gradle (as above `5.0.4 -> 9.0`) and Maven can be configured to do the same. It still can cause issues though. An example where other frameworks have insulated this detail is in [spring-core](https://github.com/spring-projects/spring-framework/blob/master/spring-core/spring-core.gradle#L7) shading of cglib/asm.

It looks like DSG has done a good job of not exposing JsonPath and its only used internally in `graphql-dgs-client`. This qualifies it as a candidate for shading. It's truly an internal implementation detail that consuming applications should not have to deal with. 

#### Option 1 
I would ❤️  to submit a PR that shades JsonPath-and-company. Thoughts? 

#### Option 2
Exclude the transitive `json-smart` lib and switch JsonPath's [JsonProvider](https://github.com/json-path/JsonPath#jsonprovider-spi) off of `json-smart` and to Jackson instead. 

#### Option 3
Improve JsonPath to hide its internals. However, this is not easy as some of its API exposes JsonSmart I believe. 

#### Option N (theres always more options)

I am willing to submit a PR for whatever approach we land on in this discussion. We are going to be consumers of DGS and as such I would love to contribute.

**Comment by srinivasankavitha** [comment]
Thanks for the detailed description of the issue. We'll discuss this and get back to you this week.

**Comment by bono007** [comment]
I was mistaken about `json-path` not being exposed in the API - `queryExecutor` exposes `com.jayway.jsonpath.DocumentContext`. Therefore **Option 1** is probably not a good choice. I am playing around w/ **Option 2** to see how that would look like in practice.

**Comment by bono007** [comment]
Once I dug further into the DGS code I was pleasantly surprised to see that the JSON provider has already been switched to Jackson in both the [graphql-dgs-client](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-client/src/main/kotlin/com/netflix/graphql/dgs/client/GraphQLResponse.kt#L43) and [graphql-dgs](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsQueryExecutor.kt#L56) modules.

I believe the `net.minidev:json-smart` can simply be excluded from the above modules build.gradle.kts with 

```groovy
api("com.jayway.jsonpath:json-path:2.+") {
	exclude(group = "net.minidev", module = "json-smart")
}
```
and 
```groovy
api("com.jayway.jsonpath:json-path:2.4.+") {
        exclude(group = "net.minidev", module = "json-smart")
}
```

**Comment by paulbakker** [comment]
@bono007 Thanks so much for digging into this. These problems can be tricky to deal with. I think the idea to exclude those transitives is a great one. 

I'll do some testing today to make sure, but this _should_ work!

**Comment by bono007** [comment]
Hi @paulbakker - I am not a fan on commenting on closed issues but I figured it would be a decent avenue to ask a small question relevant to the ticket. We are trying to use the latest release [3.5.1](https://github.com/Netflix/dgs-framework/releases/tag/v3.5.1) that includes this fix but we don't see it on [Maven Central](https://mvnrepository.com/artifact/com.netflix.graphql.dgs/graphql-dgs-spring-boot-starter) yet. Any insight? Thanks.

**Comment by paulbakker** [comment]
Strange, it should be on Maven Central... I'll look into it

**Comment by paulbakker** [comment]
@bono007 Thanks for reporting the maven central issue, it was indeed missing. It looks like there was some sort of issue with Bintray. It's in central now: https://repo1.maven.org/maven2/com/netflix/graphql/dgs/graphql-dgs/

Btw, we're migrating away from Bintray soon, this is happening for all Netflix OSS repos.

**Comment by bono007** [comment]
@paulbakker I just wanted to say thank you for the responsiveness - not just in this instance, but throughout. It's really appreciated. Thank you.

**Comment by paulbakker** [comment]
> @paulbakker I just wanted to say thank you for the responsiveness - not just in this instance, but throughout. It's really appreciated. Thank you.

Thank you, much appreciated!
