### ISSUE TITLE
bug: Kotlin WebFlux - Request Context is not propagating to suspended Resolver function

### ISSUE THREAD

**Issue by darko1002001** [Netflix/dgs-framework#582]
I am using Kotlin with Spring WebFlux + Spring Security. I want to be able to read the authenticated user information as part of the request context. There is a utility class called ReactiveSecurityContextHolder provided by Spring Security that read this information. Unfortunately the data stored in the request context is not available when executing the resolver methods.

There is an issue related to this and a proposed solution which helps with solving the case where a resolver returns a Mono or a Flux instance.

[https://github.com/Netflix/dgs-framework/issues/375](https://github.com/Netflix/dgs-framework/issues/375)

However this doesn't help when defining a Kotlin suspend function as the resolver method. In this case the context data is not available.

I think this is related to how the coroutines are executed here:

https://github.com/Netflix/dgs-framework/blob/cb762dae368583c6a4a0754b6a845f859d9f5b59/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DataFetcherInvoker.kt#L106

The simplest way to show the problem is to do the following:

- Register a custom Context Builder

```
@DgsComponent
class MonoContextBuilder : DgsReactiveCustomContextBuilderWithRequest<WebContext> {
    override fun build(
        extensions: Map<String, Any>?,
        headers: HttpHeaders?,
        serverRequest: ServerRequest?
    ): Mono<WebContext> {
        return Mono.deferContextual { context ->
            Mono.just(WebContext(context))
        }
    }
}
```

- create a separate Bean or Component of a DataFetcherResultProcessor. This is nearly identical to the one included with the library, except for copying over the request context we got above into the next request that executes the resolver. This will work if the return type of the resolver function is a Mono in this case.

```
@Component
class MonoDataFetcherResultProcessor : DataFetcherResultProcessor {
    override fun supportsType(originalResult: Any): Boolean {
        return originalResult is Mono<*>
    }

    override fun process(originalResult: Any, dfe: DgsDataFetchingEnvironment): Any {
        if (originalResult is Mono<*>) {
            val context = (dfe.getContext<DgsContext>().customContext as WebContext).requestContext
            return originalResult.contextWrite(context).toFuture()
        } else {
            throw IllegalArgumentException("Instance passed to ${this::class.qualifiedName} was not a Mono<*>. It was a ${originalResult::class.qualifiedName} instead")
        }
    }
}
```

Here is a working example for a resolver returning Mono:

```
   @DgsQuery
   fun demo(dfe: DataFetchingEnvironment): Mono<Authentication> {
        val mono: Mono<Authentication> = Mono.deferContextual { context ->
            // Context here will contain the extra data added by Spring Security
            ReactiveSecurityContextHolder.getContext().map { it.authentication }
        }
        return mono
    }
```

The issue happens if we convert this method to a suspend function returning a result

```
 @DgsQuery
    suspend fun demoSuspend(dfe: DataFetchingEnvironment): String {
        // This is always null
        val securityContext = ReactiveSecurityContextHolder.getContext().awaitFirstOrNull()
        return "Hello World"
    }
```

In the REST API code i have a service which i can inject into other components that provides access to the context information such as the User ID, without me needing to pass in the Context (DataFetchingEnvironment in this case) in each service method as an argument. I haven't been able to find any info on what is the proposed alternative. I am assuming that Method Security will also not work on suspend functions because of this, but haven't tested it.

**Comment by hantsy** [comment]
This may be a Spring Security context related issue in Kotlin Coroutines . 

I created a [Kotlin Coroutines sample](https://github.com/hantsy/spring-graphql-sample/tree/master/dgs-kotlin-co), the normal suspend function works well, but security annotations on datafetechers is problematic.

**Comment by darko1002001** [comment]
So in the context, at least in my case there are 2 items. One is the Security Context coming from Spring Security, and the other is the request context coming from webflux. I don't think this is a spring issue, from what i've seen it comes down to this library and maybe the graphql-java lib using Java Futures as opposed to coroutines or reactor observables. Instead of the complete request being a single observable chain, there are separate tasks started (as futures) to which the context is not propagated.

**Comment by gnoeley** [comment]
I've proposed a fix based on your initial observations @darko1002001 (see https://github.com/Netflix/dgs-framework/pull/1041). Both of these PRs combined (pending review changes) should get Kotlin suspend functions working as expected as DataFetcher(s) 🤞

**Comment by gnoeley** [comment]
@berngp worth closing this and #375 now?

**Comment by berngp** [comment]
We should, thanks to your help @gnoeley
