### ISSUE TITLE
Directives APIs

### ISSUE THREAD

**Issue by dcheung2** [Netflix/dgs-framework#59]
It seem that DGS framework does not provide any API to access [Graphql Directives ](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/GraphQLDirective.java)

Is there any plan to support GraphQLDirective binding in DataFetcher in additional to existing InputArgument ?

**Comment by omaralani1** [comment]
Unsubscribe

**Comment by srinivasankavitha** [comment]
Can you provide an example of your use case? Are you looking to define your own custom directives?

**Comment by hkdennis2k** [comment]
In my case it is @locale for i18n fields.

@optional for something is fine to skip if slow / busy

@maxLength for memory limited clients on field possible huge payload


I can also think of 
@preload @lowpriority @mimetype @etag @hiddenAPi @version where they may or may not useful, depends on application usecases.

But does it matter? If the framework is to make graphql easier to unlock the features defined in the graphql spec.

**Comment by srinivasankavitha** [comment]
Ok, makes sense. I wasn't aware of this feature actually. Mainly wanted to understand if you were referring to the @skip and @include directives  - the schema directives which you should be able to use as is, but that is not what you are referring to. I think it makes sense to add support for graphql directives as you describe it.

**Comment by paulbakker** [comment]
@srinivasankavitha I think the question is how to get the directives set on a field from data fetcher code, not how to add new directives.

I'll look into this

**Comment by paulbakker** [comment]
I wasn't completely sure, so added a test here: https://github.com/Netflix/dgs-framework/commit/1f9b75006d2689758fb5e016c50cabed07ef7da9

In a datafetcher you can get access to field definitions from the `DataFetchingEnvironment`. 
For example the following schema: 
```
directive @someDirective(name: String) on FIELD_DEFINITION
type Query {
     hello: String @someDirective(name: "some name")
}
```

Using `DgsDataFetchingEnvironment` to get the field definition and the defined directives.
```
@DgsData(parentType="Query", field="hello")
fun hellOFetcher(dataFetchingEnvironment: DgsDataFetchingEnvironment):String {
      val directive = dataFetchingEnvironment.fieldDefinition.directives[0]
      return "hello ${directive.arguments[0].value}"
}
```

**Comment by dcheung2** [comment]
Actually I've have a problem to [get the directives set on a field with SPQR](https://stackoverflow.com/questions/61947301/how-to-access-field-level-graphql-directive-with-graphql-spqr). 

It is fine for getting it from a (nested) query level, but I am not sure when I made attempt to read it on sub-field level. Beside the API is not friendly to read / to understand.

**Comment by paulbakker** [comment]
I'm not sure how SPQR is related?

For sub fields, if you need to read the directive for further processing, it's probably just worth putting that logic in a sub datafetcher? That way you don't have to do the "look ahead" that you're mentioning in the stackoverflow post.

As for the API not being friendly, I agree with that to some extend (although it's not a super common use-case either). Any proposal on how it could be nicer using a DGS API instead of DataFetchingEnvironment?

**Comment by paulbakker** [comment]
Closing as "won't fix". As explained in the previous comment, there doesn't seem to be a great way of providing such an API that is useful in different use-cases.

Please re-open if there are ideas on how to make it widely applicable.

**Comment by andimarek** [comment]
@paulbakker Please have a look at `QueryDirective` in GraphQL Java ( accessible via `DataFetchingEnvironment`). This is how the class that should give you a nice way of getting the Directives.
