### ISSUE TITLE
[CodeGen] Unable to supply arguments for fields in projection nor supply aliases

### ISSUE THREAD

**Issue by deadpool333999** [Netflix/dgs-framework#63]
Inspecting the generated code, looks like there is no ability to supply arguments to fields in projections nor is there ability to supply aliases either.
https://graphql.org/learn/queries/#arguments
https://graphql.org/learn/queries/#aliases

This behavior can be reproduced by tweaking the example from the Getting started guide:
`type Votes {
    starRating(min: Float): Float
    nrOfVotes: Int
}`
After generating for this example, there is no way to set `min` on the field `starRating` via the `TicksEdgesNodeRouteVotesProjection.java` methods.

**Comment by srinivasankavitha** [comment]
We don't support this type of query currently. Will look into adding this as a new feature.

**Comment by sdoxsee** [comment]
I believe this is a codegen issue. Should this issue be closed and linked to a new one on https://github.com/Netflix/dgs-codegen for better tracking?

**Comment by srinivasankavitha** [comment]
Yes, sure. That is a better place to track this.

**Comment by srinivasankavitha** [comment]
Moved to codegen repo, closing this issue.

**Comment by sdoxsee** [comment]
@deadpool333999 would you be interested in reviewing https://github.com/Netflix/dgs-codegen/pull/69 to see if that meets your needs?
