### ISSUE TITLE
The Platform BOM references SNAPSHOT builds of reactor-core

### ISSUE THREAD

**Issue by JohanNordlinder** [Netflix/dgs-framework#642]
## Expected behavior
When using the Maven `graphql-dgs-platform-dependencies` package I assume only release builds of dependencies will be installed.

## Actual behavior
With the BOM in pom.xml
```
 <dependency>
    <groupId>com.netflix.graphql.dgs</groupId>
    <artifactId>graphql-dgs-platform-dependencies</artifactId>
    <!-- The DGS BOM/platform dependency. This is the only place you set version of DGS -->
    <version>4.5.1</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

Running `mvn dependency:tree` result in 
```
[INFO] |  |  +- io.projectreactor:reactor-core:jar:3.4.11-SNAPSHOT:compile (version selected from constraint [3.4,))
```

When looking at the POM file for `com.netflix.graphql.dgs:graphql-dgs-platform` I can see that the version of reactor-core is specified as `<version>[3.4,)</version>`. which apparently will hit SNAPSHOT builds as well.

As the purpose of the BOM is to resolve all dependencies to compatible versions I guess this should be considered a bug. My team encountered a situation today where the SNAPSHOT build resolved was not compatible with the rest of the spring boot project which caused errors of type: ` java.lang.ClassNotFoundException: reactor.core.Disposable`.

We resolved this by explicitly importing a stable version of `reactor-core`:
```
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.4.10</version>
</dependency>
```

**Comment by berngp** [comment]
Thanks for reporting @JohanNordlinder, will address this in the next release.
