### ISSUE TITLE
bug: If the input is a list of enums, the deserialized list passed to the fetcher still contains strings.

### ISSUE THREAD

**Issue by berngp** [Netflix/dgs-framework#644]
If the input is a list of enums, the deserialized list passed to the fetcher still contains strings, e.g.:

```
Query {
  lookup(types: [MyTypeEnum!]): [Result]
}

enum MyTypeEnum {
  TYPE1,
  TYPE2
}
```

This will fail:
```
query TestQuery {
  lookup(types: [TYPE1])
}
```

However if you nest the enum inside another input object the deserialization does work correctly:
```
query {
  lookup(types: MyLookupType): [Result]
}

input MyLookupType {
  types: [MyTypeEnum!]!
}

enum MyTypeEnum {
  TYPE1,
  TYPE2
}
```

this will work, nested list of enums will be deserialized properly when calling the fetcher method:
```
Query TestQuery {
  lookup(types: { types: [TYPE1]})
}
```

**Comment by jrogers** [comment]
@berngp Confirmed this works on 4.8.1
