### ISSUE TITLE
bug: After #522, (default) `Apollo Client` subscriptions no longer work with `dgs-framework`

### ISSUE THREAD

**Issue by zackary-clark** [Netflix/dgs-framework#651]
When following the [Apollo Client docs](https://www.apollographql.com/docs/react/data/subscriptions/) to set up a websocket subscription, DGS can no longer consume the connection_init message from Apollo, as of #522.

## Expected behavior
DGS websocket subscriptions work with Apollo.

## Actual behavior
Jackson databind throws an `InvalidTypeIdException` referencing `com.netflix.graphql.types.subscription.OperationMessage["payload"]`

## Steps to reproduce
Run the additional `OperationMessageTest` case referenced below
-or-
Attempt to use a WebSocketLink with Apollo to an API using DGS

## Notes
I write this under the assumption that DGS + Apollo Client is a combination the GraphQL community wants to "just work," as they're the two most popular JVM and React libraries, and file it as a DGS bug rather than an Apollo one as the Apollo behavior has been consistent for quite some time.

Downgrading to any version prior to #522 solves this issue.

The additional test case simulates what Apollo sends on initial connection, which is always a `payload` of `{}`.

I spent several hours playing around with Jackson annotation configurations trying to coerce `{}` to `null`, but this just isn't possible.

It would seem the only options are writing a fairly complex custom deserializer, or undoing the creation of the shared subscription types module. Neither of these seem perfect...

## Test Case
https://github.com/zackary-clark/dgs-framework/commit/c3add1fb167a808c041e114922a525eba45a19cd

**Comment by paulbakker** [comment]
Thanks for reporting this @zackary-clark. That's definetely an unintentional side-effect, and we didn't know about this yet!

Apollo client should just work, so this needs to be fixed.

**Comment by paulbakker** [comment]
Fixed in 4.8.3 which we just released. Sorry for breaking it!
https://github.com/Netflix/dgs-framework/releases/tag/v4.8.3
