### ISSUE TITLE
bug: 4.7.7 is missing in the nexus

### ISSUE THREAD

**Issue by EugenMayer** [Netflix/dgs-framework#665]
Not sure why this happens (kind of unusually often), but 4.7.7 is not released to the nexus yet : https://mvnrepository.com/artifact/com.netflix.graphql.dgs/graphql-dgs-platform-dependencies.

**Comment by paulbakker** [comment]
There is no 4.7.7 I think? The releases page doesn't show it: https://github.com/Netflix/dgs-framework/releases

We went from 4.7.6 to 4.8.

**Comment by EugenMayer** [comment]
Odd - i have a release notification (gihub) for 4.7.7 - has it been deleted? Anyway, if this is just me confused or it has been deleted, same outcome. I went to 4.8.3 already too, so great you closed that issue. Sorry for the fuz, kind of confusing start into thee week!
