### ISSUE TITLE
bug: operationName is ignored in WebFlux implementation

### ISSUE THREAD

**Issue by TrueDevProfile** [Netflix/dgs-framework#672]
I am using this framework with Spring WebFlux, and I have noticed that in Prometheus `operationName` is empty 
![image](https://user-images.githubusercontent.com/22364772/135257225-c41ce675-9896-4f83-b3d2-2429bdc9c635.png)

## Expected behavior
`operationName` should have name of query
## Actual behavior
`operationName`  is empty

I guess It is an empty string because of the following line  
https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-spring-webflux-autoconfigure/src/main/kotlin/com/netflix/graphql/dgs/webflux/handlers/DgsWebfluxHttpHandler.kt#L56

**Comment by srinivasankavitha** [comment]
Thanks for reporting, will look into fixing it.
