### ISSUE TITLE
bug: WebSocketHandler produce in junit tests a memory leak

### ISSUE THREAD

**Issue by TheMeinerLP** [Netflix/dgs-framework#677]
## Expected behavior
After exiting the application that the threads are stopped in the class `DgsWebSocketHandler`

## Actual behavior
TaskTimers are created but not stopped on each start but not on exit 

## Steps to reproduce
Create some unit tests with a abstract class system.
Base Class:
```kt
@RunWith(SpringRunner::class)
@ActiveProfiles("test")
@SpringBootTest(classes = [ExampleAPI::class, SpringSecurityAuditorAware::class])
@AutoConfigureMockMvc
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
@Suppress("UnnecessaryAbstractClass")
abstract class TestBase {
    @Autowired
    lateinit var context: ApplicationContext

    @MockkBean
    internal lateinit var userUtils: UserUtils

    @Before
    fun initializeContext() {
        SpringContext.context = context

        coEvery { userUtils.getCurrentUser() } returns
            UserUser(
                1,
                "Test",
                "Unit",
                "",
                eventStoreId = "test"
            )
    }
}
```
Each test:
```kt
class AddressAddressDatabaseHandlerTest : TestBase() {
    @Test
    fun create() = runBlocking {
        val address = addressAddressDatabaseHandler.create(
            AddressAddress(
                street = "Musterstraße",
                number = "1",
                zip = "89073",
                city = "Ulm",
                country = "DE",
            ).toDto()
        )

        val addressAddress = addressAddressDatabaseHandler.getById(1)
        Assert.assertEquals(address, addressAddress)
    }
}
```
[https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L42](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L42)

**Comment by TheMeinerLP** [comment]
![image](https://user-images.githubusercontent.com/6745190/136015876-8185ddb8-2585-4449-abc9-f71a0b9b6bd9.png)
![image](https://user-images.githubusercontent.com/6745190/136015897-36e5c7f7-b578-458d-ade5-abab41612419.png)

**Comment by Georgian** [comment]
Do you have a follow up for this?

**Comment by srinivasankavitha** [comment]
Thanks for reporting the issue. We will investigate and try to get a fix in
the next release. In the meantime, if you are blocked, we do welcome PR
contributions, so feel free to open a PR.

**Comment by paulbakker** [comment]
Closing this as this is now handled by Spring GraphQL with the DGS/Spring GraphQL integration.
