### ISSUE TITLE
Unable to pass header while writing unit test for datafetchers

### ISSUE THREAD

**Issue by dpatra1** [Netflix/dgs-framework#685]
### Discussed in https://github.com/Netflix/dgs-framework/discussions/683

<div type='discussions-op-text'>

<sup>Originally posted by **dpatra1** October  6, 2021</sup>
Hello,

I need help to address an issue which I am seeing while writing unit test cases for the data fetcher.

Here is my DataFetcher:
`@Slf4j
@DgsComponent
@Transactional(readOnly = true)
public class GetUserMetaDataDataFetcher {

	@Autowired HttpServletRequest request;
	@Autowired UserService userService;

    @DgsData(parentType = "Query", field = "userMetaData")
    public UserMetaDataResult getUserMetaData(@InputArgument("schoolId") UUID schoolId) {

    	String userId = request.getHeader("USER_UUID");

    	if (isBlank(userId)) {
      		log.error("User UUID is missing in the header");
      		throw new BadRequestError("User ID is missing in the header which is required for the API to pull the data.");
    	}

        return userService.getUser(userId, schoolId.toString());
    }
}`

Here is unit test I have written for the datafetcher.

`
@SpringBootTest(
        classes = {
                DgsAutoConfiguration.class,
                GraphQLRuntimeWiring.class,
                GetUserMetaDataDataFetcher.class,
                DgsExtendedScalarsAutoConfiguration.class
        })
public class GetResidualDocumentUploadDataFetcherTest {

    @Autowired DgsQueryExecutor dgsQueryExecutor;

    @MockBean UserService userService;

    @Mock HttpServletRequest request;

    @Test
    void testEduContentById() {
        Map<String, Object> variables = new HashMap<>();
        variables.put(SCHOOLID, schoolId);

        when(request.getHeader(eq(X_CHEGG_USER_UUID.getKey()))).thenReturn(userId);

        when(userService.getUser(eq(userId), eq(schoolId))).thenReturn(getUserMetaDataResult());

        ExecutionResult response = dgsQueryExecutor.execute(RESIDUAL_QUERY, variables);

    }

    UserMetaDataResult getUserMetaDataResult() {
        return UserMetaDataResult.builder().build();
    }
}`

The problem with this is:
-  I am not able to pass the USER_ID in header.
- And if I try to mock `when(request.getHeader(eq(X_CHEGG_USER_UUID.getKey()))).thenReturn(userId);`, its always null.

I don't want to change all my DataFetcher to pass header as an argument like below.
`@RequestHeader("USER_UUID") String userId`

What are the other ways I can address this issue ? Its kind of blocker to achieve the unit test coverage goal which we have for the project. Need help.

Thanks in advance.

Thanks,
Deba</div>

**Comment by paulbakker** [comment]
This is supported through the `@DgsQueryExecutor` and alternatively using the Spring GraphQL `HttpGraphQlTester`.
