### ISSUE TITLE
documentation: Improve the deprecation messages surrounding the GraphQLClient methods.

### ISSUE THREAD

**Issue by berngp** [Netflix/dgs-framework#693]
## What are you missing in the docs

The `@Deprecated("The RequestExecutor should be provided while creating the implementation.", ReplaceWith("Example: new DefaultGraphQLClient(url, requestExecutor);"))` points to`DefaultGraphQLClient`, which is deprecated as well. \
We need to suggest either `CustomGraphQLClient`, `CustomReactiveGraphQLClient` and `WebClientGraphQLClient`.

Creating a guide on when to use each of the clients mentioned above will help as well as provide examples of migrating from the deprecated method calls to the new clients.

**Comment by paulbakker** [comment]
I think the guide is already there: https://netflix.github.io/dgs/advanced/java-client/#usage

**Comment by berngp** [comment]
I think we are just missing a simple change in the `GraphQLClient.kt` file. Right now it reads...
```
graphql-dgs-client/src/main/kotlin/com/netflix/graphql/dgs/client/GraphQLClient.kt
59:    @Deprecated("The RequestExecutor should be provided while creating the implementation.", ReplaceWith("Example: new DefaultGraphQLClient(url, requestExecutor);"))
62:    @Deprecated("The RequestExecutor should be provided while creating the implementation.", ReplaceWith("Example: new DefaultGraphQLClient(url, requestExecutor);"))
116:    @Deprecated("The RequestExecutor should be provided while creating the implementation.", ReplaceWith("Example: new DefaultGraphQLClient(url, requestExecutor);"))
123:    @Deprecated("The RequestExecutor should be provided while creating the implementation.", ReplaceWith("Example: new DefaultGraphQLClient(url, requestExecutor);"))
```
