### ISSUE TITLE
feature: DGS Federation Gateway

### ISSUE THREAD

**Issue by saravind-hotstar** [Netflix/dgs-framework#697]
- Support for federation gateway talking to subgraph based services. 
- Current GraphQL client can be enhanced to understand apollo based federated schema guidelines 
- Java based graphql federator to allow federation from subgraph graphql services

**Comment by paulbakker** [comment]
@saravind-hotstar Although I completely agree that an open-source gateway in Java would be great to have, it shouldn't be part of the DGS Framework. It should be a separate project.
We use a Java implementation at Netflix, but there are currently no plans yet to open source this unfortunately. 

Like @srinivasankavitha mentioned, the best option right now is the Apollo gateway.
