### ISSUE TITLE
documentation: Obsolete Kotlin Data Types section in mutations

### ISSUE THREAD

**Issue by lukas-krecan** [Netflix/dgs-framework#701]
[Kotlin Data Types](https://netflix.github.io/dgs/mutations/#kotlin-data-types) section in mutations is obsolete. DGS is not using Jackson for input deserialization anymore, and `var`s are not required neither. I think it's possible to drop the whole section.

**Comment by paulbakker** [comment]
Fixed. Thanks again @lukas-krecan
