### ISSUE TITLE
bug: Kotlin type in custom type mapping can not be a Kotlin type #704

### ISSUE THREAD

**Issue by evser** [Netflix/dgs-framework#705]
**build.gradle.kts**
```
tasks {
    generateJava {
        schemaPaths = mutableListOf("${projectDir}/src/main/resources/schema") // List of directories containing schema files
        packageName = "com.something" // The package name to use to generate sources
        generateClient = true // Enable generating the type safe query API
        language = "kotlin"
        typeMapping = mutableMapOf("JSON" to "kotlin.String")
    }
}
```

**schema.graphqls**
```
"""A JSON formated string."""
scalar JSON

type ColumnValue {
    """The column value's additional information."""
    additional_info: JSON
}
```

## Expected behavior
everything is compiled 

## Actual behavior
**kotlin.String** is not found during compiling **.java** class and if I change it to **java.lang.String** then it shows me that I should use **kotlin.String**

```
> Task :compileJava
D:\projects\others\tgbot\build\generated\com\...\client\Change_column_valueGraphQLQuery.java:16: error: cannot find symbol
      kotlin.String value, Boolean create_labels_if_missing, Set<String> fieldsSet) {
            ^
  symbol:   class String
  location: package kotlin
```

## Steps to reproduce

1.  Compile the configuration above.

**Comment by npwork** [comment]
@evser  for the primitive type (nonspecific to the language)  you can use

```
typeMapping = mutableMapOf("JSON" to "String")
```

**Comment by npwork** [comment]
@evser  I believe it was fixed as part of `5.1.10`. I've fixed it in PR https://github.com/Netflix/dgs-codegen/pull/293 which is part of the release.
Can you please try with dgs-codegen plugin version `5.1.10`?

**Comment by evser** [comment]
@npwork I have tried, but still have "import String" generated in .kt files:

![image](https://user-images.githubusercontent.com/11527468/145607148-9539f075-0b4e-4410-b1a0-9eaf3a85ec6d.png)

**Comment by npwork** [comment]
@evser you are right, reproduced it. Will fix it and come back to you.

**Comment by npwork** [comment]
@evser meanwhile can you try to:

```kotlin
typeMapping = mutableMapOf("JSON" to "kotlin.String")
```

**Comment by npwork** [comment]
Fix is available in PR: https://github.com/Netflix/dgs-codegen/pull/303

**Comment by evser** [comment]
@npwork `("JSON" to "kotlin.String")` does not work, as Queries are generated in `.java` files

![image](https://user-images.githubusercontent.com/11527468/146021065-675827a4-b6ad-4bd9-bc71-f990012c2492.png)

**Comment by paulbakker** [comment]
Closing this issue, it was fixed a long time ago but the issue was never closed.
