### ISSUE TITLE
bug: Failure to register data loader when also using com.graphql-java-kickstart

### ISSUE THREAD

**Issue by markwimpory** [Netflix/dgs-framework#715]
## Expected behavior

Dataloaders appear in the registry from the data fetch environment

## Actual behavior

No dataloader are in the registry

## Steps to reproduce

Include the following dependency

<dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>12.0.0</version>
        </dependency>

**Comment by paulbakker** [comment]
Why are you using `com.graphql-java-kickstart`? Any reason to use this together with DGS?
We will likely not prioritize debugging this, since it's an issue caused by another library.

**Comment by markwimpory** [comment]
Sorry didn't get notified of the change.  Im using kickstart because it includes a few tools I was interested in.  Ive had to remove these to a docker container which is less useful.  I guess its something to watch out for as its not the kickstyart library thats the problem but one of the other graphql dependencies.
