### ISSUE TITLE
documentation: a common federation use case

### ISSUE THREAD

**Issue by chen-ni-hotstar** [Netflix/dgs-framework#727]
## What are you missing in the docs

Consider this scenario: I'm working on the search engine domain, which returns a list of `movieId` as the search result based on the query parameters.

The `Movie` data is served by another domain.

In this case, how should I write the schema? I didn't find a clear answer in the documentation.

I imagine the schema for our search engine domain should look like this:

```
type Query {
    searchResults(q: String): [Movie]
}

type Movie @key(fields: "movieId") @extends {
    movieId: ID! @external
}
```

But what should the datafetcher for `searchResults` return? Is it a list of objects that contains the `__typename` and `id` attributes?

The support for Apollo Federation is actually the reason we chose DGS, but I've found very little information about federation in the documentation. I've read https://netflix.github.io/dgs/advanced/federated-testing/ but it's not very helpful.

It would be great if you could provide an example that helps me understand it. Thanks!

**Comment by srinivasankavitha** [comment]
@chen-ni-hotstar - the reason we don't have detailed documentation on federation is because this is already well defined by Apollo here: https://www.apollographql.com/docs/federation/

Our documentation is scoped to what the DGS framework offers to enable federation but not the federation spec by itself.

Let us know if you need any further clarification on how DGS supports federation.  We have am example that works with apollo's gateway as well here: https://netflix.github.io/dgs/examples/

I'll close this issue. Feel free to open a new issue if you find something specifically lacking in the docs.

**Comment by chen-ni-hotstar** [comment]
@srinivasankavitha Hi Kavitha, thanks for the reply! Yeah I've read the official Apollo Federation documentation, but there are some notable differences between how Apollo and DGS define a federated schema. For example, in the official Apollo doc, a schema might look like this:

```
extend type Show @key(fields: "id") {
    id: ID @external
    reviews: [Review]
}

type Review {
    starRating: Int
}
```
However, in the DGS example you provided, it's written like this:

```
type Show @key(fields: "id") @extends {
    id: ID @external
    reviews: [Review]
}

type Review {
    starRating: Int
}
```

Note the difference between `extend type` and `type ... @extends`.

Due to this inconsistency, I can't really figure out how federation works in DGS just by referring to the Apollo docs. That's the reason I created this issue.

As for the example you provided, it's helpful for sure, but it doesn't cover my use case. Normally I should have been able to infer how federation works in my use case, but unfortunately I can't figure it out.

**Comment by chen-ni-hotstar** [comment]
@srinivasankavitha  So I still believe there should be a dedicated section in the documentation focusing on how federation works in DGS.

**Comment by srinivasankavitha** [comment]
Ok, I see, makes sense. For the difference in `extend` vs @extends, they are technically doing the same. `@extends` is more for `graphql-java` to understand it. Per apollo's docs:
```
Some libraries such as graphql-java don't have native support for type extensions in their printer. Apollo Federation supports using an @extends directive in place of extend type to annotate type references:

type User @key(fields: "id") @extends {
  id: ID! @external
  reviews: [Review]
}
```

We will add some more documentation using the federation example we have to clarify this.

For your use case, the search service would just return the Movie object with the MovieID populated. The Movie service would populate the other fields. So the schema as you have it should work as is.

**Comment by paulbakker** [comment]
@chen-ni-hotstar There aren't any differences between Apollo federation or DGS, it's based on the same spec.

It would be good to have federation docs on our site though - I don't find the Apollo docs to be particularly great (for federation), and it's confusing for users to read through all the JS related example code.

**Comment by chen-ni-hotstar** [comment]
@srinivasankavitha Thanks a lot! It does help :)

**Comment by chen-ni-hotstar** [comment]
@paulbakker 

> I don't find the Apollo docs to be particularly great (for federation), and it's confusing for users to read through all the JS related example code.

Exactly!

**Comment by srinivasankavitha** [comment]
Added more documentation with examples. Closing this issue. https://netflix.github.io/dgs/federation/
https://github.com/Netflix/dgs/pull/71
