### ISSUE TITLE
bug: GraphiQL path does not work with version 4.9.7 neither introspection query

### ISSUE THREAD

**Issue by zanonena** [Netflix/dgs-framework#738]
## Expected behavior
 Introspection query does not work neither GRAPHIQL path
## Actual behavior
The graphiql and instropection must work
## Steps to reproduce
I updated the framework to 4.9.7 and when going to http://localhost:8080/graphiql/index.html the GRAPHIQL does not work.

Here is the query that the graphiql does automatically:

```
    query IntrospectionQuery {
      __schema {
        
        queryType { name }
        mutationType { name }
        subscriptionType { name }
        types {
          ...FullType
        }
        directives {
          name
          description
          
          locations
          args {
            ...InputValue
          }
        }
      }
    }

    fragment FullType on __Type {
      kind
      name
      description
      
      fields(includeDeprecated: true) {
        name
        description
        args {
          ...InputValue
        }
        type {
          ...TypeRef
        }
        isDeprecated
        deprecationReason
      }
      inputFields {
        ...InputValue
      }
      interfaces {
        ...TypeRef
      }
      enumValues(includeDeprecated: true) {
        name
        description
        isDeprecated
        deprecationReason
      }
      possibleTypes {
        ...TypeRef
      }
    }

    fragment InputValue on __InputValue {
      name
      description
      type { ...TypeRef }
      defaultValue
      
      
    }

    fragment TypeRef on __Type {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                  ofType {
                    kind
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
```
  
Response:
`{"timestamp":"2021-11-17T15:15:35.562+00:00","path":"/graphiql/%3CDGS_GRAPHQL_PATH%3E","status":404,"error":"Not Found","message":null,"requestId":"ce7c76ba-20"}`

`{
  "errors": [
    "{\n  \"timestamp\": \"2021-11-17T15:15:35.591+00:00\",\n  \"path\": \"/graphiql/%3CDGS_GRAPHQL_PATH%3E\",\n  \"status\": 404,\n  \"error\": \"Not Found\",\n  \"message\": null,\n  \"requestId\": \"ce7c76ba-21\"\n}"
  ]
}`

If I watch the console and the network in chrome tab I am seeing these errors:

> DevTools failed to load source map: Could not load content for https://unpkg.com/graphiql/graphiql.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

> DevTools failed to load source map: Could not load content for https://unpkg.com/graphiql@1.5.1/graphiql.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

The problem that i suspect is that is trying to download those files with .map extensions, does not makes any sense.
The real files are without the .map extension... I do not know what is happening.
These are the correct URLS:
Request URL: https://unpkg.com/graphiql@1.5.1/graphiql.min.js
Request URL: https://unpkg.com/graphiql@1.5.1/graphiql.min.css

**Comment by heoYH** [comment]
https://github.com/Netflix/dgs-framework/pull/737

**Comment by berngp** [comment]
Thanks @heoYH, will validate the changes on master and would have release soon with your changes.

**Comment by berngp** [comment]
Fix should be available in the latest release.

**Comment by willisjtc** [comment]
Looks like i'm running into this issue now and i'm on 5.1.16
