### ISSUE TITLE
bug: Kotlin GraphQL Code Gen on input type with default value is not correct

### ISSUE THREAD

**Issue by gaplo917** [Netflix/dgs-framework#755]
## Expected behavior
Given the `input` with the empty object type
<img width="546" alt="Screenshot 2021-11-27 at 12 20 09" src="https://user-images.githubusercontent.com/5468398/143667842-8f66dc71-cf60-4b37-bd0e-253e282ffde0.png">

I expect the generated type should looks like the following
<img width="717" alt="Screenshot 2021-11-27 at 12 22 40" src="https://user-images.githubusercontent.com/5468398/143667865-c9651df7-2b23-421c-a6a6-83529598f403.png">

## Actual behavior
Given the `input` with the empty object type
<img width="546" alt="Screenshot 2021-11-27 at 12 20 09" src="https://user-images.githubusercontent.com/5468398/143667842-8f66dc71-cf60-4b37-bd0e-253e282ffde0.png">

the actual generated looks like
<img width="640" alt="Screenshot 2021-11-27 at 12 19 46" src="https://user-images.githubusercontent.com/5468398/143667957-51c4bd32-753a-4575-a40b-02b408a8df7d.png">

Given the `input` with the object type with some default value 
<img width="644" alt="Screenshot 2021-11-27 at 12 20 43" src="https://user-images.githubusercontent.com/5468398/143667903-484a9fb6-e8ab-4c31-8c83-9f3192ce7f4a.png">

the generated file have some default value inside, but the type is not correct.
<img width="818" alt="Screenshot 2021-11-27 at 12 20 36" src="https://user-images.githubusercontent.com/5468398/143667909-778c1f48-fe9b-4a15-a586-fb9b0f661fe6.png">

## Steps to reproduce
1. clone https://github.com/Netflix/dgs-examples-kotlin
2. Modify the graphql schema to 

```graphql
input Something {
    sth1: Int = 0
    sth2: String = ""
}

input TitleFormat {
    uppercase: Boolean
    someInput: Something = {}
}

```

OR

```graphql
input Something {
    sth1: Int = 0
    sth2: String = ""
}

input TitleFormat {
    uppercase: Boolean
    someInput: Something = { sth1: 1, sth2: "test" }
}

```

3. run `./gradlew generateJava`
4. open `./build/generated/com/example/demo/generated/types/TitleFormat.kt`

**Comment by srinivasankavitha** [comment]
Thanks for reporting @gaplo917. This is actually an issue with the code generation plugin. Would you be able to move this issue to here: https://github.com/Netflix/dgs-codegen

**Comment by gaplo917** [comment]
Moved.

Thanks for your great work on DGS @srinivasankavitha
