### ISSUE TITLE
Maven plugin for code generation similar to the Gradle plugin

### ISSUE THREAD

**Issue by HenrikSkriver** [Netflix/dgs-framework#78]
Hi
Thank you so much for making DGS public!

It would very helpful for the maven based projects to also have a maven plugin available for code generation like the gradle projects do.

Is that in the pipeline or even on the roadmap?
Is there a suggested workaround on how to run the gradle plugin from a maven build?

Thank you in advance.

**Comment by srinivasankavitha** [comment]
Yes, we have it in our backlog. Since the majority of our users so far (mainly internal) use Gradle, we haven't gotten to it just yet.
Unfortunately, I am not aware of a workaround for this though.

**Comment by paulbakker** [comment]
Also note that without a community contribution it’s unlikely we’ll prioritize a Maven plugin any time soon, since we’re not using Maven at all. 
The codegen code is fully decoupled from Gradle however, the plugin is a very thin layer, so it should be relatively easy to do the same for Maven.

**Comment by Moltik** [comment]
Hello. We also faced this problem since our projects are also based on maven. We are currently using a third-party plugin for code generation

**Comment by srinivasankavitha** [comment]
Linking to this issue: https://github.com/Netflix/dgs-codegen/issues/47. @deweyjose mentioned having a maven plugin that they have implemented for this.

**Comment by paulbakker** [comment]
Added a link to the Maven plugin created by @deweyjose to the docs:  https://netflix.github.io/dgs/generating-code-from-schema/
