### ISSUE TITLE
Does the client generation not work with schema.json?

### ISSUE THREAD

**Issue by Sam-Kruglov** [Netflix/dgs-framework#785]
I couldn't find any info on whether I can use the [`schema.json`](https://www.apollographql.com/docs/android/essentials/get-started-java/#download-your-schemajson-file) for generating my client code. All the documentation asks for `.graphqls` files which is hand-written only, as it seems. I would like to re-generate my client as part of the CI to keep it up to date, so it will use the `schema.json` that is served by the deployed application.

This is the way the Apollo plugin works. 
https://github.com/aoudiamoncef/apollo-client-maven-plugin
https://www.apollographql.com/docs/android/essentials/get-started-java/

**Comment by berngp** [comment]
We don't support it. This might be a nice feature to have but it would be hard for us to prioritize since don't follow that workflow internally.

Context, I see the [apollo-client-maven-plugin] will...
> Create a file src/main/graphql/schema.json with the JSON results of an introspection query, OR you can automatically generate this file by setting introspection.enabled to true and endpointUrl to your GraphQL endpoint. At build time, the plugin will query the server and install this file per the value of schemaFile.

[apollo-client-maven-plugin]: https://github.com/aoudiamoncef/apollo-client-maven-plugin

**Comment by srinivasankavitha** [comment]
we won't be adding support for this any time soon since it's not a priority for us. We will create a new ticket if this becomes a more widely requested feature.
