### ISSUE TITLE
changing the endpoint for running tests

### ISSUE THREAD

**Issue by liron-navon** [Netflix/dgs-framework#80]
I follow the testing examples from the documentation, and I use the "DgsQueryExecutor" to run the queries.
I know spring runs a local service, but I would like to run the tests against a remote service and (as part of our CI/CD pipeline).

Is there an option to change the URL used by the "DgsQueryExecutor" to execute queries against a remote server? if not, can we have such an option?

**Comment by paulbakker** [comment]
You’re looking for the  [DGS GraphQL Client](https://netflix.github.io/dgs/advanced/java-client/). It’s a similar API as the query executor, but designed to use over HTTP.

The DgsQueryExecutor itself can’t be configured remote, it doesn’t have any notion of HTTP.
