### ISSUE TITLE
documentation: Document injection of `PreparsedDocumentProvider`

### ISSUE THREAD

**Issue by jord1e** [Netflix/dgs-framework#822]
## What are you missing in the docs

The fact that you can inject a `PreparsedDocumentProvider` in order to cache the parsing and validation steps:

https://github.com/Netflix/dgs-framework/blob/3d1d61f52e7308ef21c0b5a195f9a01511421b18/graphql-dgs-spring-boot-oss-autoconfigure/src/main/kotlin/com/netflix/graphql/dgs/autoconfig/DgsAutoConfiguration.kt#L98-L102

## Proposed text

Will open a Pull Request somewhere this weekend. The PR will include an example on using a Caffeine cache.

**Comment by berngp** [comment]
Our Docs reside [here](https://github.com/Netflix/dgs).

**Comment by jord1e** [comment]
I am aware, I noticed the documentation issue template and label.
Thank you
