### ISSUE TITLE
documentation: How to customize scalars

### ISSUE THREAD

**Issue by MANJUSAK** [Netflix/dgs-framework#823]
If you want to achieve return a large object
For example: scalar Object
How to customize scalars

**Comment by berngp** [comment]
There is already an Object|JSON scalar that you could use. You might want to read first (GraphQL Java Extended Scalars)[https://github.com/graphql-java/graphql-java-extended-scalars#object--json-scalars]. The DGS Framework can auto-configure the GraphQL Java Extended Scalars if you import `com.netflix.graphql.dgs:graphql-dgs-extended-scalars`. More info [here](https://netflix.github.io/dgs/configuration/#dgs-extended-scalars-graphql-dgs-extended-scalars) on how to configure them.

**Comment by srinivasankavitha** [comment]
Closing this issue. Please reopen if needed.
