### ISSUE TITLE
are you planning to expand the configuration?

### ISSUE THREAD

**Issue by azgarot** [Netflix/dgs-framework#831]
Encountered a problem when deploying in docker graphql is deployed along the way http://localhost:8080/graphql , and graphiql at home looks at http://localhost:8080/service/myservice/graphql . Specifying dgs.graphql.path does not help, it is simply added to the path. Question is there any plans to add additional management settings, for example, by which graphiql will be viewed?

**Comment by paulbakker** [comment]
What's the exact problem you're having with `dgs.graphql.path`?

As for the general question the only answer I can give is "Probably, when the needs arrises". If there is anything _specific_ that you might need, let us know.

**Comment by azgarot** [comment]
the problem is that when deploying an application in docker, graphql expands along one path, and graphiql tries to find it in another place.Specifying dgs.graphql.path does not help as described above. In Docker, when deploying graphql, it turns out to take into account the path to the service, and in graphiql this path is not taken into account. Super if it would be possible to set separately <DGS_GRAPHQL_PATH> in graphql-dgs-spring-webmvc-auto configure index.html

**Comment by paulbakker** [comment]
Closing because AFAIK this is not an issue anymore, also it would have to be changed in Spring GraphQL if it is.
