### ISSUE TITLE
bug: HTTP status 500 when the request contains only a empty space

### ISSUE THREAD

**Issue by elizeusdsantos** [Netflix/dgs-framework#832]
## Expected behavior
Should return HTTP Status 400

## Actual behavior
It's actually returning HTTP Status Code 500 due to the following exception:

`com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input at [Source: (String)" "; line: 1, column: 0] at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688) at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586) at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548) at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3531) `

## Steps to reproduce
Send any request to `/graphql` having just a white space in the request body

**Comment by berngp** [comment]
Thanks for reporting. Will address this in the next release.
