### ISSUE TITLE
bug: NPE in equals of TypedGraphQLError

### ISSUE THREAD

**Issue by rabbitvirus** [Netflix/dgs-framework#841]
Funny problem found today. I was writing some tests for my project and I ran into strange NPEs...

For example, let's take the following piece of code:
```
TypedGraphQLError e1 = TypedGraphQLError.newBadRequestBuilder().build();
TypedGraphQLError e2 = TypedGraphQLError.newBadRequestBuilder().build();
Assertions.assertEquals(e1, e2);
```
		
We have two exactly the same errors. Equals should return true here. However, it fails with NPE:
```
java.lang.NullPointerException
	at com.netflix.graphql.types.errors.TypedGraphQLError.equals(TypedGraphQLError.java:257)
	...
```

I added a few tests and prepared a fix here:
[https://github.com/Netflix/dgs-framework/pull/840](https://github.com/Netflix/dgs-framework/pull/840)

I am looking forward to your review :-)

**Comment by srinivasankavitha** [comment]
Thanks for reporting and opening a PR. Changes look good to me.

**Comment by rabbitvirus** [comment]
It is fixed now. Thank you for your review and merge :-)
I am closing the issue.
