### ISSUE TITLE
feature: Support for union pagination

### ISSUE THREAD

**Issue by BCantos17** [Netflix/dgs-framework#843]
## Describe the Feature Request
Being able to use the connection directive on a union type

## Describe Preferred Solution
```
directive @connection on UNION

union Media @connection = Video | Image

type Query {
    media(first: String!, after: String!): MediaConnection
}
```

## Describe Alternatives
Need to use interface or a wrapper object around the union as a work around when a union type would make more sense

**Comment by srinivasankavitha** [comment]
Sorry, haven't been able to prioritize this yet. The implementation should
be straightforward to add. I'll try looking into adding some support in the
next couple weeks. However, in the meantime, feel free to open a PR if that
time frame is too delayed.

**Comment by BCantos17** [comment]
I can take a look for a possible PR but I have also been pretty busy on my end. Can you point me to the right direction?

**Comment by BCantos17** [comment]
nvm, I think I found it, seems straightforward. Will submit a PR soon

**Comment by BCantos17** [comment]
Created a PR @srinivasankavitha

**Comment by bcole** [comment]
One question on this @BCantos17, your example in this description shows:
```
directive @connection on UNION
```

However, I noticed [here in documentation](https://netflix.github.io/dgs/advanced/relay-pagination/#set-up):

> Note that the `@connection` directive is defined automatically by the framework, so there is no need to add it to your schema file.

So I am trying to omit declaring the `@connection` directive again in my schema, but when adding it on a union type, I get this error at startup:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

There are problems with the GraphQL Schema:
	 * 'Media' [@19:1] tried to use a directive 'connection' in the 'UNION' location but that is illegal
```

Note: if I manually add the declaration (like your example here), it does work as a workaround.  But, anyway we could reduce the need to redefine the directive?  Thanks!
