### ISSUE TITLE
feature: Kotlin specific generated request/response classes

### ISSUE THREAD

**Issue by mbossenbroek** [Netflix/dgs-framework#871]
## Describe the Feature Request
Generated projection and response classes that lean into Kotlin idioms like explicit nullability and leveraging lambda expressions to build a DSL.

Note: this isn't so much a request as a placeholder to track migrating some existing work into this repo.

## Describe Preferred Solution
A client might express a query like this (written in kotlin):
```
    client.query {
        foo(a = 1, b = "2") {
            field1
            field2 {
                other
                stuff
            }
        }
    }
```

For response objects, differentiate between "I asked for this and it's null" and "I did not ask for this, but I tried to use it"

## Describe Alternatives
Using the existing java classes :)

**Comment by paulbakker** [comment]
This is being worked on by folks at Netflix, and is expected to be contributed soon.

**Comment by Emily** [comment]
Closing as this has become available since the last activity on this issue: https://netflix.github.io/dgs/advanced/kotlin-codegen/
