### ISSUE TITLE
bug: Reactive Federated Graph errors out when returning a Mono in a DGSEntityFetcher

### ISSUE THREAD

**Issue by BCantos17** [Netflix/dgs-framework#876]
## Expected behavior
Given a reactive federated graph, framework should return requested fields in schema without issues
## Actual behavior

Returns error message stating no definition found for ...MonoJust.

Note: I tested this out without using Mono and it works fine

```
{
  "errors": [
    {
      "message": "Can't resolve '/_entities[0]'. Abstract type '_Entity' must resolve to an Object type at runtime for field '[_Entity]._entities'. Could not determine the exact type of '_Entity'",
      "extensions": {
        "code": "DOWNSTREAM_SERVICE_ERROR",
        "serviceName": "review",
        "classification": "DataFetchingException",
        "exception": {
          "message": "Can't resolve '/_entities[0]'. Abstract type '_Entity' must resolve to an Object type at runtime for field '[_Entity]._entities'. Could not determine the exact type of '_Entity'",
          "path": [
            "_entities",
            0
          ],
          "stacktrace": [
            "GraphQLError: Can't resolve '/_entities[0]'. Abstract type '_Entity' must resolve to an Object type at runtime for field '[_Entity]._entities'. Could not determine the exact type of '_Entity'", ... other message with personal data

          ]
        }
      }
    }
  ],
  "data": {
   ... data
  }
}
```
```
2022-02-11 14:28:26.189  WARN 89198 --- [ctor-http-nio-2] c.n.g.d.f.DefaultDgsFederationResolver   : No type definition found for reactor.core.publisher.MonoJust. You probably need to provide either a type mapping,or override DefaultDgsFederationResolver.typeResolver().Alternatively make sure the type name in the schema and your Java model match
2022-02-11 14:28:26.191  WARN 89198 --- [ctor-http-nio-2] n.graphql.execution.ExecutionStrategy    : Can't resolve '/_entities[9]'. Abstract type '_Entity' must resolve to an Object type at runtime for field '[_Entity]._entities'. Could not determine the exact type of '_Entity'

graphql.execution.UnresolvedTypeException: Could not determine the exact type of '_Entity'
```

## Steps to reproduce
Define a federated schema
```graphql
type Query {
  shows(titleFilter: String): [Show]
}

type Show @key(fields: "id") {
  id: ID
  title: String
  releaseYear: Int
}
```
Extend the federated schema
```graphql
type Show @key(fields: "id") @extends {
  id: ID @external
  reviews: [Review]
}

type Review {
  starRating: Int
}
```

Define entity fetcher in extended service with returning an object with `Mono.just(...)`
```kotlin
@DgsEntityFetcher(name = "Show")
fun show(values: Map<String, Any>): Mono<Show> {
        return Mono.just(Show( values.get("id") as String, null))
}

// Don't think it makes it here but including it just in case
@DgsData(parentType = "Show", field = "reviews" )
fun reviewFetcher(dfs: DgsDataFetchingEnvironment): Mono<Review> {
    val show = dfe.getSource<Show>()
    val loader = dfe.getDataLoader<String, Review>(reviews)
    val future = loader.load(show.id)
    return Mono.fromCompletionStage(future)
}
```

**Comment by gdagitrep** [comment]
Any updates on this, I am facing similar issue? `DgsQuery` works fine with Mono/Flux, but `DgsEntityFetcher` is troublesome.

**Comment by gdagitrep** [comment]
Found similar issue  https://github.com/Netflix/dgs-framework/issues/376, https://github.com/Netflix/dgs-framework/pull/389 , per which support was added in  `graphql-dgs-webflux-starter:4.2.0`. But I am using 4.9.20, still facing it.

@BCantos17 any workarounds found?

**Comment by sshevlyagin** [comment]
We're running into this as well :/

**Comment by sshevlyagin** [comment]
Tagging @paulbakker I didn't see explicit tests for `DgsEntityFetcher` in https://github.com/Netflix/dgs-framework/pull/389 does it require a similar but different fix?

**Comment by gdagitrep** [comment]
@BCantos17 

Found the following works: remove the mono only from the parent `DgsEntityFetcher` and keep the `Mono` in the actual field resolver. Using it as a work around for now until the bug is fixed.
```
@DgsEntityFetcher(name = "Show")
fun show(values: Map<String, Any>): Show {
        return new Show( values.get("id") as String, null)
}

@DgsData(parentType = "Show", field = "reviews" )
fun reviewFetcher(dfs: DgsDataFetchingEnvironment): Mono<Review> {
    val show = dfe.getSource<Show>()
    val loader = dfe.getDataLoader<String, Review>(reviews)
    val future = loader.load(show.id)
    return Mono.fromCompletionStage(future)
}
```

**Comment by srinivasankavitha** [comment]
Thanks for reporting this issue. We will look into fixing this in the next release or so.

**Comment by bogdanbrindusan** [comment]
@jord1e alright, a bit harsh, but fair. I admit I haven't looked deeply into why isn't it working before posting.

But thanks a lot for the suggestion; tested it and it works.

**Comment by srinivasankavitha** [comment]
@jord1e - Thanks so much for responding and suggesting a workaround. We will address this soon, we've been a bit busy with our current priorities and haven't gotten around to fixing this. Will do so in an upcoming release.

**Comment by jord1e** [comment]
Sorry for the rude reaction @bogdanbrindusan 

I had some free time, I fixed the issue @srinivasankavitha (consider it my Netflix internship application 😜)
#903 (fix) and https://github.com/Netflix/dgs/pull/84 (docs)
