### ISSUE TITLE
bug: Custom Context returned as null using DGS WebFlux

### ISSUE THREAD

**Issue by AyushChaubey** [Netflix/dgs-framework#889]
I am creating a graphQL server using the web flux starter dependency `graphql-dgs-webflux-starter` . In my use case, I want to fetch some details from the request header and set them in the context using my own custom context. 
For this purpose, I created a class that implements `DgsCustomContextBuilder` interface and added my logic in the overridden `build()` method. 
I added the logic to fetch my custom context in the Data Fetcher class like this `DgsContext.getCustomContext(dgsDataFetchingEnvironment)` . The issue is that the custom context that is returned is null. Also, when I make the request to this server then also the `build()` method of the custom context class is not invoked. I am adding the screenshots of both the custom context class and the Data Fetcher class. 

<img width="606" alt="Screenshot 2022-02-17 at 14 34 43" src="https://user-images.githubusercontent.com/6051317/154494537-1ac58d4e-5552-48b4-b335-a83484df7525.png">

<img width="1050" alt="Screenshot 2022-02-17 at 14 35 20" src="https://user-images.githubusercontent.com/6051317/154494607-cf0c6618-e912-470e-8b12-7a3d0cca99fd.png">

## Expected behavior
According to the [documentation](https://netflix.github.io/dgs/advanced/custom-datafetcher-context/), we should get the custom context in the Data Fetcher.

## Actual behavior
The custom context does not get initialised and we get `null` when we fetch it in the Data Fetcher.

## Steps to reproduce

I am attaching the sample project that can be used to reproduce the issue. I have added the code to create and fetch the custom context on top of the [official example](https://github.com/Netflix/dgs-examples-webflux) that is provided.

The custom context class that I have created is this - `MyContext.java`
The Data Fetcher where I try to fetch this context is this - `ReviewsDataFetcher.java`, in the first line of the method - `reviews(DgsDataFetchingEnvironment dfe, @InputArgument DateRange dateRange)` . The context that is returned is `null` .

The service can be started by running `DemoApplication.java` class or just running the Gradle command 
`./gradlew bootRun` .

Then open the UI - [http://localhost:8080/graphiql/](http://localhost:8080/graphiql/) and run this sample query  - 

`{
  shows {
    releaseYear
    reviews {
      username
    }
  } 
}
`

and put a breakpoint where we fetch the custom context at the first line in this method `reviews(DgsDataFetchingEnvironment dfe, @InputArgument DateRange dateRange)` . The returned context will be null.

Please let me know if you need anything else from my side and please let me know if you see any issue in which I am trying to fetch the custom context.

**Sample Project:**
[dgs-examples-webflux.zip](https://github.com/Netflix/dgs-framework/files/8089026/dgs-examples-webflux.zip)

**Comment by BCantos17** [comment]
Have you tried with reactive context? I am assuming that using the DgsCustomContextBuilder does not work when implementing a reactive app.
Example is found here: https://github.com/Netflix/dgs-framework/issues/375#issuecomment-864326805

**Comment by achaubey-interface** [comment]
For this scenario, I have just added the custom context logic on top of the [official example](https://github.com/Netflix/dgs-examples-webflux) . If you refer the second screenshot pasted above, I access the custom context in the Data fetcher like this -

`@DgsData(parentType = DgsConstants.SHOW.TYPE_NAME, field = DgsConstants.SHOW.Reviews)
    public CompletableFuture<List<Review>> reviews(DgsDataFetchingEnvironment dfe, @InputArgument DateRange dateRange) {
        MyContext customContext = DgsContext.getCustomContext(dfe);`

It should ideally fetch the custom context being set in the `MyContextBuilder` class shown in the first screenshot right ?

**Comment by AyushChaubey** [comment]
> Have you tried with reactive context? I am assuming that using the DgsCustomContextBuilder does not work when implementing a reactive app.
> Example is found here: [#375 (comment)](https://github.com/Netflix/dgs-framework/issues/375#issuecomment-864326805)

For this scenario, I have just added the custom context logic on top of the [official example](https://github.com/Netflix/dgs-examples-webflux) . If you refer the second screenshot pasted above, I access the custom context in the Data fetcher like below. It should ideally fetch the custom context being set in the MyContextBuilder class shown in the first screenshot right ?

    public CompletableFuture<List<Review>> reviews(DgsDataFetchingEnvironment dfe, 
                                                       @InputArgument DateRange dateRange) {
        MyContext customContext = DgsContext.getCustomContext(dfe);```

**Comment by AyushChaubey** [comment]
> 

This work correctly. Thanks for your help. I think there should be an update in the documentation to include details and example of fetching the custom context in a reactive set up.

**Comment by berngp** [comment]
The `ReactiveDgsContext` has the header information via the `DgsReactiveRequestData`.
