### ISSUE TITLE
Update examples and document feature for custom directives support using @DgsDirective

### ISSUE THREAD

**Issue by srinivasankavitha** [Netflix/dgs-framework#891]
Update this example with usage of custom directive: https://github.com/Netflix/dgs-examples-java
We have some examples part of the framework repo already: https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/test/kotlin/com/netflix/graphql/dgs/UppercaseDirective.kt

Update the documentation with the code snippet and explanation: https://github.com/Netflix/dgs/tree/main/docs

**Comment by wbaldoumas** [comment]
@srinivasankavitha is this still reserved for GHC open source day? Happy to pick this up, if not. 😄

**Comment by wbaldoumas** [comment]
Looks like there's already a code example in the dgs-examples-java repository [here](https://github.com/Netflix/dgs-examples-java/blob/main/src/main/java/com/example/demo/directives/UppercaseDirective.java).

I've gone ahead and created an initial set of simple documentation using that example for the DGS docs: https://github.com/Netflix/dgs/pull/149

Please take a look when you've got time, and have a great weekend. 😄
