### ISSUE TITLE
feature: ability to customise the subscription endpoint

### ISSUE THREAD

**Issue by Ancient-Dragon** [Netflix/dgs-framework#906]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue. Also consider discussing your idea on
the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) first.

## Describe the Feature Request

I would like to be able to config the subscriptions endpoint. Currently it is only able to be: /subscriptions whereas the graphql endpoint can be configured using:
`
dgs:
  graphql:
    path: /api2/graphql
`

## Describe Preferred Solution

The preferred solution would be to a new property under graphql called subscription.path or something and then the subscription endpoint uses that. 

## Describe Alternatives

None

**Comment by srinivasankavitha** [comment]
Thanks for the request. We will look into supporting this in a future release.

**Comment by Ancient-Dragon** [comment]
Thank you!
