### ISSUE TITLE
bug: 'errors' property is never populated for GraphQL subscriptions

### ISSUE THREAD

**Issue by raindrop23** [Netflix/dgs-framework#914]
## Expected behavior

When I receive an event in the Response Stream for a GraphQL subscription, I expect the `errors` property to be non-empty if an error occurred for any field during the execution of the GraphQL operation.

## Actual behavior

The `errors` property is always empty.

## Steps to reproduce

These steps are based on a slightly modified version of https://github.com/Netflix/dgs-examples-kotlin .

### 1
Get a local copy of https://github.com/raindrop23/dgs-examples-kotlin/commit/d44060acb77814b7cf533b45901de55e96150938 . (That commit is the only change I made after forking [dgs-examples-kotlin](https://github.com/Netflix/dgs-examples-kotlin).)

### 2
Start the GraphQL web service locally.

### 3
Install [websocat](https://github.com/vi/websocat). (Here are [installation instructions](https://github.com/vi/websocat#installation).)

### 4
Run this command:

```
websocat ws://localhost:8080/subscriptions --protocol graphql-ws -v
```

### 5
Paste in the following line:

```json
{"type":"connection_init"}
```

Paste it in as a full line, so that the cursor goes to the start of the next line.

### 6
Paste in the following line:

```json
{"id":"5","type":"start","payload":{"query":"subscription { reviewAdded(showId: 1) {  ipAddress starScore username  } }"}}
```

Again, paste it in as a full line.

### 7
In a local web browser, access GraphiQL at http://localhost:8080/graphiql. Enter the following GraphQL operation and execute it.

```graphql
mutation {
  addReview(review: {
    showId: 1
    username: "user1"
    starScore: 5
  }) {
    __typename
  }
}
```

### 8
Look at the terminal where `websocat` is running. Observe that the review has appeared as an event in the Response Stream. Observe that the value of `ipAddress` is "1.1.1.1".

### 9
Return to GraphiQL. Slightly edit the value of `username` and `starScore` to produce the following operation, then execute it.

```graphql
mutation {
  addReview(review: {
    showId: 1
    username: "user2"
    starScore: 1
  }) {
    __typename
  }
}
```

### 10
In the output of the local GraphQL web service, observe that a stack trace has appeared, preceded by the message "Exception while executing data fetcher for /reviewAdded/ipAddress: null". (That message is because an exception was thrown on [this line of code](https://github.com/raindrop23/dgs-examples-kotlin/blob/d44060acb77814b7cf533b45901de55e96150938/src/main/kotlin/com/example/demo/datafetchers/ReviewsDataFetcher.kt#L56).)

### 11
Look at the terminal where `websocat` is running. Observe that the review has appeared as an event in the Response Stream. Observe that the value of `ipAddress` is `null`. Observe also that the value of the `errors` property is an empty array.

## Discussion

Further to the last step: it's clear from the GraphQL specification that `errors` should be non-empty. [Section 6.2.3.2](https://spec.graphql.org/October2021/#sec-Response-Stream) says:

> 5. Let *errors* be any *field errors* produced while executing the selection set.

## Clean-up

You can terminate the `websocat` process by typing Control-C.

**Comment by berngp** [comment]
Thanks for reporting with such a detail set of instructions.

**Comment by jord1e** [comment]
Shouldn't

https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-subscriptions-websockets/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketHandler.kt#L121

Be

```diff
- val message = OperationMessage(GQL_DATA, DataPayload(er.getData()), id)
+ val message = OperationMessage(GQL_DATA, DataPayload(er.getData(), er.getErrors()), id)
```

See line 70 https://github.com/Netflix/dgs-framework/blob/ac8c708352b3c58332c91bbe4feb18d3e45df078/graphql-dgs-subscription-types/src/main/kotlin/com/netflix/graphql/types/subscription/OperationMessage.kt#L66-L71

**Comment by srinivasankavitha** [comment]
Yes, that is the issue. We will fix this in the upcoming release.
