### ISSUE TITLE
Shorthand Annotations

### ISSUE THREAD

**Issue by aramir** [Netflix/dgs-framework#92]
In an effort to make code less verbose and easier to read: in addition to `@DgsData` annotation please consider adding the following two:

 - `@DgsQuery`
 - `@DgsMutation`

which are to serve as shorthands for `parentType="Query"` and `parentType="Mutation"`, respectively.

Further, it would be great to have a `field` parameter for the above annotations (as well as for `@DgsData`) as optional and have it to default to the annotated method's name.

This way the following annotation:
```java
@DgsData(parentType = "Query", field = "shows")
public List<Show> shows()
```
Becomes:
```java
@DgsQuery
public List<Show> shows()
```
Which is much more compact and follows the same approach that Spring Framework takes for composed annotations `@GetMapping`/`@PostMapping` vs `@RequestMapping(...)`

**Comment by paulbakker** [comment]
`@DgsData` is used both to define queries/mutations, but also for field datafetchers on other types. Would you still use `@DgsData` for those? And the new annotations would just be shortcuts for query/mutation fields? For example: 

```
@DgsQuery
List<Show> shows() {}

@DgsData(type = "Show", field = "director")
Director director() {}
```

I'll give it some more thought, but I think I like the idea.

**Comment by aramir** [comment]
> `@DgsData` is used both to define queries/mutations, but also for field datafetchers on other types. Would you still use `@DgsData` for those?

Of course! Just additional shorthands - but with `parentType = Query/Mutation` being the most common ones out there - that would eliminate a lot of boilerplate.

**Comment by golfingal72** [comment]
2 Other Ideas:

1). We have a union type class, a field from the abstract maps to different target field names.. this way, no need to
write 5 resolvers

@DgsDatas(datas = {
            @DgsData(field = "productId", parentType = FavoriteProductDto.class),
            @DgsData(field = "brandId", parentType = FavoriteBrandDto.class),
            @DgsData(field = "retailerId", parentType = FavoriteRetailerDto.class),
            @DgsData(field = "userId", parentType = FavoriteUserDto.class),
            @DgsData(field = "postId", parentType = FavoritePostDto.class)
    })
   public Object favObjectIdFetcher(DataFetchingEnvironment environment) {
        log.trace("favObjectIdFetcher()");
        return ((Favorite) environment.getSource()).getReferencedId();
    }

2.  Same target field into different schema objects.. again no need to write 5 different resolvers ( I suppose if you implemented option 1, then the below could be satisfied with that

@DgsData(field = "referralPartnerId", parentType = {
            FavoriteProductDto.class,
            FavoriteBrandDto.class,
            FavoriteRetailerDto.class,
            FavoriteUserDto.class,
            FavoritePostDto.class
    })
public Long favReferralPartnerIdFetcher(DataFetchingEnvironment environment) {
        Favorite favorite = environment.getSource();
        return favorite.getReferralPartnerId() != null
                ? favorite.getReferralPartnerId()
                : NumberUtils.LONG_ZERO;
    }

**Comment by paulbakker** [comment]
@golfingal72 I like your idea, but we’ll take it on separately. Would you mind copying your idea into a new issue?
