### ISSUE TITLE
bug: @RequestHeader does not support Map<String, String>

### ISSUE THREAD

**Issue by evanmalmud** [Netflix/dgs-framework#934]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

Expect when using `@RequestHeader HttpHeaders headers` to get the list of headers included. Currently it is null.

If I attempt to get a specific header - `@RequestHeader("content-type") String contentType` i get the value from the request.

## Actual behavior

Because it is using the Spring framework annotation I would expect it to support the Map/MultiMap/HttpHeaders section of it. 
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestHeader.html

Currently when I try
`
@DgsQuery
  public CompletableFuture<Map<String, Object>> byId(
          DataFetchingEnvironment dfe,
          @InputArgument Integer Id,
          @RequestHeader HttpHeaders headers) {
`
I get the following error 
`
Exception while executing data fetcher for /byId: Required header 'headers' was not provided
block-api  | 
block-api  | com.netflix.graphql.dgs.exceptions.DgsInvalidInputArgumentException: Required header 'headers' was not provided
`

If I give @RequestHeaders the literal name for each header it works as expected.

## Steps to reproduce

Add
`@RequestHeader HttpHeaders headers` or
`@RequestHeader Map<String, String> headers` or
`@RequestHeader MultiValueMap<String, String> headers`

to any dgs query.

**Comment by evanmalmud** [comment]
# Workaround

Found that this works - 
`  @DgsQuery
  public CompletableFuture<Map<String, Object>> ById(
          DgsDataFetchingEnvironment dfe,
          @InputArgument Integer Id) {
    HttpHeaders headers = dfe.getDgsContext().getRequestData().getHeaders();`

Using the DgsDataFetchingEnvironment over the DataFetchingEnvironment helps

**Comment by srinivasankavitha** [comment]
@evanmalmud - this is a feature available to you via the DgsDataFetchingEnvironment, so it's not a workaround. Rather the recommended way of accessing the Request headers: https://netflix.github.io/dgs/datafetching/#using-dgsrequestdata-to-get-access-to-the-request-object

Closing this issue since it is not actually a bug.

**Comment by evanmalmud** [comment]
It feels more like a bug because a feature that works outside of DGS, does not work with DGS. Albeit if i'm the first one bringing it up, it doesn't seem like a huge issue. Ultimately it seems like it would just be easier to work with the information if you allowed the HashMap mapping.

I Am stil having issues grabbing headers.
I realize that the secondary way is a feature to do this, but I'm also having an issue grabbing this setup during graphql registry. For instance we are using a 
`GraphQLCodeRegistry` to build out dynamic queries, but it relies on
`codeRegistryBuilder.dataFetcher(coordinates, ((DataFetchingEnvironment dfe) -> {`

I feel like grabbing the headers is much harder than it should be for some reason during unit tests.

This does seem to cast to DgsDataFetchingEnvironment in runtime, but having issues casting this during unit tests.


Finally, I gave up on all this and wrote a servlet filter. This works in runtime, but again am having issues getting this to work during unit testing. 

Any insight would be very helpful.


Sort of humorous you nailed the programmer trope.
> "this is a feature"..."it is not actually a bug."

**Comment by paulbakker** [comment]
I agree that this is a bug (or rather not fully implemented feature). If these work in Spring, it should work in DGS as well, the goal is to have similar behavior.

**Comment by srinivasankavitha** [comment]
@evanmalmud - Apologies for the confusion. I got sidetracked by your comment regarding usage of DgsDataFetchingEnvironment over DataFetchingEnvironment. The issue you reported is valid and we will fix this in an upcoming release soon.

**Comment by evanmalmud** [comment]
I did ultimately get headers working much more easily using a CustomContext. 
https://netflix.github.io/dgs/advanced/custom-datafetcher-context/

That is WAY easier than doing the other approaches in my opinion.

Thanks for the help.

**Comment by srinivasankavitha** [comment]
This fix will be available in the next release.

**Comment by evanmalmud** [comment]
woo!
