### ISSUE TITLE
feature: support Spring Boot 3.0.0-M2

### ISSUE THREAD

**Issue by pgrosslicht** [Netflix/dgs-framework#948]
## Expected behavior
Fully work in a Spring Boot 3.0.0-M2 project.
## Actual behavior
GraphiQL autoconfiguration prevents Spring Boot from starting, DgsDataLoaders don't get picked up.
## Steps to reproduce
1. Create a plain Spring Boot 3.0.0 project (https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=3.0.0-M2&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo)
2. Add Netflix DGS Spring Boot Starter to dependencies: `implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter:4.9.24")`
3. Start application and notice it failing to start with the following error:
```Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 34 common frames omitted
```

As described [here](https://spring.io/blog/2022/01/20/spring-boot-3-0-0-m1-is-now-available), Spring has migrated all Java EE APIs from `javax` to `jakarta`, so usages would need to be adapted.

While Spring Boot 3.0.0's general availability is planned for November 2022, I think it still might be important on how this will be handled.

**Comment by srinivasankavitha** [comment]
Thanks for bringing this up and trying it out. We are aware of the upcoming release, and will be planning to update the framework later this year to Spring Boot `3.0.0`.

**Comment by sweller999** [comment]
Confirming that this issue is still present in 3.0.0. Have a project with a graphql autoconfig that fails to initiate on startup due to missing graphql.GraphQL condition

<img width="867" alt="Screen Shot 2023-01-06 at 8 45 34 AM" src="https://user-images.githubusercontent.com/74434932/211058396-9862f3f4-2fc5-400f-affa-694fea8fadce.png">

**Comment by srinivasankavitha** [comment]
We have a candidate branch we are currently testing out and will be ready for release in the next couple weeks: `spring-boot-3-candidate`.  This thread has updates as well: https://github.com/Netflix/dgs-framework/issues/1340

**Comment by srinivasankavitha** [comment]
I will close this issue in favor of the other one that is a duplicate.
