### ISSUE TITLE
Provide access to WebRequest in DgsCustomContextBuilder

### ISSUE THREAD

**Issue by ntungare** [Netflix/dgs-framework#95]
Is it possible to provide access to the original request in the [DgsCustomContextBuilder](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/context/DgsCustomContextBuilder.kt)?

Background:
In the company where I work, we use Apollo Federation Gateway to generate certain headers related to the client and also forward certain user-level cookies over to the Federated Services.

Generally we are able to create a custom [GraphQLInvocation](https://github.com/graphql-java/graphql-java-spring/blob/master/graphql-java-spring-webmvc/src/main/java/graphql/spring/web/servlet/GraphQLInvocation.java) and get access to the `WebRequest` via which we can read all these details and then do things with the `WebRequest` such as authenticating the cookies and perform some side effects that are common for all DataFetchers.

I'm not entirely sure if this currently possible and whether such a functionality is possible.

**Comment by ntungare** [comment]
I think I have this figured out by using Spring to extract current Request:
```java
public static Optional<HttpServletRequest> getCurrentHttpRequest() {
    return Optional.ofNullable(RequestContextHolder.getRequestAttributes())
            .filter(requestAttributes -> ServletRequestAttributes.class.isAssignableFrom(requestAttributes.getClass()))
            .map(requestAttributes -> ((ServletRequestAttributes) requestAttributes))
            .map(ServletRequestAttributes::getRequest);
}
```

But we do lose the visibility into the extensions that the [default context](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsQueryExecutor.kt#L74) has access to.

**Comment by paulbakker** [comment]
Be aware that this can be problematic when working with async datafetchers that run on different threads. Spring uses ThreadLocal to store these things (for Spring WebMVC that is).
I do agree that at the very least we need documentation around this.

**Comment by ntungare** [comment]
Yep, would love some docs for best practices on this from DGS perspective.

And re thread local + datafetchers, I do agree that this could be problematic for async datafetchers but accessing the request only in [DgsCustomContextBuilder](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/context/DgsCustomContextBuilder.kt) should be relatively safe, but obviously depends on how that builder is written.

**Comment by paulbakker** [comment]
We do plan to pick up this topic very soon btw. Not sure about the exact implementation yet, but we'll figure that out.

**Comment by paulbakker** [comment]
Fixed in #112

**Comment by ntungare** [comment]
Just now getting around to this

Looks like the webrequest is added to the context after the custom context builder has run, so I don't think this addresses this issue exactly.

While it is great that the original webrequest is made accessible to the lower down datafetchers/dataloaders, this request is not made available to the DgsCustomContextBuilder (I'm guessing for compatibility reasons).

This does restrict the work we can do in the graphql context.

Kinda still have to access the request using the solution I had detailed above.

Ideally there is a nicer way to access current request and use the data in said request to generate common things for the shared graphql context.

**Comment by paulbakker** [comment]
I interpreted the original issue as "we need access to WebRequest", which is probably the most common case. But indeed, it doesn't give you access to in the builder for further processing. We can probably add that as well.

Just curious, what do you need it for in the builder?

**Comment by ntungare** [comment]
The reason to need access to the webrequest in the builder is quite simple, it will then let us extract information out and persist it in the context in a structured way. And also let us perform some side-effects based on that data that would be common for **all** datafetchers/dataloaders early on in the stack, rather than do it per datafetcher/dataloader.

**Comment by paulbakker** [comment]
Yes, makes sense. I’ll re-open this issue to further address it.

**Comment by paulbakker** [comment]
Fixed by https://github.com/Netflix/dgs-framework/pull/169

**Comment by ntungare** [comment]
Thank you very much @paulbakker, this was probably my only blocker to convert an existing GraphQL service my team has over to Netflix DGS.

I appreciate the work you guys have put into this and it's been great to use it!
