### ISSUE TITLE
feature: Local Time Scalar

### ISSUE THREAD

**Issue by Ancient-Dragon** [Netflix/dgs-framework#953]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue. Also consider discussing your idea on
the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) first.

## Describe the Feature Request

Supporting a local time scalar, this would allow the user of the library to have a java local time as an input argument.

## Describe Preferred Solution

I guess there could be two ways this could be implemented:
- DGS could use latest version of [graphql-java-extended-scalars](https://github.com/graphql-java/graphql-java-extended-scalars) - [2022-02-25T03-14-46-8c3b172](https://mvnrepository.com/artifact/com.graphql-java/graphql-java-extended-scalars/2022-02-25T03-14-46-8c3b172)
- DGS could implement its own version of a local time scalar

## Describe Alternatives

We could implement a custom scalar, but we felt that this could be widely used by other people.

**Comment by srinivasankavitha** [comment]
Thanks, seems reasonable to update to the latest version of
extended-scalars. Will do that for the next release (mostly next week).

**Comment by setchy** [comment]
As far as I'm aware, DGS already uses the latest published version of graphql-java-extended-scalars (v17.0) that isn't a nightly snapshot, but in 17.0 `LocalTime` isn't part of their [ExtendedScalars](https://github.com/graphql-java/graphql-java-extended-scalars/blob/master/src/main/java/graphql/scalars/ExtendedScalars.java) entry point, which I'd be guessing is why it wasn't referenced in https://github.com/Netflix/dgs-framework/blob/5bfe8dd25f268653bda5bca06d6bbe70c7359575/graphql-dgs-extended-scalars/src/main/kotlin/com/netflix/graphql/dgs/autoconfig/DgsExtendedScalarsAutoConfiguration.kt#L48

I've raised a simple PR https://github.com/graphql-java/graphql-java-extended-scalars/pull/57 to get the ball rolling on a new non-snapshot version that will also include a proper `ExtendedScalars.LocalTime` entry point

**Comment by setchy** [comment]
@Ancient-Dragon @joshvince - released in v4.10.0
