### ISSUE TITLE
bug: Error using custom federation resolvers, "The dependencies of some of the beans in the application context form a cycle."

### ISSUE THREAD

**Issue by MayCXC** [Netflix/dgs-framework#961]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior

Implement a custom typeMapping as documented [https://netflix.github.io/dgs/federation/#customizing-the-default-federation-resolver](here) in a consumer project and see it behave as expected.

## Actual behavior

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  myFederationResolver (field public com.netflix.graphql.dgs.internal.DgsSchemaProvider com.netflix.graphql.dgs.federation.DefaultDgsFederationResolver.dgsSchemaProvider)
↑     ↓
|  dgsSchemaProvider defined in class path resource [com/netflix/graphql/dgs/autoconfig/DgsAutoConfiguration.class]
└─────┘
```

## Steps to reproduce

Can be reproduced in [https://github.com/MayCXC/dgs-federation-example/tree/test/dgs-auto-configuration](this) DGS by using version 4.9.17 of the DGS framework platform package [here](https://github.com/MayCXC/dgs-federation-example/blob/test/dgs-auto-configuration/inner-dgs/build.gradle.kts#L34) and [here](https://github.com/MayCXC/dgs-federation-example/blob/test/dgs-auto-configuration/outer-dgs/build.gradle.kts#L34).

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by srinivasankavitha** [comment]
Already fixed in `4.9.22`. Please try and let us know if you still experience issues.
