### ISSUE TITLE
Doc: example of separate field resolver

### ISSUE THREAD

**Issue by xenoterracide** [Netflix/dgs-framework#97]
Ok, so I read the documentation, all of it last night. I may have been tired, and may not have been thorough, so I apologize if this is covered. I saw a case for this in the Federation examples in the blog post, but not if Federation isn't being used. If you have a field on an object that needs its own resolver/data fetcher, because it's doing another query, how do you do that? if it's documented can you point me to that? if not I think it would be a good page to add. I think I know how to do it, I just can't find the documentation. Here's an example (we could talk about how this is the wrong model, but it's just an example).

```graphql
type Query {
    shows(titleFilter: String): [Show]
}

type Show {
    title: String
    releaseYear: Int
    watchedTimes: Int # I'm not stored in the same table, in fact, I'm just another query, and I shouldn't be fetched unless I'm asked for by the client
}
```

**Comment by paulbakker** [comment]
Short answer: 

The `@DgsData` annotation takes a `parentType` and `field` parameter. You can define one for any field. E.g. for your example schema:

```
@DgsData(parntType = "Query", field = "shows")
List<Show> shows() 
 //Create shows with title and releaseYear
}

@DgsData(parentType = "Show", field = "watchedTimes")
int watched(DgsDataFetchtingEnvironment dfe) {
    Show show = dfe.getSource();
    
    return watchedService.getForShow(show.getId());
}
   
```

The second datafetcher uses the `getSource()` method to get the parent object, which in this case is a `Show`.

Good idea to further illustrate this in the docs. I'll keep this issue open for that.

**Comment by paulbakker** [comment]
Wrote a whole new datafetching guide, which covers this topic: https://netflix.github.io/dgs/datafetching/
